// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NeoPlayful/maple-gateway/server/ent/bluegreenevent"
	"github.com/NeoPlayful/maple-gateway/server/ent/predicate"
	"github.com/google/uuid"
)

// BluegreenEventUpdate is the builder for updating BluegreenEvent entities.
type BluegreenEventUpdate struct {
	config
	hooks    []Hook
	mutation *BluegreenEventMutation
}

// Where appends a list predicates to the BluegreenEventUpdate builder.
func (beu *BluegreenEventUpdate) Where(ps ...predicate.BluegreenEvent) *BluegreenEventUpdate {
	beu.mutation.Where(ps...)
	return beu
}

// SetBgID sets the "bg_id" field.
func (beu *BluegreenEventUpdate) SetBgID(u uuid.UUID) *BluegreenEventUpdate {
	beu.mutation.SetBgID(u)
	return beu
}

// SetNillableBgID sets the "bg_id" field if the given value is not nil.
func (beu *BluegreenEventUpdate) SetNillableBgID(u *uuid.UUID) *BluegreenEventUpdate {
	if u != nil {
		beu.SetBgID(*u)
	}
	return beu
}

// SetAction sets the "action" field.
func (beu *BluegreenEventUpdate) SetAction(s string) *BluegreenEventUpdate {
	beu.mutation.SetAction(s)
	return beu
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (beu *BluegreenEventUpdate) SetNillableAction(s *string) *BluegreenEventUpdate {
	if s != nil {
		beu.SetAction(*s)
	}
	return beu
}

// SetFromActive sets the "from_active" field.
func (beu *BluegreenEventUpdate) SetFromActive(u uuid.UUID) *BluegreenEventUpdate {
	beu.mutation.SetFromActive(u)
	return beu
}

// SetNillableFromActive sets the "from_active" field if the given value is not nil.
func (beu *BluegreenEventUpdate) SetNillableFromActive(u *uuid.UUID) *BluegreenEventUpdate {
	if u != nil {
		beu.SetFromActive(*u)
	}
	return beu
}

// ClearFromActive clears the value of the "from_active" field.
func (beu *BluegreenEventUpdate) ClearFromActive() *BluegreenEventUpdate {
	beu.mutation.ClearFromActive()
	return beu
}

// SetToActive sets the "to_active" field.
func (beu *BluegreenEventUpdate) SetToActive(u uuid.UUID) *BluegreenEventUpdate {
	beu.mutation.SetToActive(u)
	return beu
}

// SetNillableToActive sets the "to_active" field if the given value is not nil.
func (beu *BluegreenEventUpdate) SetNillableToActive(u *uuid.UUID) *BluegreenEventUpdate {
	if u != nil {
		beu.SetToActive(*u)
	}
	return beu
}

// ClearToActive clears the value of the "to_active" field.
func (beu *BluegreenEventUpdate) ClearToActive() *BluegreenEventUpdate {
	beu.mutation.ClearToActive()
	return beu
}

// SetDetail sets the "detail" field.
func (beu *BluegreenEventUpdate) SetDetail(s string) *BluegreenEventUpdate {
	beu.mutation.SetDetail(s)
	return beu
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (beu *BluegreenEventUpdate) SetNillableDetail(s *string) *BluegreenEventUpdate {
	if s != nil {
		beu.SetDetail(*s)
	}
	return beu
}

// ClearDetail clears the value of the "detail" field.
func (beu *BluegreenEventUpdate) ClearDetail() *BluegreenEventUpdate {
	beu.mutation.ClearDetail()
	return beu
}

// Mutation returns the BluegreenEventMutation object of the builder.
func (beu *BluegreenEventUpdate) Mutation() *BluegreenEventMutation {
	return beu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (beu *BluegreenEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, beu.sqlSave, beu.mutation, beu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (beu *BluegreenEventUpdate) SaveX(ctx context.Context) int {
	affected, err := beu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (beu *BluegreenEventUpdate) Exec(ctx context.Context) error {
	_, err := beu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (beu *BluegreenEventUpdate) ExecX(ctx context.Context) {
	if err := beu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (beu *BluegreenEventUpdate) check() error {
	if v, ok := beu.mutation.Action(); ok {
		if err := bluegreenevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "BluegreenEvent.action": %w`, err)}
		}
	}
	return nil
}

func (beu *BluegreenEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := beu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(bluegreenevent.Table, bluegreenevent.Columns, sqlgraph.NewFieldSpec(bluegreenevent.FieldID, field.TypeUUID))
	if ps := beu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := beu.mutation.BgID(); ok {
		_spec.SetField(bluegreenevent.FieldBgID, field.TypeUUID, value)
	}
	if value, ok := beu.mutation.Action(); ok {
		_spec.SetField(bluegreenevent.FieldAction, field.TypeString, value)
	}
	if value, ok := beu.mutation.FromActive(); ok {
		_spec.SetField(bluegreenevent.FieldFromActive, field.TypeUUID, value)
	}
	if beu.mutation.FromActiveCleared() {
		_spec.ClearField(bluegreenevent.FieldFromActive, field.TypeUUID)
	}
	if value, ok := beu.mutation.ToActive(); ok {
		_spec.SetField(bluegreenevent.FieldToActive, field.TypeUUID, value)
	}
	if beu.mutation.ToActiveCleared() {
		_spec.ClearField(bluegreenevent.FieldToActive, field.TypeUUID)
	}
	if value, ok := beu.mutation.Detail(); ok {
		_spec.SetField(bluegreenevent.FieldDetail, field.TypeString, value)
	}
	if beu.mutation.DetailCleared() {
		_spec.ClearField(bluegreenevent.FieldDetail, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, beu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bluegreenevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	beu.mutation.done = true
	return n, nil
}

// BluegreenEventUpdateOne is the builder for updating a single BluegreenEvent entity.
type BluegreenEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BluegreenEventMutation
}

// SetBgID sets the "bg_id" field.
func (beuo *BluegreenEventUpdateOne) SetBgID(u uuid.UUID) *BluegreenEventUpdateOne {
	beuo.mutation.SetBgID(u)
	return beuo
}

// SetNillableBgID sets the "bg_id" field if the given value is not nil.
func (beuo *BluegreenEventUpdateOne) SetNillableBgID(u *uuid.UUID) *BluegreenEventUpdateOne {
	if u != nil {
		beuo.SetBgID(*u)
	}
	return beuo
}

// SetAction sets the "action" field.
func (beuo *BluegreenEventUpdateOne) SetAction(s string) *BluegreenEventUpdateOne {
	beuo.mutation.SetAction(s)
	return beuo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (beuo *BluegreenEventUpdateOne) SetNillableAction(s *string) *BluegreenEventUpdateOne {
	if s != nil {
		beuo.SetAction(*s)
	}
	return beuo
}

// SetFromActive sets the "from_active" field.
func (beuo *BluegreenEventUpdateOne) SetFromActive(u uuid.UUID) *BluegreenEventUpdateOne {
	beuo.mutation.SetFromActive(u)
	return beuo
}

// SetNillableFromActive sets the "from_active" field if the given value is not nil.
func (beuo *BluegreenEventUpdateOne) SetNillableFromActive(u *uuid.UUID) *BluegreenEventUpdateOne {
	if u != nil {
		beuo.SetFromActive(*u)
	}
	return beuo
}

// ClearFromActive clears the value of the "from_active" field.
func (beuo *BluegreenEventUpdateOne) ClearFromActive() *BluegreenEventUpdateOne {
	beuo.mutation.ClearFromActive()
	return beuo
}

// SetToActive sets the "to_active" field.
func (beuo *BluegreenEventUpdateOne) SetToActive(u uuid.UUID) *BluegreenEventUpdateOne {
	beuo.mutation.SetToActive(u)
	return beuo
}

// SetNillableToActive sets the "to_active" field if the given value is not nil.
func (beuo *BluegreenEventUpdateOne) SetNillableToActive(u *uuid.UUID) *BluegreenEventUpdateOne {
	if u != nil {
		beuo.SetToActive(*u)
	}
	return beuo
}

// ClearToActive clears the value of the "to_active" field.
func (beuo *BluegreenEventUpdateOne) ClearToActive() *BluegreenEventUpdateOne {
	beuo.mutation.ClearToActive()
	return beuo
}

// SetDetail sets the "detail" field.
func (beuo *BluegreenEventUpdateOne) SetDetail(s string) *BluegreenEventUpdateOne {
	beuo.mutation.SetDetail(s)
	return beuo
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (beuo *BluegreenEventUpdateOne) SetNillableDetail(s *string) *BluegreenEventUpdateOne {
	if s != nil {
		beuo.SetDetail(*s)
	}
	return beuo
}

// ClearDetail clears the value of the "detail" field.
func (beuo *BluegreenEventUpdateOne) ClearDetail() *BluegreenEventUpdateOne {
	beuo.mutation.ClearDetail()
	return beuo
}

// Mutation returns the BluegreenEventMutation object of the builder.
func (beuo *BluegreenEventUpdateOne) Mutation() *BluegreenEventMutation {
	return beuo.mutation
}

// Where appends a list predicates to the BluegreenEventUpdate builder.
func (beuo *BluegreenEventUpdateOne) Where(ps ...predicate.BluegreenEvent) *BluegreenEventUpdateOne {
	beuo.mutation.Where(ps...)
	return beuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (beuo *BluegreenEventUpdateOne) Select(field string, fields ...string) *BluegreenEventUpdateOne {
	beuo.fields = append([]string{field}, fields...)
	return beuo
}

// Save executes the query and returns the updated BluegreenEvent entity.
func (beuo *BluegreenEventUpdateOne) Save(ctx context.Context) (*BluegreenEvent, error) {
	return withHooks(ctx, beuo.sqlSave, beuo.mutation, beuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (beuo *BluegreenEventUpdateOne) SaveX(ctx context.Context) *BluegreenEvent {
	node, err := beuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (beuo *BluegreenEventUpdateOne) Exec(ctx context.Context) error {
	_, err := beuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (beuo *BluegreenEventUpdateOne) ExecX(ctx context.Context) {
	if err := beuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (beuo *BluegreenEventUpdateOne) check() error {
	if v, ok := beuo.mutation.Action(); ok {
		if err := bluegreenevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "BluegreenEvent.action": %w`, err)}
		}
	}
	return nil
}

func (beuo *BluegreenEventUpdateOne) sqlSave(ctx context.Context) (_node *BluegreenEvent, err error) {
	if err := beuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bluegreenevent.Table, bluegreenevent.Columns, sqlgraph.NewFieldSpec(bluegreenevent.FieldID, field.TypeUUID))
	id, ok := beuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BluegreenEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := beuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bluegreenevent.FieldID)
		for _, f := range fields {
			if !bluegreenevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bluegreenevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := beuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := beuo.mutation.BgID(); ok {
		_spec.SetField(bluegreenevent.FieldBgID, field.TypeUUID, value)
	}
	if value, ok := beuo.mutation.Action(); ok {
		_spec.SetField(bluegreenevent.FieldAction, field.TypeString, value)
	}
	if value, ok := beuo.mutation.FromActive(); ok {
		_spec.SetField(bluegreenevent.FieldFromActive, field.TypeUUID, value)
	}
	if beuo.mutation.FromActiveCleared() {
		_spec.ClearField(bluegreenevent.FieldFromActive, field.TypeUUID)
	}
	if value, ok := beuo.mutation.ToActive(); ok {
		_spec.SetField(bluegreenevent.FieldToActive, field.TypeUUID, value)
	}
	if beuo.mutation.ToActiveCleared() {
		_spec.ClearField(bluegreenevent.FieldToActive, field.TypeUUID)
	}
	if value, ok := beuo.mutation.Detail(); ok {
		_spec.SetField(bluegreenevent.FieldDetail, field.TypeString, value)
	}
	if beuo.mutation.DetailCleared() {
		_spec.ClearField(bluegreenevent.FieldDetail, field.TypeString)
	}
	_node = &BluegreenEvent{config: beuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, beuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bluegreenevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	beuo.mutation.done = true
	return _node, nil
}
