// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NeoPlayful/maple-gateway/server/ent/bluegreenevent"
	"github.com/google/uuid"
)

// BluegreenEventCreate is the builder for creating a BluegreenEvent entity.
type BluegreenEventCreate struct {
	config
	mutation *BluegreenEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBgID sets the "bg_id" field.
func (bec *BluegreenEventCreate) SetBgID(u uuid.UUID) *BluegreenEventCreate {
	bec.mutation.SetBgID(u)
	return bec
}

// SetAction sets the "action" field.
func (bec *BluegreenEventCreate) SetAction(s string) *BluegreenEventCreate {
	bec.mutation.SetAction(s)
	return bec
}

// SetFromActive sets the "from_active" field.
func (bec *BluegreenEventCreate) SetFromActive(u uuid.UUID) *BluegreenEventCreate {
	bec.mutation.SetFromActive(u)
	return bec
}

// SetNillableFromActive sets the "from_active" field if the given value is not nil.
func (bec *BluegreenEventCreate) SetNillableFromActive(u *uuid.UUID) *BluegreenEventCreate {
	if u != nil {
		bec.SetFromActive(*u)
	}
	return bec
}

// SetToActive sets the "to_active" field.
func (bec *BluegreenEventCreate) SetToActive(u uuid.UUID) *BluegreenEventCreate {
	bec.mutation.SetToActive(u)
	return bec
}

// SetNillableToActive sets the "to_active" field if the given value is not nil.
func (bec *BluegreenEventCreate) SetNillableToActive(u *uuid.UUID) *BluegreenEventCreate {
	if u != nil {
		bec.SetToActive(*u)
	}
	return bec
}

// SetDetail sets the "detail" field.
func (bec *BluegreenEventCreate) SetDetail(s string) *BluegreenEventCreate {
	bec.mutation.SetDetail(s)
	return bec
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (bec *BluegreenEventCreate) SetNillableDetail(s *string) *BluegreenEventCreate {
	if s != nil {
		bec.SetDetail(*s)
	}
	return bec
}

// SetCreatedAt sets the "created_at" field.
func (bec *BluegreenEventCreate) SetCreatedAt(t time.Time) *BluegreenEventCreate {
	bec.mutation.SetCreatedAt(t)
	return bec
}

// SetID sets the "id" field.
func (bec *BluegreenEventCreate) SetID(u uuid.UUID) *BluegreenEventCreate {
	bec.mutation.SetID(u)
	return bec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (bec *BluegreenEventCreate) SetNillableID(u *uuid.UUID) *BluegreenEventCreate {
	if u != nil {
		bec.SetID(*u)
	}
	return bec
}

// Mutation returns the BluegreenEventMutation object of the builder.
func (bec *BluegreenEventCreate) Mutation() *BluegreenEventMutation {
	return bec.mutation
}

// Save creates the BluegreenEvent in the database.
func (bec *BluegreenEventCreate) Save(ctx context.Context) (*BluegreenEvent, error) {
	bec.defaults()
	return withHooks(ctx, bec.sqlSave, bec.mutation, bec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bec *BluegreenEventCreate) SaveX(ctx context.Context) *BluegreenEvent {
	v, err := bec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bec *BluegreenEventCreate) Exec(ctx context.Context) error {
	_, err := bec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bec *BluegreenEventCreate) ExecX(ctx context.Context) {
	if err := bec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bec *BluegreenEventCreate) defaults() {
	if _, ok := bec.mutation.Detail(); !ok {
		v := bluegreenevent.DefaultDetail
		bec.mutation.SetDetail(v)
	}
	if _, ok := bec.mutation.ID(); !ok {
		v := bluegreenevent.DefaultID()
		bec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bec *BluegreenEventCreate) check() error {
	if _, ok := bec.mutation.BgID(); !ok {
		return &ValidationError{Name: "bg_id", err: errors.New(`ent: missing required field "BluegreenEvent.bg_id"`)}
	}
	if _, ok := bec.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "BluegreenEvent.action"`)}
	}
	if v, ok := bec.mutation.Action(); ok {
		if err := bluegreenevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "BluegreenEvent.action": %w`, err)}
		}
	}
	if _, ok := bec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BluegreenEvent.created_at"`)}
	}
	return nil
}

func (bec *BluegreenEventCreate) sqlSave(ctx context.Context) (*BluegreenEvent, error) {
	if err := bec.check(); err != nil {
		return nil, err
	}
	_node, _spec := bec.createSpec()
	if err := sqlgraph.CreateNode(ctx, bec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	bec.mutation.id = &_node.ID
	bec.mutation.done = true
	return _node, nil
}

func (bec *BluegreenEventCreate) createSpec() (*BluegreenEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &BluegreenEvent{config: bec.config}
		_spec = sqlgraph.NewCreateSpec(bluegreenevent.Table, sqlgraph.NewFieldSpec(bluegreenevent.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = bec.conflict
	if id, ok := bec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := bec.mutation.BgID(); ok {
		_spec.SetField(bluegreenevent.FieldBgID, field.TypeUUID, value)
		_node.BgID = value
	}
	if value, ok := bec.mutation.Action(); ok {
		_spec.SetField(bluegreenevent.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := bec.mutation.FromActive(); ok {
		_spec.SetField(bluegreenevent.FieldFromActive, field.TypeUUID, value)
		_node.FromActive = &value
	}
	if value, ok := bec.mutation.ToActive(); ok {
		_spec.SetField(bluegreenevent.FieldToActive, field.TypeUUID, value)
		_node.ToActive = &value
	}
	if value, ok := bec.mutation.Detail(); ok {
		_spec.SetField(bluegreenevent.FieldDetail, field.TypeString, value)
		_node.Detail = value
	}
	if value, ok := bec.mutation.CreatedAt(); ok {
		_spec.SetField(bluegreenevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BluegreenEvent.Create().
//		SetBgID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BluegreenEventUpsert) {
//			SetBgID(v+v).
//		}).
//		Exec(ctx)
func (bec *BluegreenEventCreate) OnConflict(opts ...sql.ConflictOption) *BluegreenEventUpsertOne {
	bec.conflict = opts
	return &BluegreenEventUpsertOne{
		create: bec,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BluegreenEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bec *BluegreenEventCreate) OnConflictColumns(columns ...string) *BluegreenEventUpsertOne {
	bec.conflict = append(bec.conflict, sql.ConflictColumns(columns...))
	return &BluegreenEventUpsertOne{
		create: bec,
	}
}

type (
	// BluegreenEventUpsertOne is the builder for "upsert"-ing
	//  one BluegreenEvent node.
	BluegreenEventUpsertOne struct {
		create *BluegreenEventCreate
	}

	// BluegreenEventUpsert is the "OnConflict" setter.
	BluegreenEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetBgID sets the "bg_id" field.
func (u *BluegreenEventUpsert) SetBgID(v uuid.UUID) *BluegreenEventUpsert {
	u.Set(bluegreenevent.FieldBgID, v)
	return u
}

// UpdateBgID sets the "bg_id" field to the value that was provided on create.
func (u *BluegreenEventUpsert) UpdateBgID() *BluegreenEventUpsert {
	u.SetExcluded(bluegreenevent.FieldBgID)
	return u
}

// SetAction sets the "action" field.
func (u *BluegreenEventUpsert) SetAction(v string) *BluegreenEventUpsert {
	u.Set(bluegreenevent.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *BluegreenEventUpsert) UpdateAction() *BluegreenEventUpsert {
	u.SetExcluded(bluegreenevent.FieldAction)
	return u
}

// SetFromActive sets the "from_active" field.
func (u *BluegreenEventUpsert) SetFromActive(v uuid.UUID) *BluegreenEventUpsert {
	u.Set(bluegreenevent.FieldFromActive, v)
	return u
}

// UpdateFromActive sets the "from_active" field to the value that was provided on create.
func (u *BluegreenEventUpsert) UpdateFromActive() *BluegreenEventUpsert {
	u.SetExcluded(bluegreenevent.FieldFromActive)
	return u
}

// ClearFromActive clears the value of the "from_active" field.
func (u *BluegreenEventUpsert) ClearFromActive() *BluegreenEventUpsert {
	u.SetNull(bluegreenevent.FieldFromActive)
	return u
}

// SetToActive sets the "to_active" field.
func (u *BluegreenEventUpsert) SetToActive(v uuid.UUID) *BluegreenEventUpsert {
	u.Set(bluegreenevent.FieldToActive, v)
	return u
}

// UpdateToActive sets the "to_active" field to the value that was provided on create.
func (u *BluegreenEventUpsert) UpdateToActive() *BluegreenEventUpsert {
	u.SetExcluded(bluegreenevent.FieldToActive)
	return u
}

// ClearToActive clears the value of the "to_active" field.
func (u *BluegreenEventUpsert) ClearToActive() *BluegreenEventUpsert {
	u.SetNull(bluegreenevent.FieldToActive)
	return u
}

// SetDetail sets the "detail" field.
func (u *BluegreenEventUpsert) SetDetail(v string) *BluegreenEventUpsert {
	u.Set(bluegreenevent.FieldDetail, v)
	return u
}

// UpdateDetail sets the "detail" field to the value that was provided on create.
func (u *BluegreenEventUpsert) UpdateDetail() *BluegreenEventUpsert {
	u.SetExcluded(bluegreenevent.FieldDetail)
	return u
}

// ClearDetail clears the value of the "detail" field.
func (u *BluegreenEventUpsert) ClearDetail() *BluegreenEventUpsert {
	u.SetNull(bluegreenevent.FieldDetail)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.BluegreenEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(bluegreenevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BluegreenEventUpsertOne) UpdateNewValues() *BluegreenEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(bluegreenevent.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(bluegreenevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BluegreenEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BluegreenEventUpsertOne) Ignore() *BluegreenEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BluegreenEventUpsertOne) DoNothing() *BluegreenEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BluegreenEventCreate.OnConflict
// documentation for more info.
func (u *BluegreenEventUpsertOne) Update(set func(*BluegreenEventUpsert)) *BluegreenEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BluegreenEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetBgID sets the "bg_id" field.
func (u *BluegreenEventUpsertOne) SetBgID(v uuid.UUID) *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.SetBgID(v)
	})
}

// UpdateBgID sets the "bg_id" field to the value that was provided on create.
func (u *BluegreenEventUpsertOne) UpdateBgID() *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.UpdateBgID()
	})
}

// SetAction sets the "action" field.
func (u *BluegreenEventUpsertOne) SetAction(v string) *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *BluegreenEventUpsertOne) UpdateAction() *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.UpdateAction()
	})
}

// SetFromActive sets the "from_active" field.
func (u *BluegreenEventUpsertOne) SetFromActive(v uuid.UUID) *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.SetFromActive(v)
	})
}

// UpdateFromActive sets the "from_active" field to the value that was provided on create.
func (u *BluegreenEventUpsertOne) UpdateFromActive() *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.UpdateFromActive()
	})
}

// ClearFromActive clears the value of the "from_active" field.
func (u *BluegreenEventUpsertOne) ClearFromActive() *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.ClearFromActive()
	})
}

// SetToActive sets the "to_active" field.
func (u *BluegreenEventUpsertOne) SetToActive(v uuid.UUID) *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.SetToActive(v)
	})
}

// UpdateToActive sets the "to_active" field to the value that was provided on create.
func (u *BluegreenEventUpsertOne) UpdateToActive() *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.UpdateToActive()
	})
}

// ClearToActive clears the value of the "to_active" field.
func (u *BluegreenEventUpsertOne) ClearToActive() *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.ClearToActive()
	})
}

// SetDetail sets the "detail" field.
func (u *BluegreenEventUpsertOne) SetDetail(v string) *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.SetDetail(v)
	})
}

// UpdateDetail sets the "detail" field to the value that was provided on create.
func (u *BluegreenEventUpsertOne) UpdateDetail() *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.UpdateDetail()
	})
}

// ClearDetail clears the value of the "detail" field.
func (u *BluegreenEventUpsertOne) ClearDetail() *BluegreenEventUpsertOne {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.ClearDetail()
	})
}

// Exec executes the query.
func (u *BluegreenEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BluegreenEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BluegreenEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BluegreenEventUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BluegreenEventUpsertOne.ID is not supported by MySQL driver. Use BluegreenEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BluegreenEventUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BluegreenEventCreateBulk is the builder for creating many BluegreenEvent entities in bulk.
type BluegreenEventCreateBulk struct {
	config
	err      error
	builders []*BluegreenEventCreate
	conflict []sql.ConflictOption
}

// Save creates the BluegreenEvent entities in the database.
func (becb *BluegreenEventCreateBulk) Save(ctx context.Context) ([]*BluegreenEvent, error) {
	if becb.err != nil {
		return nil, becb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(becb.builders))
	nodes := make([]*BluegreenEvent, len(becb.builders))
	mutators := make([]Mutator, len(becb.builders))
	for i := range becb.builders {
		func(i int, root context.Context) {
			builder := becb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BluegreenEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, becb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = becb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, becb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, becb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (becb *BluegreenEventCreateBulk) SaveX(ctx context.Context) []*BluegreenEvent {
	v, err := becb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (becb *BluegreenEventCreateBulk) Exec(ctx context.Context) error {
	_, err := becb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (becb *BluegreenEventCreateBulk) ExecX(ctx context.Context) {
	if err := becb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BluegreenEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BluegreenEventUpsert) {
//			SetBgID(v+v).
//		}).
//		Exec(ctx)
func (becb *BluegreenEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *BluegreenEventUpsertBulk {
	becb.conflict = opts
	return &BluegreenEventUpsertBulk{
		create: becb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BluegreenEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (becb *BluegreenEventCreateBulk) OnConflictColumns(columns ...string) *BluegreenEventUpsertBulk {
	becb.conflict = append(becb.conflict, sql.ConflictColumns(columns...))
	return &BluegreenEventUpsertBulk{
		create: becb,
	}
}

// BluegreenEventUpsertBulk is the builder for "upsert"-ing
// a bulk of BluegreenEvent nodes.
type BluegreenEventUpsertBulk struct {
	create *BluegreenEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BluegreenEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(bluegreenevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BluegreenEventUpsertBulk) UpdateNewValues() *BluegreenEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(bluegreenevent.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(bluegreenevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BluegreenEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BluegreenEventUpsertBulk) Ignore() *BluegreenEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BluegreenEventUpsertBulk) DoNothing() *BluegreenEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BluegreenEventCreateBulk.OnConflict
// documentation for more info.
func (u *BluegreenEventUpsertBulk) Update(set func(*BluegreenEventUpsert)) *BluegreenEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BluegreenEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetBgID sets the "bg_id" field.
func (u *BluegreenEventUpsertBulk) SetBgID(v uuid.UUID) *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.SetBgID(v)
	})
}

// UpdateBgID sets the "bg_id" field to the value that was provided on create.
func (u *BluegreenEventUpsertBulk) UpdateBgID() *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.UpdateBgID()
	})
}

// SetAction sets the "action" field.
func (u *BluegreenEventUpsertBulk) SetAction(v string) *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *BluegreenEventUpsertBulk) UpdateAction() *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.UpdateAction()
	})
}

// SetFromActive sets the "from_active" field.
func (u *BluegreenEventUpsertBulk) SetFromActive(v uuid.UUID) *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.SetFromActive(v)
	})
}

// UpdateFromActive sets the "from_active" field to the value that was provided on create.
func (u *BluegreenEventUpsertBulk) UpdateFromActive() *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.UpdateFromActive()
	})
}

// ClearFromActive clears the value of the "from_active" field.
func (u *BluegreenEventUpsertBulk) ClearFromActive() *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.ClearFromActive()
	})
}

// SetToActive sets the "to_active" field.
func (u *BluegreenEventUpsertBulk) SetToActive(v uuid.UUID) *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.SetToActive(v)
	})
}

// UpdateToActive sets the "to_active" field to the value that was provided on create.
func (u *BluegreenEventUpsertBulk) UpdateToActive() *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.UpdateToActive()
	})
}

// ClearToActive clears the value of the "to_active" field.
func (u *BluegreenEventUpsertBulk) ClearToActive() *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.ClearToActive()
	})
}

// SetDetail sets the "detail" field.
func (u *BluegreenEventUpsertBulk) SetDetail(v string) *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.SetDetail(v)
	})
}

// UpdateDetail sets the "detail" field to the value that was provided on create.
func (u *BluegreenEventUpsertBulk) UpdateDetail() *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.UpdateDetail()
	})
}

// ClearDetail clears the value of the "detail" field.
func (u *BluegreenEventUpsertBulk) ClearDetail() *BluegreenEventUpsertBulk {
	return u.Update(func(s *BluegreenEventUpsert) {
		s.ClearDetail()
	})
}

// Exec executes the query.
func (u *BluegreenEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BluegreenEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BluegreenEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BluegreenEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
