// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NeoPlayful/maple-gateway/server/ent/bluegreendeployment"
	"github.com/google/uuid"
)

// BluegreenDeploymentCreate is the builder for creating a BluegreenDeployment entity.
type BluegreenDeploymentCreate struct {
	config
	mutation *BluegreenDeploymentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeploymentID sets the "deployment_id" field.
func (bdc *BluegreenDeploymentCreate) SetDeploymentID(u uuid.UUID) *BluegreenDeploymentCreate {
	bdc.mutation.SetDeploymentID(u)
	return bdc
}

// SetBlueVersionID sets the "blue_version_id" field.
func (bdc *BluegreenDeploymentCreate) SetBlueVersionID(u uuid.UUID) *BluegreenDeploymentCreate {
	bdc.mutation.SetBlueVersionID(u)
	return bdc
}

// SetGreenVersionID sets the "green_version_id" field.
func (bdc *BluegreenDeploymentCreate) SetGreenVersionID(u uuid.UUID) *BluegreenDeploymentCreate {
	bdc.mutation.SetGreenVersionID(u)
	return bdc
}

// SetActiveVersionID sets the "active_version_id" field.
func (bdc *BluegreenDeploymentCreate) SetActiveVersionID(u uuid.UUID) *BluegreenDeploymentCreate {
	bdc.mutation.SetActiveVersionID(u)
	return bdc
}

// SetPreviousActiveID sets the "previous_active_id" field.
func (bdc *BluegreenDeploymentCreate) SetPreviousActiveID(u uuid.UUID) *BluegreenDeploymentCreate {
	bdc.mutation.SetPreviousActiveID(u)
	return bdc
}

// SetNillablePreviousActiveID sets the "previous_active_id" field if the given value is not nil.
func (bdc *BluegreenDeploymentCreate) SetNillablePreviousActiveID(u *uuid.UUID) *BluegreenDeploymentCreate {
	if u != nil {
		bdc.SetPreviousActiveID(*u)
	}
	return bdc
}

// SetCreatedAt sets the "created_at" field.
func (bdc *BluegreenDeploymentCreate) SetCreatedAt(t time.Time) *BluegreenDeploymentCreate {
	bdc.mutation.SetCreatedAt(t)
	return bdc
}

// SetUpdatedAt sets the "updated_at" field.
func (bdc *BluegreenDeploymentCreate) SetUpdatedAt(t time.Time) *BluegreenDeploymentCreate {
	bdc.mutation.SetUpdatedAt(t)
	return bdc
}

// SetID sets the "id" field.
func (bdc *BluegreenDeploymentCreate) SetID(u uuid.UUID) *BluegreenDeploymentCreate {
	bdc.mutation.SetID(u)
	return bdc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (bdc *BluegreenDeploymentCreate) SetNillableID(u *uuid.UUID) *BluegreenDeploymentCreate {
	if u != nil {
		bdc.SetID(*u)
	}
	return bdc
}

// Mutation returns the BluegreenDeploymentMutation object of the builder.
func (bdc *BluegreenDeploymentCreate) Mutation() *BluegreenDeploymentMutation {
	return bdc.mutation
}

// Save creates the BluegreenDeployment in the database.
func (bdc *BluegreenDeploymentCreate) Save(ctx context.Context) (*BluegreenDeployment, error) {
	bdc.defaults()
	return withHooks(ctx, bdc.sqlSave, bdc.mutation, bdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bdc *BluegreenDeploymentCreate) SaveX(ctx context.Context) *BluegreenDeployment {
	v, err := bdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bdc *BluegreenDeploymentCreate) Exec(ctx context.Context) error {
	_, err := bdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bdc *BluegreenDeploymentCreate) ExecX(ctx context.Context) {
	if err := bdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bdc *BluegreenDeploymentCreate) defaults() {
	if _, ok := bdc.mutation.ID(); !ok {
		v := bluegreendeployment.DefaultID()
		bdc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bdc *BluegreenDeploymentCreate) check() error {
	if _, ok := bdc.mutation.DeploymentID(); !ok {
		return &ValidationError{Name: "deployment_id", err: errors.New(`ent: missing required field "BluegreenDeployment.deployment_id"`)}
	}
	if _, ok := bdc.mutation.BlueVersionID(); !ok {
		return &ValidationError{Name: "blue_version_id", err: errors.New(`ent: missing required field "BluegreenDeployment.blue_version_id"`)}
	}
	if _, ok := bdc.mutation.GreenVersionID(); !ok {
		return &ValidationError{Name: "green_version_id", err: errors.New(`ent: missing required field "BluegreenDeployment.green_version_id"`)}
	}
	if _, ok := bdc.mutation.ActiveVersionID(); !ok {
		return &ValidationError{Name: "active_version_id", err: errors.New(`ent: missing required field "BluegreenDeployment.active_version_id"`)}
	}
	if _, ok := bdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BluegreenDeployment.created_at"`)}
	}
	if _, ok := bdc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BluegreenDeployment.updated_at"`)}
	}
	return nil
}

func (bdc *BluegreenDeploymentCreate) sqlSave(ctx context.Context) (*BluegreenDeployment, error) {
	if err := bdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	bdc.mutation.id = &_node.ID
	bdc.mutation.done = true
	return _node, nil
}

func (bdc *BluegreenDeploymentCreate) createSpec() (*BluegreenDeployment, *sqlgraph.CreateSpec) {
	var (
		_node = &BluegreenDeployment{config: bdc.config}
		_spec = sqlgraph.NewCreateSpec(bluegreendeployment.Table, sqlgraph.NewFieldSpec(bluegreendeployment.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = bdc.conflict
	if id, ok := bdc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := bdc.mutation.DeploymentID(); ok {
		_spec.SetField(bluegreendeployment.FieldDeploymentID, field.TypeUUID, value)
		_node.DeploymentID = value
	}
	if value, ok := bdc.mutation.BlueVersionID(); ok {
		_spec.SetField(bluegreendeployment.FieldBlueVersionID, field.TypeUUID, value)
		_node.BlueVersionID = value
	}
	if value, ok := bdc.mutation.GreenVersionID(); ok {
		_spec.SetField(bluegreendeployment.FieldGreenVersionID, field.TypeUUID, value)
		_node.GreenVersionID = value
	}
	if value, ok := bdc.mutation.ActiveVersionID(); ok {
		_spec.SetField(bluegreendeployment.FieldActiveVersionID, field.TypeUUID, value)
		_node.ActiveVersionID = value
	}
	if value, ok := bdc.mutation.PreviousActiveID(); ok {
		_spec.SetField(bluegreendeployment.FieldPreviousActiveID, field.TypeUUID, value)
		_node.PreviousActiveID = &value
	}
	if value, ok := bdc.mutation.CreatedAt(); ok {
		_spec.SetField(bluegreendeployment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bdc.mutation.UpdatedAt(); ok {
		_spec.SetField(bluegreendeployment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BluegreenDeployment.Create().
//		SetDeploymentID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BluegreenDeploymentUpsert) {
//			SetDeploymentID(v+v).
//		}).
//		Exec(ctx)
func (bdc *BluegreenDeploymentCreate) OnConflict(opts ...sql.ConflictOption) *BluegreenDeploymentUpsertOne {
	bdc.conflict = opts
	return &BluegreenDeploymentUpsertOne{
		create: bdc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BluegreenDeployment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bdc *BluegreenDeploymentCreate) OnConflictColumns(columns ...string) *BluegreenDeploymentUpsertOne {
	bdc.conflict = append(bdc.conflict, sql.ConflictColumns(columns...))
	return &BluegreenDeploymentUpsertOne{
		create: bdc,
	}
}

type (
	// BluegreenDeploymentUpsertOne is the builder for "upsert"-ing
	//  one BluegreenDeployment node.
	BluegreenDeploymentUpsertOne struct {
		create *BluegreenDeploymentCreate
	}

	// BluegreenDeploymentUpsert is the "OnConflict" setter.
	BluegreenDeploymentUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeploymentID sets the "deployment_id" field.
func (u *BluegreenDeploymentUpsert) SetDeploymentID(v uuid.UUID) *BluegreenDeploymentUpsert {
	u.Set(bluegreendeployment.FieldDeploymentID, v)
	return u
}

// UpdateDeploymentID sets the "deployment_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsert) UpdateDeploymentID() *BluegreenDeploymentUpsert {
	u.SetExcluded(bluegreendeployment.FieldDeploymentID)
	return u
}

// SetBlueVersionID sets the "blue_version_id" field.
func (u *BluegreenDeploymentUpsert) SetBlueVersionID(v uuid.UUID) *BluegreenDeploymentUpsert {
	u.Set(bluegreendeployment.FieldBlueVersionID, v)
	return u
}

// UpdateBlueVersionID sets the "blue_version_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsert) UpdateBlueVersionID() *BluegreenDeploymentUpsert {
	u.SetExcluded(bluegreendeployment.FieldBlueVersionID)
	return u
}

// SetGreenVersionID sets the "green_version_id" field.
func (u *BluegreenDeploymentUpsert) SetGreenVersionID(v uuid.UUID) *BluegreenDeploymentUpsert {
	u.Set(bluegreendeployment.FieldGreenVersionID, v)
	return u
}

// UpdateGreenVersionID sets the "green_version_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsert) UpdateGreenVersionID() *BluegreenDeploymentUpsert {
	u.SetExcluded(bluegreendeployment.FieldGreenVersionID)
	return u
}

// SetActiveVersionID sets the "active_version_id" field.
func (u *BluegreenDeploymentUpsert) SetActiveVersionID(v uuid.UUID) *BluegreenDeploymentUpsert {
	u.Set(bluegreendeployment.FieldActiveVersionID, v)
	return u
}

// UpdateActiveVersionID sets the "active_version_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsert) UpdateActiveVersionID() *BluegreenDeploymentUpsert {
	u.SetExcluded(bluegreendeployment.FieldActiveVersionID)
	return u
}

// SetPreviousActiveID sets the "previous_active_id" field.
func (u *BluegreenDeploymentUpsert) SetPreviousActiveID(v uuid.UUID) *BluegreenDeploymentUpsert {
	u.Set(bluegreendeployment.FieldPreviousActiveID, v)
	return u
}

// UpdatePreviousActiveID sets the "previous_active_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsert) UpdatePreviousActiveID() *BluegreenDeploymentUpsert {
	u.SetExcluded(bluegreendeployment.FieldPreviousActiveID)
	return u
}

// ClearPreviousActiveID clears the value of the "previous_active_id" field.
func (u *BluegreenDeploymentUpsert) ClearPreviousActiveID() *BluegreenDeploymentUpsert {
	u.SetNull(bluegreendeployment.FieldPreviousActiveID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BluegreenDeploymentUpsert) SetUpdatedAt(v time.Time) *BluegreenDeploymentUpsert {
	u.Set(bluegreendeployment.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsert) UpdateUpdatedAt() *BluegreenDeploymentUpsert {
	u.SetExcluded(bluegreendeployment.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.BluegreenDeployment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(bluegreendeployment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BluegreenDeploymentUpsertOne) UpdateNewValues() *BluegreenDeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(bluegreendeployment.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(bluegreendeployment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BluegreenDeployment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BluegreenDeploymentUpsertOne) Ignore() *BluegreenDeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BluegreenDeploymentUpsertOne) DoNothing() *BluegreenDeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BluegreenDeploymentCreate.OnConflict
// documentation for more info.
func (u *BluegreenDeploymentUpsertOne) Update(set func(*BluegreenDeploymentUpsert)) *BluegreenDeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BluegreenDeploymentUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeploymentID sets the "deployment_id" field.
func (u *BluegreenDeploymentUpsertOne) SetDeploymentID(v uuid.UUID) *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.SetDeploymentID(v)
	})
}

// UpdateDeploymentID sets the "deployment_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsertOne) UpdateDeploymentID() *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.UpdateDeploymentID()
	})
}

// SetBlueVersionID sets the "blue_version_id" field.
func (u *BluegreenDeploymentUpsertOne) SetBlueVersionID(v uuid.UUID) *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.SetBlueVersionID(v)
	})
}

// UpdateBlueVersionID sets the "blue_version_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsertOne) UpdateBlueVersionID() *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.UpdateBlueVersionID()
	})
}

// SetGreenVersionID sets the "green_version_id" field.
func (u *BluegreenDeploymentUpsertOne) SetGreenVersionID(v uuid.UUID) *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.SetGreenVersionID(v)
	})
}

// UpdateGreenVersionID sets the "green_version_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsertOne) UpdateGreenVersionID() *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.UpdateGreenVersionID()
	})
}

// SetActiveVersionID sets the "active_version_id" field.
func (u *BluegreenDeploymentUpsertOne) SetActiveVersionID(v uuid.UUID) *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.SetActiveVersionID(v)
	})
}

// UpdateActiveVersionID sets the "active_version_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsertOne) UpdateActiveVersionID() *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.UpdateActiveVersionID()
	})
}

// SetPreviousActiveID sets the "previous_active_id" field.
func (u *BluegreenDeploymentUpsertOne) SetPreviousActiveID(v uuid.UUID) *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.SetPreviousActiveID(v)
	})
}

// UpdatePreviousActiveID sets the "previous_active_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsertOne) UpdatePreviousActiveID() *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.UpdatePreviousActiveID()
	})
}

// ClearPreviousActiveID clears the value of the "previous_active_id" field.
func (u *BluegreenDeploymentUpsertOne) ClearPreviousActiveID() *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.ClearPreviousActiveID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BluegreenDeploymentUpsertOne) SetUpdatedAt(v time.Time) *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsertOne) UpdateUpdatedAt() *BluegreenDeploymentUpsertOne {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BluegreenDeploymentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BluegreenDeploymentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BluegreenDeploymentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BluegreenDeploymentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BluegreenDeploymentUpsertOne.ID is not supported by MySQL driver. Use BluegreenDeploymentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BluegreenDeploymentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BluegreenDeploymentCreateBulk is the builder for creating many BluegreenDeployment entities in bulk.
type BluegreenDeploymentCreateBulk struct {
	config
	err      error
	builders []*BluegreenDeploymentCreate
	conflict []sql.ConflictOption
}

// Save creates the BluegreenDeployment entities in the database.
func (bdcb *BluegreenDeploymentCreateBulk) Save(ctx context.Context) ([]*BluegreenDeployment, error) {
	if bdcb.err != nil {
		return nil, bdcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bdcb.builders))
	nodes := make([]*BluegreenDeployment, len(bdcb.builders))
	mutators := make([]Mutator, len(bdcb.builders))
	for i := range bdcb.builders {
		func(i int, root context.Context) {
			builder := bdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BluegreenDeploymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = bdcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bdcb *BluegreenDeploymentCreateBulk) SaveX(ctx context.Context) []*BluegreenDeployment {
	v, err := bdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bdcb *BluegreenDeploymentCreateBulk) Exec(ctx context.Context) error {
	_, err := bdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bdcb *BluegreenDeploymentCreateBulk) ExecX(ctx context.Context) {
	if err := bdcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BluegreenDeployment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BluegreenDeploymentUpsert) {
//			SetDeploymentID(v+v).
//		}).
//		Exec(ctx)
func (bdcb *BluegreenDeploymentCreateBulk) OnConflict(opts ...sql.ConflictOption) *BluegreenDeploymentUpsertBulk {
	bdcb.conflict = opts
	return &BluegreenDeploymentUpsertBulk{
		create: bdcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BluegreenDeployment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bdcb *BluegreenDeploymentCreateBulk) OnConflictColumns(columns ...string) *BluegreenDeploymentUpsertBulk {
	bdcb.conflict = append(bdcb.conflict, sql.ConflictColumns(columns...))
	return &BluegreenDeploymentUpsertBulk{
		create: bdcb,
	}
}

// BluegreenDeploymentUpsertBulk is the builder for "upsert"-ing
// a bulk of BluegreenDeployment nodes.
type BluegreenDeploymentUpsertBulk struct {
	create *BluegreenDeploymentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BluegreenDeployment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(bluegreendeployment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BluegreenDeploymentUpsertBulk) UpdateNewValues() *BluegreenDeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(bluegreendeployment.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(bluegreendeployment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BluegreenDeployment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BluegreenDeploymentUpsertBulk) Ignore() *BluegreenDeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BluegreenDeploymentUpsertBulk) DoNothing() *BluegreenDeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BluegreenDeploymentCreateBulk.OnConflict
// documentation for more info.
func (u *BluegreenDeploymentUpsertBulk) Update(set func(*BluegreenDeploymentUpsert)) *BluegreenDeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BluegreenDeploymentUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeploymentID sets the "deployment_id" field.
func (u *BluegreenDeploymentUpsertBulk) SetDeploymentID(v uuid.UUID) *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.SetDeploymentID(v)
	})
}

// UpdateDeploymentID sets the "deployment_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsertBulk) UpdateDeploymentID() *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.UpdateDeploymentID()
	})
}

// SetBlueVersionID sets the "blue_version_id" field.
func (u *BluegreenDeploymentUpsertBulk) SetBlueVersionID(v uuid.UUID) *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.SetBlueVersionID(v)
	})
}

// UpdateBlueVersionID sets the "blue_version_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsertBulk) UpdateBlueVersionID() *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.UpdateBlueVersionID()
	})
}

// SetGreenVersionID sets the "green_version_id" field.
func (u *BluegreenDeploymentUpsertBulk) SetGreenVersionID(v uuid.UUID) *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.SetGreenVersionID(v)
	})
}

// UpdateGreenVersionID sets the "green_version_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsertBulk) UpdateGreenVersionID() *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.UpdateGreenVersionID()
	})
}

// SetActiveVersionID sets the "active_version_id" field.
func (u *BluegreenDeploymentUpsertBulk) SetActiveVersionID(v uuid.UUID) *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.SetActiveVersionID(v)
	})
}

// UpdateActiveVersionID sets the "active_version_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsertBulk) UpdateActiveVersionID() *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.UpdateActiveVersionID()
	})
}

// SetPreviousActiveID sets the "previous_active_id" field.
func (u *BluegreenDeploymentUpsertBulk) SetPreviousActiveID(v uuid.UUID) *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.SetPreviousActiveID(v)
	})
}

// UpdatePreviousActiveID sets the "previous_active_id" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsertBulk) UpdatePreviousActiveID() *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.UpdatePreviousActiveID()
	})
}

// ClearPreviousActiveID clears the value of the "previous_active_id" field.
func (u *BluegreenDeploymentUpsertBulk) ClearPreviousActiveID() *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.ClearPreviousActiveID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BluegreenDeploymentUpsertBulk) SetUpdatedAt(v time.Time) *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BluegreenDeploymentUpsertBulk) UpdateUpdatedAt() *BluegreenDeploymentUpsertBulk {
	return u.Update(func(s *BluegreenDeploymentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BluegreenDeploymentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BluegreenDeploymentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BluegreenDeploymentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BluegreenDeploymentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
