// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NeoPlayful/maple-gateway/server/ent/certificateoperation"
	"github.com/NeoPlayful/maple-gateway/server/ent/predicate"
)

// CertificateOperationDelete is the builder for deleting a CertificateOperation entity.
type CertificateOperationDelete struct {
	config
	hooks    []Hook
	mutation *CertificateOperationMutation
}

// Where appends a list predicates to the CertificateOperationDelete builder.
func (cod *CertificateOperationDelete) Where(ps ...predicate.CertificateOperation) *CertificateOperationDelete {
	cod.mutation.Where(ps...)
	return cod
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cod *CertificateOperationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cod.sqlExec, cod.mutation, cod.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cod *CertificateOperationDelete) ExecX(ctx context.Context) int {
	n, err := cod.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cod *CertificateOperationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(certificateoperation.Table, sqlgraph.NewFieldSpec(certificateoperation.FieldID, field.TypeUUID))
	if ps := cod.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cod.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cod.mutation.done = true
	return affected, err
}

// CertificateOperationDeleteOne is the builder for deleting a single CertificateOperation entity.
type CertificateOperationDeleteOne struct {
	cod *CertificateOperationDelete
}

// Where appends a list predicates to the CertificateOperationDelete builder.
func (codo *CertificateOperationDeleteOne) Where(ps ...predicate.CertificateOperation) *CertificateOperationDeleteOne {
	codo.cod.mutation.Where(ps...)
	return codo
}

// Exec executes the deletion query.
func (codo *CertificateOperationDeleteOne) Exec(ctx context.Context) error {
	n, err := codo.cod.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{certificateoperation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (codo *CertificateOperationDeleteOne) ExecX(ctx context.Context) {
	if err := codo.Exec(ctx); err != nil {
		panic(err)
	}
}
