// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NeoPlayful/maple-gateway/server/ent/deployment"
	"github.com/NeoPlayful/maple-gateway/server/ent/deploymentversion"
	"github.com/google/uuid"
)

// DeploymentVersionCreate is the builder for creating a DeploymentVersion entity.
type DeploymentVersionCreate struct {
	config
	mutation *DeploymentVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeploymentID sets the "deployment_id" field.
func (dvc *DeploymentVersionCreate) SetDeploymentID(u uuid.UUID) *DeploymentVersionCreate {
	dvc.mutation.SetDeploymentID(u)
	return dvc
}

// SetVersion sets the "version" field.
func (dvc *DeploymentVersionCreate) SetVersion(s string) *DeploymentVersionCreate {
	dvc.mutation.SetVersion(s)
	return dvc
}

// SetImage sets the "image" field.
func (dvc *DeploymentVersionCreate) SetImage(s string) *DeploymentVersionCreate {
	dvc.mutation.SetImage(s)
	return dvc
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (dvc *DeploymentVersionCreate) SetNillableImage(s *string) *DeploymentVersionCreate {
	if s != nil {
		dvc.SetImage(*s)
	}
	return dvc
}

// SetWeight sets the "weight" field.
func (dvc *DeploymentVersionCreate) SetWeight(i int) *DeploymentVersionCreate {
	dvc.mutation.SetWeight(i)
	return dvc
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (dvc *DeploymentVersionCreate) SetNillableWeight(i *int) *DeploymentVersionCreate {
	if i != nil {
		dvc.SetWeight(*i)
	}
	return dvc
}

// SetStatus sets the "status" field.
func (dvc *DeploymentVersionCreate) SetStatus(s string) *DeploymentVersionCreate {
	dvc.mutation.SetStatus(s)
	return dvc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (dvc *DeploymentVersionCreate) SetNillableStatus(s *string) *DeploymentVersionCreate {
	if s != nil {
		dvc.SetStatus(*s)
	}
	return dvc
}

// SetCreatedAt sets the "created_at" field.
func (dvc *DeploymentVersionCreate) SetCreatedAt(t time.Time) *DeploymentVersionCreate {
	dvc.mutation.SetCreatedAt(t)
	return dvc
}

// SetUpdatedAt sets the "updated_at" field.
func (dvc *DeploymentVersionCreate) SetUpdatedAt(t time.Time) *DeploymentVersionCreate {
	dvc.mutation.SetUpdatedAt(t)
	return dvc
}

// SetID sets the "id" field.
func (dvc *DeploymentVersionCreate) SetID(u uuid.UUID) *DeploymentVersionCreate {
	dvc.mutation.SetID(u)
	return dvc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (dvc *DeploymentVersionCreate) SetNillableID(u *uuid.UUID) *DeploymentVersionCreate {
	if u != nil {
		dvc.SetID(*u)
	}
	return dvc
}

// SetDeployment sets the "deployment" edge to the Deployment entity.
func (dvc *DeploymentVersionCreate) SetDeployment(d *Deployment) *DeploymentVersionCreate {
	return dvc.SetDeploymentID(d.ID)
}

// Mutation returns the DeploymentVersionMutation object of the builder.
func (dvc *DeploymentVersionCreate) Mutation() *DeploymentVersionMutation {
	return dvc.mutation
}

// Save creates the DeploymentVersion in the database.
func (dvc *DeploymentVersionCreate) Save(ctx context.Context) (*DeploymentVersion, error) {
	dvc.defaults()
	return withHooks(ctx, dvc.sqlSave, dvc.mutation, dvc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dvc *DeploymentVersionCreate) SaveX(ctx context.Context) *DeploymentVersion {
	v, err := dvc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dvc *DeploymentVersionCreate) Exec(ctx context.Context) error {
	_, err := dvc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dvc *DeploymentVersionCreate) ExecX(ctx context.Context) {
	if err := dvc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dvc *DeploymentVersionCreate) defaults() {
	if _, ok := dvc.mutation.Image(); !ok {
		v := deploymentversion.DefaultImage
		dvc.mutation.SetImage(v)
	}
	if _, ok := dvc.mutation.Weight(); !ok {
		v := deploymentversion.DefaultWeight
		dvc.mutation.SetWeight(v)
	}
	if _, ok := dvc.mutation.Status(); !ok {
		v := deploymentversion.DefaultStatus
		dvc.mutation.SetStatus(v)
	}
	if _, ok := dvc.mutation.ID(); !ok {
		v := deploymentversion.DefaultID()
		dvc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dvc *DeploymentVersionCreate) check() error {
	if _, ok := dvc.mutation.DeploymentID(); !ok {
		return &ValidationError{Name: "deployment_id", err: errors.New(`ent: missing required field "DeploymentVersion.deployment_id"`)}
	}
	if _, ok := dvc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "DeploymentVersion.version"`)}
	}
	if v, ok := dvc.mutation.Version(); ok {
		if err := deploymentversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "DeploymentVersion.version": %w`, err)}
		}
	}
	if _, ok := dvc.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "DeploymentVersion.weight"`)}
	}
	if _, ok := dvc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DeploymentVersion.status"`)}
	}
	if _, ok := dvc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeploymentVersion.created_at"`)}
	}
	if _, ok := dvc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DeploymentVersion.updated_at"`)}
	}
	if len(dvc.mutation.DeploymentIDs()) == 0 {
		return &ValidationError{Name: "deployment", err: errors.New(`ent: missing required edge "DeploymentVersion.deployment"`)}
	}
	return nil
}

func (dvc *DeploymentVersionCreate) sqlSave(ctx context.Context) (*DeploymentVersion, error) {
	if err := dvc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dvc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dvc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	dvc.mutation.id = &_node.ID
	dvc.mutation.done = true
	return _node, nil
}

func (dvc *DeploymentVersionCreate) createSpec() (*DeploymentVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &DeploymentVersion{config: dvc.config}
		_spec = sqlgraph.NewCreateSpec(deploymentversion.Table, sqlgraph.NewFieldSpec(deploymentversion.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = dvc.conflict
	if id, ok := dvc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := dvc.mutation.Version(); ok {
		_spec.SetField(deploymentversion.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := dvc.mutation.Image(); ok {
		_spec.SetField(deploymentversion.FieldImage, field.TypeString, value)
		_node.Image = value
	}
	if value, ok := dvc.mutation.Weight(); ok {
		_spec.SetField(deploymentversion.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := dvc.mutation.Status(); ok {
		_spec.SetField(deploymentversion.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := dvc.mutation.CreatedAt(); ok {
		_spec.SetField(deploymentversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := dvc.mutation.UpdatedAt(); ok {
		_spec.SetField(deploymentversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := dvc.mutation.DeploymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentversion.DeploymentTable,
			Columns: []string{deploymentversion.DeploymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeploymentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeploymentVersion.Create().
//		SetDeploymentID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeploymentVersionUpsert) {
//			SetDeploymentID(v+v).
//		}).
//		Exec(ctx)
func (dvc *DeploymentVersionCreate) OnConflict(opts ...sql.ConflictOption) *DeploymentVersionUpsertOne {
	dvc.conflict = opts
	return &DeploymentVersionUpsertOne{
		create: dvc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeploymentVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dvc *DeploymentVersionCreate) OnConflictColumns(columns ...string) *DeploymentVersionUpsertOne {
	dvc.conflict = append(dvc.conflict, sql.ConflictColumns(columns...))
	return &DeploymentVersionUpsertOne{
		create: dvc,
	}
}

type (
	// DeploymentVersionUpsertOne is the builder for "upsert"-ing
	//  one DeploymentVersion node.
	DeploymentVersionUpsertOne struct {
		create *DeploymentVersionCreate
	}

	// DeploymentVersionUpsert is the "OnConflict" setter.
	DeploymentVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeploymentID sets the "deployment_id" field.
func (u *DeploymentVersionUpsert) SetDeploymentID(v uuid.UUID) *DeploymentVersionUpsert {
	u.Set(deploymentversion.FieldDeploymentID, v)
	return u
}

// UpdateDeploymentID sets the "deployment_id" field to the value that was provided on create.
func (u *DeploymentVersionUpsert) UpdateDeploymentID() *DeploymentVersionUpsert {
	u.SetExcluded(deploymentversion.FieldDeploymentID)
	return u
}

// SetVersion sets the "version" field.
func (u *DeploymentVersionUpsert) SetVersion(v string) *DeploymentVersionUpsert {
	u.Set(deploymentversion.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *DeploymentVersionUpsert) UpdateVersion() *DeploymentVersionUpsert {
	u.SetExcluded(deploymentversion.FieldVersion)
	return u
}

// SetImage sets the "image" field.
func (u *DeploymentVersionUpsert) SetImage(v string) *DeploymentVersionUpsert {
	u.Set(deploymentversion.FieldImage, v)
	return u
}

// UpdateImage sets the "image" field to the value that was provided on create.
func (u *DeploymentVersionUpsert) UpdateImage() *DeploymentVersionUpsert {
	u.SetExcluded(deploymentversion.FieldImage)
	return u
}

// ClearImage clears the value of the "image" field.
func (u *DeploymentVersionUpsert) ClearImage() *DeploymentVersionUpsert {
	u.SetNull(deploymentversion.FieldImage)
	return u
}

// SetWeight sets the "weight" field.
func (u *DeploymentVersionUpsert) SetWeight(v int) *DeploymentVersionUpsert {
	u.Set(deploymentversion.FieldWeight, v)
	return u
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *DeploymentVersionUpsert) UpdateWeight() *DeploymentVersionUpsert {
	u.SetExcluded(deploymentversion.FieldWeight)
	return u
}

// AddWeight adds v to the "weight" field.
func (u *DeploymentVersionUpsert) AddWeight(v int) *DeploymentVersionUpsert {
	u.Add(deploymentversion.FieldWeight, v)
	return u
}

// SetStatus sets the "status" field.
func (u *DeploymentVersionUpsert) SetStatus(v string) *DeploymentVersionUpsert {
	u.Set(deploymentversion.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DeploymentVersionUpsert) UpdateStatus() *DeploymentVersionUpsert {
	u.SetExcluded(deploymentversion.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeploymentVersionUpsert) SetUpdatedAt(v time.Time) *DeploymentVersionUpsert {
	u.Set(deploymentversion.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeploymentVersionUpsert) UpdateUpdatedAt() *DeploymentVersionUpsert {
	u.SetExcluded(deploymentversion.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DeploymentVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(deploymentversion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeploymentVersionUpsertOne) UpdateNewValues() *DeploymentVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(deploymentversion.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(deploymentversion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeploymentVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeploymentVersionUpsertOne) Ignore() *DeploymentVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeploymentVersionUpsertOne) DoNothing() *DeploymentVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeploymentVersionCreate.OnConflict
// documentation for more info.
func (u *DeploymentVersionUpsertOne) Update(set func(*DeploymentVersionUpsert)) *DeploymentVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeploymentVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeploymentID sets the "deployment_id" field.
func (u *DeploymentVersionUpsertOne) SetDeploymentID(v uuid.UUID) *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.SetDeploymentID(v)
	})
}

// UpdateDeploymentID sets the "deployment_id" field to the value that was provided on create.
func (u *DeploymentVersionUpsertOne) UpdateDeploymentID() *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.UpdateDeploymentID()
	})
}

// SetVersion sets the "version" field.
func (u *DeploymentVersionUpsertOne) SetVersion(v string) *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *DeploymentVersionUpsertOne) UpdateVersion() *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetImage sets the "image" field.
func (u *DeploymentVersionUpsertOne) SetImage(v string) *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.SetImage(v)
	})
}

// UpdateImage sets the "image" field to the value that was provided on create.
func (u *DeploymentVersionUpsertOne) UpdateImage() *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.UpdateImage()
	})
}

// ClearImage clears the value of the "image" field.
func (u *DeploymentVersionUpsertOne) ClearImage() *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.ClearImage()
	})
}

// SetWeight sets the "weight" field.
func (u *DeploymentVersionUpsertOne) SetWeight(v int) *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *DeploymentVersionUpsertOne) AddWeight(v int) *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *DeploymentVersionUpsertOne) UpdateWeight() *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.UpdateWeight()
	})
}

// SetStatus sets the "status" field.
func (u *DeploymentVersionUpsertOne) SetStatus(v string) *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DeploymentVersionUpsertOne) UpdateStatus() *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeploymentVersionUpsertOne) SetUpdatedAt(v time.Time) *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeploymentVersionUpsertOne) UpdateUpdatedAt() *DeploymentVersionUpsertOne {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DeploymentVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeploymentVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeploymentVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeploymentVersionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DeploymentVersionUpsertOne.ID is not supported by MySQL driver. Use DeploymentVersionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeploymentVersionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeploymentVersionCreateBulk is the builder for creating many DeploymentVersion entities in bulk.
type DeploymentVersionCreateBulk struct {
	config
	err      error
	builders []*DeploymentVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the DeploymentVersion entities in the database.
func (dvcb *DeploymentVersionCreateBulk) Save(ctx context.Context) ([]*DeploymentVersion, error) {
	if dvcb.err != nil {
		return nil, dvcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dvcb.builders))
	nodes := make([]*DeploymentVersion, len(dvcb.builders))
	mutators := make([]Mutator, len(dvcb.builders))
	for i := range dvcb.builders {
		func(i int, root context.Context) {
			builder := dvcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeploymentVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dvcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = dvcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dvcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dvcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dvcb *DeploymentVersionCreateBulk) SaveX(ctx context.Context) []*DeploymentVersion {
	v, err := dvcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dvcb *DeploymentVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := dvcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dvcb *DeploymentVersionCreateBulk) ExecX(ctx context.Context) {
	if err := dvcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeploymentVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeploymentVersionUpsert) {
//			SetDeploymentID(v+v).
//		}).
//		Exec(ctx)
func (dvcb *DeploymentVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeploymentVersionUpsertBulk {
	dvcb.conflict = opts
	return &DeploymentVersionUpsertBulk{
		create: dvcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeploymentVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dvcb *DeploymentVersionCreateBulk) OnConflictColumns(columns ...string) *DeploymentVersionUpsertBulk {
	dvcb.conflict = append(dvcb.conflict, sql.ConflictColumns(columns...))
	return &DeploymentVersionUpsertBulk{
		create: dvcb,
	}
}

// DeploymentVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of DeploymentVersion nodes.
type DeploymentVersionUpsertBulk struct {
	create *DeploymentVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DeploymentVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(deploymentversion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeploymentVersionUpsertBulk) UpdateNewValues() *DeploymentVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(deploymentversion.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(deploymentversion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeploymentVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeploymentVersionUpsertBulk) Ignore() *DeploymentVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeploymentVersionUpsertBulk) DoNothing() *DeploymentVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeploymentVersionCreateBulk.OnConflict
// documentation for more info.
func (u *DeploymentVersionUpsertBulk) Update(set func(*DeploymentVersionUpsert)) *DeploymentVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeploymentVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeploymentID sets the "deployment_id" field.
func (u *DeploymentVersionUpsertBulk) SetDeploymentID(v uuid.UUID) *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.SetDeploymentID(v)
	})
}

// UpdateDeploymentID sets the "deployment_id" field to the value that was provided on create.
func (u *DeploymentVersionUpsertBulk) UpdateDeploymentID() *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.UpdateDeploymentID()
	})
}

// SetVersion sets the "version" field.
func (u *DeploymentVersionUpsertBulk) SetVersion(v string) *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *DeploymentVersionUpsertBulk) UpdateVersion() *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetImage sets the "image" field.
func (u *DeploymentVersionUpsertBulk) SetImage(v string) *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.SetImage(v)
	})
}

// UpdateImage sets the "image" field to the value that was provided on create.
func (u *DeploymentVersionUpsertBulk) UpdateImage() *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.UpdateImage()
	})
}

// ClearImage clears the value of the "image" field.
func (u *DeploymentVersionUpsertBulk) ClearImage() *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.ClearImage()
	})
}

// SetWeight sets the "weight" field.
func (u *DeploymentVersionUpsertBulk) SetWeight(v int) *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *DeploymentVersionUpsertBulk) AddWeight(v int) *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *DeploymentVersionUpsertBulk) UpdateWeight() *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.UpdateWeight()
	})
}

// SetStatus sets the "status" field.
func (u *DeploymentVersionUpsertBulk) SetStatus(v string) *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DeploymentVersionUpsertBulk) UpdateStatus() *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeploymentVersionUpsertBulk) SetUpdatedAt(v time.Time) *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeploymentVersionUpsertBulk) UpdateUpdatedAt() *DeploymentVersionUpsertBulk {
	return u.Update(func(s *DeploymentVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DeploymentVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeploymentVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeploymentVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeploymentVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
