// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NeoPlayful/maple-gateway/server/ent/domain"
	"github.com/NeoPlayful/maple-gateway/server/ent/tenant"
	"github.com/google/uuid"
)

// DomainCreate is the builder for creating a Domain entity.
type DomainCreate struct {
	config
	mutation *DomainMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (dc *DomainCreate) SetTenantID(u uuid.UUID) *DomainCreate {
	dc.mutation.SetTenantID(u)
	return dc
}

// SetHostname sets the "hostname" field.
func (dc *DomainCreate) SetHostname(s string) *DomainCreate {
	dc.mutation.SetHostname(s)
	return dc
}

// SetServiceID sets the "service_id" field.
func (dc *DomainCreate) SetServiceID(u uuid.UUID) *DomainCreate {
	dc.mutation.SetServiceID(u)
	return dc
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (dc *DomainCreate) SetNillableServiceID(u *uuid.UUID) *DomainCreate {
	if u != nil {
		dc.SetServiceID(*u)
	}
	return dc
}

// SetStatus sets the "status" field.
func (dc *DomainCreate) SetStatus(s string) *DomainCreate {
	dc.mutation.SetStatus(s)
	return dc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (dc *DomainCreate) SetNillableStatus(s *string) *DomainCreate {
	if s != nil {
		dc.SetStatus(*s)
	}
	return dc
}

// SetVerifiedAt sets the "verified_at" field.
func (dc *DomainCreate) SetVerifiedAt(t time.Time) *DomainCreate {
	dc.mutation.SetVerifiedAt(t)
	return dc
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (dc *DomainCreate) SetNillableVerifiedAt(t *time.Time) *DomainCreate {
	if t != nil {
		dc.SetVerifiedAt(*t)
	}
	return dc
}

// SetCreatedAt sets the "created_at" field.
func (dc *DomainCreate) SetCreatedAt(t time.Time) *DomainCreate {
	dc.mutation.SetCreatedAt(t)
	return dc
}

// SetUpdatedAt sets the "updated_at" field.
func (dc *DomainCreate) SetUpdatedAt(t time.Time) *DomainCreate {
	dc.mutation.SetUpdatedAt(t)
	return dc
}

// SetID sets the "id" field.
func (dc *DomainCreate) SetID(u uuid.UUID) *DomainCreate {
	dc.mutation.SetID(u)
	return dc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (dc *DomainCreate) SetNillableID(u *uuid.UUID) *DomainCreate {
	if u != nil {
		dc.SetID(*u)
	}
	return dc
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (dc *DomainCreate) SetTenant(t *Tenant) *DomainCreate {
	return dc.SetTenantID(t.ID)
}

// Mutation returns the DomainMutation object of the builder.
func (dc *DomainCreate) Mutation() *DomainMutation {
	return dc.mutation
}

// Save creates the Domain in the database.
func (dc *DomainCreate) Save(ctx context.Context) (*Domain, error) {
	dc.defaults()
	return withHooks(ctx, dc.sqlSave, dc.mutation, dc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DomainCreate) SaveX(ctx context.Context) *Domain {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DomainCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DomainCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dc *DomainCreate) defaults() {
	if _, ok := dc.mutation.Status(); !ok {
		v := domain.DefaultStatus
		dc.mutation.SetStatus(v)
	}
	if _, ok := dc.mutation.ID(); !ok {
		v := domain.DefaultID()
		dc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DomainCreate) check() error {
	if _, ok := dc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Domain.tenant_id"`)}
	}
	if _, ok := dc.mutation.Hostname(); !ok {
		return &ValidationError{Name: "hostname", err: errors.New(`ent: missing required field "Domain.hostname"`)}
	}
	if v, ok := dc.mutation.Hostname(); ok {
		if err := domain.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`ent: validator failed for field "Domain.hostname": %w`, err)}
		}
	}
	if _, ok := dc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Domain.status"`)}
	}
	if _, ok := dc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Domain.created_at"`)}
	}
	if _, ok := dc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Domain.updated_at"`)}
	}
	if len(dc.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Domain.tenant"`)}
	}
	return nil
}

func (dc *DomainCreate) sqlSave(ctx context.Context) (*Domain, error) {
	if err := dc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	dc.mutation.id = &_node.ID
	dc.mutation.done = true
	return _node, nil
}

func (dc *DomainCreate) createSpec() (*Domain, *sqlgraph.CreateSpec) {
	var (
		_node = &Domain{config: dc.config}
		_spec = sqlgraph.NewCreateSpec(domain.Table, sqlgraph.NewFieldSpec(domain.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = dc.conflict
	if id, ok := dc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := dc.mutation.Hostname(); ok {
		_spec.SetField(domain.FieldHostname, field.TypeString, value)
		_node.Hostname = value
	}
	if value, ok := dc.mutation.ServiceID(); ok {
		_spec.SetField(domain.FieldServiceID, field.TypeUUID, value)
		_node.ServiceID = &value
	}
	if value, ok := dc.mutation.Status(); ok {
		_spec.SetField(domain.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := dc.mutation.VerifiedAt(); ok {
		_spec.SetField(domain.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if value, ok := dc.mutation.CreatedAt(); ok {
		_spec.SetField(domain.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := dc.mutation.UpdatedAt(); ok {
		_spec.SetField(domain.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := dc.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domain.TenantTable,
			Columns: []string{domain.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Domain.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DomainUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (dc *DomainCreate) OnConflict(opts ...sql.ConflictOption) *DomainUpsertOne {
	dc.conflict = opts
	return &DomainUpsertOne{
		create: dc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Domain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dc *DomainCreate) OnConflictColumns(columns ...string) *DomainUpsertOne {
	dc.conflict = append(dc.conflict, sql.ConflictColumns(columns...))
	return &DomainUpsertOne{
		create: dc,
	}
}

type (
	// DomainUpsertOne is the builder for "upsert"-ing
	//  one Domain node.
	DomainUpsertOne struct {
		create *DomainCreate
	}

	// DomainUpsert is the "OnConflict" setter.
	DomainUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *DomainUpsert) SetTenantID(v uuid.UUID) *DomainUpsert {
	u.Set(domain.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *DomainUpsert) UpdateTenantID() *DomainUpsert {
	u.SetExcluded(domain.FieldTenantID)
	return u
}

// SetHostname sets the "hostname" field.
func (u *DomainUpsert) SetHostname(v string) *DomainUpsert {
	u.Set(domain.FieldHostname, v)
	return u
}

// UpdateHostname sets the "hostname" field to the value that was provided on create.
func (u *DomainUpsert) UpdateHostname() *DomainUpsert {
	u.SetExcluded(domain.FieldHostname)
	return u
}

// SetServiceID sets the "service_id" field.
func (u *DomainUpsert) SetServiceID(v uuid.UUID) *DomainUpsert {
	u.Set(domain.FieldServiceID, v)
	return u
}

// UpdateServiceID sets the "service_id" field to the value that was provided on create.
func (u *DomainUpsert) UpdateServiceID() *DomainUpsert {
	u.SetExcluded(domain.FieldServiceID)
	return u
}

// ClearServiceID clears the value of the "service_id" field.
func (u *DomainUpsert) ClearServiceID() *DomainUpsert {
	u.SetNull(domain.FieldServiceID)
	return u
}

// SetStatus sets the "status" field.
func (u *DomainUpsert) SetStatus(v string) *DomainUpsert {
	u.Set(domain.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DomainUpsert) UpdateStatus() *DomainUpsert {
	u.SetExcluded(domain.FieldStatus)
	return u
}

// SetVerifiedAt sets the "verified_at" field.
func (u *DomainUpsert) SetVerifiedAt(v time.Time) *DomainUpsert {
	u.Set(domain.FieldVerifiedAt, v)
	return u
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *DomainUpsert) UpdateVerifiedAt() *DomainUpsert {
	u.SetExcluded(domain.FieldVerifiedAt)
	return u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *DomainUpsert) ClearVerifiedAt() *DomainUpsert {
	u.SetNull(domain.FieldVerifiedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DomainUpsert) SetUpdatedAt(v time.Time) *DomainUpsert {
	u.Set(domain.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DomainUpsert) UpdateUpdatedAt() *DomainUpsert {
	u.SetExcluded(domain.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Domain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(domain.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DomainUpsertOne) UpdateNewValues() *DomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(domain.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(domain.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Domain.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DomainUpsertOne) Ignore() *DomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DomainUpsertOne) DoNothing() *DomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DomainCreate.OnConflict
// documentation for more info.
func (u *DomainUpsertOne) Update(set func(*DomainUpsert)) *DomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DomainUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *DomainUpsertOne) SetTenantID(v uuid.UUID) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *DomainUpsertOne) UpdateTenantID() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateTenantID()
	})
}

// SetHostname sets the "hostname" field.
func (u *DomainUpsertOne) SetHostname(v string) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.SetHostname(v)
	})
}

// UpdateHostname sets the "hostname" field to the value that was provided on create.
func (u *DomainUpsertOne) UpdateHostname() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateHostname()
	})
}

// SetServiceID sets the "service_id" field.
func (u *DomainUpsertOne) SetServiceID(v uuid.UUID) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.SetServiceID(v)
	})
}

// UpdateServiceID sets the "service_id" field to the value that was provided on create.
func (u *DomainUpsertOne) UpdateServiceID() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateServiceID()
	})
}

// ClearServiceID clears the value of the "service_id" field.
func (u *DomainUpsertOne) ClearServiceID() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.ClearServiceID()
	})
}

// SetStatus sets the "status" field.
func (u *DomainUpsertOne) SetStatus(v string) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DomainUpsertOne) UpdateStatus() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateStatus()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *DomainUpsertOne) SetVerifiedAt(v time.Time) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *DomainUpsertOne) UpdateVerifiedAt() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *DomainUpsertOne) ClearVerifiedAt() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.ClearVerifiedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DomainUpsertOne) SetUpdatedAt(v time.Time) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DomainUpsertOne) UpdateUpdatedAt() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DomainUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DomainCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DomainUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DomainUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DomainUpsertOne.ID is not supported by MySQL driver. Use DomainUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DomainUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DomainCreateBulk is the builder for creating many Domain entities in bulk.
type DomainCreateBulk struct {
	config
	err      error
	builders []*DomainCreate
	conflict []sql.ConflictOption
}

// Save creates the Domain entities in the database.
func (dcb *DomainCreateBulk) Save(ctx context.Context) ([]*Domain, error) {
	if dcb.err != nil {
		return nil, dcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Domain, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DomainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = dcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DomainCreateBulk) SaveX(ctx context.Context) []*Domain {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DomainCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DomainCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Domain.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DomainUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (dcb *DomainCreateBulk) OnConflict(opts ...sql.ConflictOption) *DomainUpsertBulk {
	dcb.conflict = opts
	return &DomainUpsertBulk{
		create: dcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Domain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dcb *DomainCreateBulk) OnConflictColumns(columns ...string) *DomainUpsertBulk {
	dcb.conflict = append(dcb.conflict, sql.ConflictColumns(columns...))
	return &DomainUpsertBulk{
		create: dcb,
	}
}

// DomainUpsertBulk is the builder for "upsert"-ing
// a bulk of Domain nodes.
type DomainUpsertBulk struct {
	create *DomainCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Domain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(domain.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DomainUpsertBulk) UpdateNewValues() *DomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(domain.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(domain.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Domain.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DomainUpsertBulk) Ignore() *DomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DomainUpsertBulk) DoNothing() *DomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DomainCreateBulk.OnConflict
// documentation for more info.
func (u *DomainUpsertBulk) Update(set func(*DomainUpsert)) *DomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DomainUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *DomainUpsertBulk) SetTenantID(v uuid.UUID) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *DomainUpsertBulk) UpdateTenantID() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateTenantID()
	})
}

// SetHostname sets the "hostname" field.
func (u *DomainUpsertBulk) SetHostname(v string) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.SetHostname(v)
	})
}

// UpdateHostname sets the "hostname" field to the value that was provided on create.
func (u *DomainUpsertBulk) UpdateHostname() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateHostname()
	})
}

// SetServiceID sets the "service_id" field.
func (u *DomainUpsertBulk) SetServiceID(v uuid.UUID) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.SetServiceID(v)
	})
}

// UpdateServiceID sets the "service_id" field to the value that was provided on create.
func (u *DomainUpsertBulk) UpdateServiceID() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateServiceID()
	})
}

// ClearServiceID clears the value of the "service_id" field.
func (u *DomainUpsertBulk) ClearServiceID() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.ClearServiceID()
	})
}

// SetStatus sets the "status" field.
func (u *DomainUpsertBulk) SetStatus(v string) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DomainUpsertBulk) UpdateStatus() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateStatus()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *DomainUpsertBulk) SetVerifiedAt(v time.Time) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *DomainUpsertBulk) UpdateVerifiedAt() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *DomainUpsertBulk) ClearVerifiedAt() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.ClearVerifiedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DomainUpsertBulk) SetUpdatedAt(v time.Time) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DomainUpsertBulk) UpdateUpdatedAt() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DomainUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DomainCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DomainCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DomainUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
