// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NeoPlayful/maple-gateway/server/ent/domain"
	"github.com/NeoPlayful/maple-gateway/server/ent/predicate"
	"github.com/NeoPlayful/maple-gateway/server/ent/tenant"
	"github.com/google/uuid"
)

// DomainUpdate is the builder for updating Domain entities.
type DomainUpdate struct {
	config
	hooks    []Hook
	mutation *DomainMutation
}

// Where appends a list predicates to the DomainUpdate builder.
func (du *DomainUpdate) Where(ps ...predicate.Domain) *DomainUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetTenantID sets the "tenant_id" field.
func (du *DomainUpdate) SetTenantID(u uuid.UUID) *DomainUpdate {
	du.mutation.SetTenantID(u)
	return du
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (du *DomainUpdate) SetNillableTenantID(u *uuid.UUID) *DomainUpdate {
	if u != nil {
		du.SetTenantID(*u)
	}
	return du
}

// SetHostname sets the "hostname" field.
func (du *DomainUpdate) SetHostname(s string) *DomainUpdate {
	du.mutation.SetHostname(s)
	return du
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (du *DomainUpdate) SetNillableHostname(s *string) *DomainUpdate {
	if s != nil {
		du.SetHostname(*s)
	}
	return du
}

// SetServiceID sets the "service_id" field.
func (du *DomainUpdate) SetServiceID(u uuid.UUID) *DomainUpdate {
	du.mutation.SetServiceID(u)
	return du
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (du *DomainUpdate) SetNillableServiceID(u *uuid.UUID) *DomainUpdate {
	if u != nil {
		du.SetServiceID(*u)
	}
	return du
}

// ClearServiceID clears the value of the "service_id" field.
func (du *DomainUpdate) ClearServiceID() *DomainUpdate {
	du.mutation.ClearServiceID()
	return du
}

// SetStatus sets the "status" field.
func (du *DomainUpdate) SetStatus(s string) *DomainUpdate {
	du.mutation.SetStatus(s)
	return du
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (du *DomainUpdate) SetNillableStatus(s *string) *DomainUpdate {
	if s != nil {
		du.SetStatus(*s)
	}
	return du
}

// SetVerifiedAt sets the "verified_at" field.
func (du *DomainUpdate) SetVerifiedAt(t time.Time) *DomainUpdate {
	du.mutation.SetVerifiedAt(t)
	return du
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (du *DomainUpdate) SetNillableVerifiedAt(t *time.Time) *DomainUpdate {
	if t != nil {
		du.SetVerifiedAt(*t)
	}
	return du
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (du *DomainUpdate) ClearVerifiedAt() *DomainUpdate {
	du.mutation.ClearVerifiedAt()
	return du
}

// SetUpdatedAt sets the "updated_at" field.
func (du *DomainUpdate) SetUpdatedAt(t time.Time) *DomainUpdate {
	du.mutation.SetUpdatedAt(t)
	return du
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (du *DomainUpdate) SetNillableUpdatedAt(t *time.Time) *DomainUpdate {
	if t != nil {
		du.SetUpdatedAt(*t)
	}
	return du
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (du *DomainUpdate) SetTenant(t *Tenant) *DomainUpdate {
	return du.SetTenantID(t.ID)
}

// Mutation returns the DomainMutation object of the builder.
func (du *DomainUpdate) Mutation() *DomainMutation {
	return du.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (du *DomainUpdate) ClearTenant() *DomainUpdate {
	du.mutation.ClearTenant()
	return du
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DomainUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DomainUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DomainUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DomainUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DomainUpdate) check() error {
	if v, ok := du.mutation.Hostname(); ok {
		if err := domain.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`ent: validator failed for field "Domain.hostname": %w`, err)}
		}
	}
	if du.mutation.TenantCleared() && len(du.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Domain.tenant"`)
	}
	return nil
}

func (du *DomainUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := du.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(domain.Table, domain.Columns, sqlgraph.NewFieldSpec(domain.FieldID, field.TypeUUID))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Hostname(); ok {
		_spec.SetField(domain.FieldHostname, field.TypeString, value)
	}
	if value, ok := du.mutation.ServiceID(); ok {
		_spec.SetField(domain.FieldServiceID, field.TypeUUID, value)
	}
	if du.mutation.ServiceIDCleared() {
		_spec.ClearField(domain.FieldServiceID, field.TypeUUID)
	}
	if value, ok := du.mutation.Status(); ok {
		_spec.SetField(domain.FieldStatus, field.TypeString, value)
	}
	if value, ok := du.mutation.VerifiedAt(); ok {
		_spec.SetField(domain.FieldVerifiedAt, field.TypeTime, value)
	}
	if du.mutation.VerifiedAtCleared() {
		_spec.ClearField(domain.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := du.mutation.UpdatedAt(); ok {
		_spec.SetField(domain.FieldUpdatedAt, field.TypeTime, value)
	}
	if du.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domain.TenantTable,
			Columns: []string{domain.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domain.TenantTable,
			Columns: []string{domain.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{domain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DomainUpdateOne is the builder for updating a single Domain entity.
type DomainUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DomainMutation
}

// SetTenantID sets the "tenant_id" field.
func (duo *DomainUpdateOne) SetTenantID(u uuid.UUID) *DomainUpdateOne {
	duo.mutation.SetTenantID(u)
	return duo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (duo *DomainUpdateOne) SetNillableTenantID(u *uuid.UUID) *DomainUpdateOne {
	if u != nil {
		duo.SetTenantID(*u)
	}
	return duo
}

// SetHostname sets the "hostname" field.
func (duo *DomainUpdateOne) SetHostname(s string) *DomainUpdateOne {
	duo.mutation.SetHostname(s)
	return duo
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (duo *DomainUpdateOne) SetNillableHostname(s *string) *DomainUpdateOne {
	if s != nil {
		duo.SetHostname(*s)
	}
	return duo
}

// SetServiceID sets the "service_id" field.
func (duo *DomainUpdateOne) SetServiceID(u uuid.UUID) *DomainUpdateOne {
	duo.mutation.SetServiceID(u)
	return duo
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (duo *DomainUpdateOne) SetNillableServiceID(u *uuid.UUID) *DomainUpdateOne {
	if u != nil {
		duo.SetServiceID(*u)
	}
	return duo
}

// ClearServiceID clears the value of the "service_id" field.
func (duo *DomainUpdateOne) ClearServiceID() *DomainUpdateOne {
	duo.mutation.ClearServiceID()
	return duo
}

// SetStatus sets the "status" field.
func (duo *DomainUpdateOne) SetStatus(s string) *DomainUpdateOne {
	duo.mutation.SetStatus(s)
	return duo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (duo *DomainUpdateOne) SetNillableStatus(s *string) *DomainUpdateOne {
	if s != nil {
		duo.SetStatus(*s)
	}
	return duo
}

// SetVerifiedAt sets the "verified_at" field.
func (duo *DomainUpdateOne) SetVerifiedAt(t time.Time) *DomainUpdateOne {
	duo.mutation.SetVerifiedAt(t)
	return duo
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (duo *DomainUpdateOne) SetNillableVerifiedAt(t *time.Time) *DomainUpdateOne {
	if t != nil {
		duo.SetVerifiedAt(*t)
	}
	return duo
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (duo *DomainUpdateOne) ClearVerifiedAt() *DomainUpdateOne {
	duo.mutation.ClearVerifiedAt()
	return duo
}

// SetUpdatedAt sets the "updated_at" field.
func (duo *DomainUpdateOne) SetUpdatedAt(t time.Time) *DomainUpdateOne {
	duo.mutation.SetUpdatedAt(t)
	return duo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (duo *DomainUpdateOne) SetNillableUpdatedAt(t *time.Time) *DomainUpdateOne {
	if t != nil {
		duo.SetUpdatedAt(*t)
	}
	return duo
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (duo *DomainUpdateOne) SetTenant(t *Tenant) *DomainUpdateOne {
	return duo.SetTenantID(t.ID)
}

// Mutation returns the DomainMutation object of the builder.
func (duo *DomainUpdateOne) Mutation() *DomainMutation {
	return duo.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (duo *DomainUpdateOne) ClearTenant() *DomainUpdateOne {
	duo.mutation.ClearTenant()
	return duo
}

// Where appends a list predicates to the DomainUpdate builder.
func (duo *DomainUpdateOne) Where(ps ...predicate.Domain) *DomainUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DomainUpdateOne) Select(field string, fields ...string) *DomainUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Domain entity.
func (duo *DomainUpdateOne) Save(ctx context.Context) (*Domain, error) {
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DomainUpdateOne) SaveX(ctx context.Context) *Domain {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DomainUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DomainUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DomainUpdateOne) check() error {
	if v, ok := duo.mutation.Hostname(); ok {
		if err := domain.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`ent: validator failed for field "Domain.hostname": %w`, err)}
		}
	}
	if duo.mutation.TenantCleared() && len(duo.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Domain.tenant"`)
	}
	return nil
}

func (duo *DomainUpdateOne) sqlSave(ctx context.Context) (_node *Domain, err error) {
	if err := duo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(domain.Table, domain.Columns, sqlgraph.NewFieldSpec(domain.FieldID, field.TypeUUID))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Domain.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, domain.FieldID)
		for _, f := range fields {
			if !domain.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != domain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Hostname(); ok {
		_spec.SetField(domain.FieldHostname, field.TypeString, value)
	}
	if value, ok := duo.mutation.ServiceID(); ok {
		_spec.SetField(domain.FieldServiceID, field.TypeUUID, value)
	}
	if duo.mutation.ServiceIDCleared() {
		_spec.ClearField(domain.FieldServiceID, field.TypeUUID)
	}
	if value, ok := duo.mutation.Status(); ok {
		_spec.SetField(domain.FieldStatus, field.TypeString, value)
	}
	if value, ok := duo.mutation.VerifiedAt(); ok {
		_spec.SetField(domain.FieldVerifiedAt, field.TypeTime, value)
	}
	if duo.mutation.VerifiedAtCleared() {
		_spec.ClearField(domain.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := duo.mutation.UpdatedAt(); ok {
		_spec.SetField(domain.FieldUpdatedAt, field.TypeTime, value)
	}
	if duo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domain.TenantTable,
			Columns: []string{domain.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domain.TenantTable,
			Columns: []string{domain.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Domain{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{domain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
