// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NeoPlayful/maple-gateway/server/ent/ratelimit"
	"github.com/google/uuid"
)

// RateLimitCreate is the builder for creating a RateLimit entity.
type RateLimitCreate struct {
	config
	mutation *RateLimitMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetScope sets the "scope" field.
func (rlc *RateLimitCreate) SetScope(s string) *RateLimitCreate {
	rlc.mutation.SetScope(s)
	return rlc
}

// SetTenantID sets the "tenant_id" field.
func (rlc *RateLimitCreate) SetTenantID(u uuid.UUID) *RateLimitCreate {
	rlc.mutation.SetTenantID(u)
	return rlc
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (rlc *RateLimitCreate) SetNillableTenantID(u *uuid.UUID) *RateLimitCreate {
	if u != nil {
		rlc.SetTenantID(*u)
	}
	return rlc
}

// SetDomainID sets the "domain_id" field.
func (rlc *RateLimitCreate) SetDomainID(u uuid.UUID) *RateLimitCreate {
	rlc.mutation.SetDomainID(u)
	return rlc
}

// SetNillableDomainID sets the "domain_id" field if the given value is not nil.
func (rlc *RateLimitCreate) SetNillableDomainID(u *uuid.UUID) *RateLimitCreate {
	if u != nil {
		rlc.SetDomainID(*u)
	}
	return rlc
}

// SetServiceID sets the "service_id" field.
func (rlc *RateLimitCreate) SetServiceID(u uuid.UUID) *RateLimitCreate {
	rlc.mutation.SetServiceID(u)
	return rlc
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (rlc *RateLimitCreate) SetNillableServiceID(u *uuid.UUID) *RateLimitCreate {
	if u != nil {
		rlc.SetServiceID(*u)
	}
	return rlc
}

// SetName sets the "name" field.
func (rlc *RateLimitCreate) SetName(s string) *RateLimitCreate {
	rlc.mutation.SetName(s)
	return rlc
}

// SetLimit sets the "limit" field.
func (rlc *RateLimitCreate) SetLimit(i int) *RateLimitCreate {
	rlc.mutation.SetLimit(i)
	return rlc
}

// SetWindowSeconds sets the "window_seconds" field.
func (rlc *RateLimitCreate) SetWindowSeconds(i int) *RateLimitCreate {
	rlc.mutation.SetWindowSeconds(i)
	return rlc
}

// SetNillableWindowSeconds sets the "window_seconds" field if the given value is not nil.
func (rlc *RateLimitCreate) SetNillableWindowSeconds(i *int) *RateLimitCreate {
	if i != nil {
		rlc.SetWindowSeconds(*i)
	}
	return rlc
}

// SetBurst sets the "burst" field.
func (rlc *RateLimitCreate) SetBurst(i int) *RateLimitCreate {
	rlc.mutation.SetBurst(i)
	return rlc
}

// SetNillableBurst sets the "burst" field if the given value is not nil.
func (rlc *RateLimitCreate) SetNillableBurst(i *int) *RateLimitCreate {
	if i != nil {
		rlc.SetBurst(*i)
	}
	return rlc
}

// SetResponseCode sets the "response_code" field.
func (rlc *RateLimitCreate) SetResponseCode(i int) *RateLimitCreate {
	rlc.mutation.SetResponseCode(i)
	return rlc
}

// SetNillableResponseCode sets the "response_code" field if the given value is not nil.
func (rlc *RateLimitCreate) SetNillableResponseCode(i *int) *RateLimitCreate {
	if i != nil {
		rlc.SetResponseCode(*i)
	}
	return rlc
}

// SetStatus sets the "status" field.
func (rlc *RateLimitCreate) SetStatus(s string) *RateLimitCreate {
	rlc.mutation.SetStatus(s)
	return rlc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rlc *RateLimitCreate) SetNillableStatus(s *string) *RateLimitCreate {
	if s != nil {
		rlc.SetStatus(*s)
	}
	return rlc
}

// SetCreatedAt sets the "created_at" field.
func (rlc *RateLimitCreate) SetCreatedAt(t time.Time) *RateLimitCreate {
	rlc.mutation.SetCreatedAt(t)
	return rlc
}

// SetUpdatedAt sets the "updated_at" field.
func (rlc *RateLimitCreate) SetUpdatedAt(t time.Time) *RateLimitCreate {
	rlc.mutation.SetUpdatedAt(t)
	return rlc
}

// SetID sets the "id" field.
func (rlc *RateLimitCreate) SetID(u uuid.UUID) *RateLimitCreate {
	rlc.mutation.SetID(u)
	return rlc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (rlc *RateLimitCreate) SetNillableID(u *uuid.UUID) *RateLimitCreate {
	if u != nil {
		rlc.SetID(*u)
	}
	return rlc
}

// Mutation returns the RateLimitMutation object of the builder.
func (rlc *RateLimitCreate) Mutation() *RateLimitMutation {
	return rlc.mutation
}

// Save creates the RateLimit in the database.
func (rlc *RateLimitCreate) Save(ctx context.Context) (*RateLimit, error) {
	rlc.defaults()
	return withHooks(ctx, rlc.sqlSave, rlc.mutation, rlc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rlc *RateLimitCreate) SaveX(ctx context.Context) *RateLimit {
	v, err := rlc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rlc *RateLimitCreate) Exec(ctx context.Context) error {
	_, err := rlc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rlc *RateLimitCreate) ExecX(ctx context.Context) {
	if err := rlc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rlc *RateLimitCreate) defaults() {
	if _, ok := rlc.mutation.WindowSeconds(); !ok {
		v := ratelimit.DefaultWindowSeconds
		rlc.mutation.SetWindowSeconds(v)
	}
	if _, ok := rlc.mutation.Burst(); !ok {
		v := ratelimit.DefaultBurst
		rlc.mutation.SetBurst(v)
	}
	if _, ok := rlc.mutation.ResponseCode(); !ok {
		v := ratelimit.DefaultResponseCode
		rlc.mutation.SetResponseCode(v)
	}
	if _, ok := rlc.mutation.Status(); !ok {
		v := ratelimit.DefaultStatus
		rlc.mutation.SetStatus(v)
	}
	if _, ok := rlc.mutation.ID(); !ok {
		v := ratelimit.DefaultID()
		rlc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rlc *RateLimitCreate) check() error {
	if _, ok := rlc.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "RateLimit.scope"`)}
	}
	if v, ok := rlc.mutation.Scope(); ok {
		if err := ratelimit.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "RateLimit.scope": %w`, err)}
		}
	}
	if _, ok := rlc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RateLimit.name"`)}
	}
	if v, ok := rlc.mutation.Name(); ok {
		if err := ratelimit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RateLimit.name": %w`, err)}
		}
	}
	if _, ok := rlc.mutation.Limit(); !ok {
		return &ValidationError{Name: "limit", err: errors.New(`ent: missing required field "RateLimit.limit"`)}
	}
	if _, ok := rlc.mutation.WindowSeconds(); !ok {
		return &ValidationError{Name: "window_seconds", err: errors.New(`ent: missing required field "RateLimit.window_seconds"`)}
	}
	if _, ok := rlc.mutation.ResponseCode(); !ok {
		return &ValidationError{Name: "response_code", err: errors.New(`ent: missing required field "RateLimit.response_code"`)}
	}
	if _, ok := rlc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RateLimit.status"`)}
	}
	if _, ok := rlc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RateLimit.created_at"`)}
	}
	if _, ok := rlc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RateLimit.updated_at"`)}
	}
	return nil
}

func (rlc *RateLimitCreate) sqlSave(ctx context.Context) (*RateLimit, error) {
	if err := rlc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rlc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rlc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	rlc.mutation.id = &_node.ID
	rlc.mutation.done = true
	return _node, nil
}

func (rlc *RateLimitCreate) createSpec() (*RateLimit, *sqlgraph.CreateSpec) {
	var (
		_node = &RateLimit{config: rlc.config}
		_spec = sqlgraph.NewCreateSpec(ratelimit.Table, sqlgraph.NewFieldSpec(ratelimit.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = rlc.conflict
	if id, ok := rlc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := rlc.mutation.Scope(); ok {
		_spec.SetField(ratelimit.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := rlc.mutation.TenantID(); ok {
		_spec.SetField(ratelimit.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = &value
	}
	if value, ok := rlc.mutation.DomainID(); ok {
		_spec.SetField(ratelimit.FieldDomainID, field.TypeUUID, value)
		_node.DomainID = &value
	}
	if value, ok := rlc.mutation.ServiceID(); ok {
		_spec.SetField(ratelimit.FieldServiceID, field.TypeUUID, value)
		_node.ServiceID = &value
	}
	if value, ok := rlc.mutation.Name(); ok {
		_spec.SetField(ratelimit.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := rlc.mutation.Limit(); ok {
		_spec.SetField(ratelimit.FieldLimit, field.TypeInt, value)
		_node.Limit = value
	}
	if value, ok := rlc.mutation.WindowSeconds(); ok {
		_spec.SetField(ratelimit.FieldWindowSeconds, field.TypeInt, value)
		_node.WindowSeconds = value
	}
	if value, ok := rlc.mutation.Burst(); ok {
		_spec.SetField(ratelimit.FieldBurst, field.TypeInt, value)
		_node.Burst = value
	}
	if value, ok := rlc.mutation.ResponseCode(); ok {
		_spec.SetField(ratelimit.FieldResponseCode, field.TypeInt, value)
		_node.ResponseCode = value
	}
	if value, ok := rlc.mutation.Status(); ok {
		_spec.SetField(ratelimit.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := rlc.mutation.CreatedAt(); ok {
		_spec.SetField(ratelimit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rlc.mutation.UpdatedAt(); ok {
		_spec.SetField(ratelimit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RateLimit.Create().
//		SetScope(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RateLimitUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (rlc *RateLimitCreate) OnConflict(opts ...sql.ConflictOption) *RateLimitUpsertOne {
	rlc.conflict = opts
	return &RateLimitUpsertOne{
		create: rlc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RateLimit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rlc *RateLimitCreate) OnConflictColumns(columns ...string) *RateLimitUpsertOne {
	rlc.conflict = append(rlc.conflict, sql.ConflictColumns(columns...))
	return &RateLimitUpsertOne{
		create: rlc,
	}
}

type (
	// RateLimitUpsertOne is the builder for "upsert"-ing
	//  one RateLimit node.
	RateLimitUpsertOne struct {
		create *RateLimitCreate
	}

	// RateLimitUpsert is the "OnConflict" setter.
	RateLimitUpsert struct {
		*sql.UpdateSet
	}
)

// SetScope sets the "scope" field.
func (u *RateLimitUpsert) SetScope(v string) *RateLimitUpsert {
	u.Set(ratelimit.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *RateLimitUpsert) UpdateScope() *RateLimitUpsert {
	u.SetExcluded(ratelimit.FieldScope)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *RateLimitUpsert) SetTenantID(v uuid.UUID) *RateLimitUpsert {
	u.Set(ratelimit.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *RateLimitUpsert) UpdateTenantID() *RateLimitUpsert {
	u.SetExcluded(ratelimit.FieldTenantID)
	return u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *RateLimitUpsert) ClearTenantID() *RateLimitUpsert {
	u.SetNull(ratelimit.FieldTenantID)
	return u
}

// SetDomainID sets the "domain_id" field.
func (u *RateLimitUpsert) SetDomainID(v uuid.UUID) *RateLimitUpsert {
	u.Set(ratelimit.FieldDomainID, v)
	return u
}

// UpdateDomainID sets the "domain_id" field to the value that was provided on create.
func (u *RateLimitUpsert) UpdateDomainID() *RateLimitUpsert {
	u.SetExcluded(ratelimit.FieldDomainID)
	return u
}

// ClearDomainID clears the value of the "domain_id" field.
func (u *RateLimitUpsert) ClearDomainID() *RateLimitUpsert {
	u.SetNull(ratelimit.FieldDomainID)
	return u
}

// SetServiceID sets the "service_id" field.
func (u *RateLimitUpsert) SetServiceID(v uuid.UUID) *RateLimitUpsert {
	u.Set(ratelimit.FieldServiceID, v)
	return u
}

// UpdateServiceID sets the "service_id" field to the value that was provided on create.
func (u *RateLimitUpsert) UpdateServiceID() *RateLimitUpsert {
	u.SetExcluded(ratelimit.FieldServiceID)
	return u
}

// ClearServiceID clears the value of the "service_id" field.
func (u *RateLimitUpsert) ClearServiceID() *RateLimitUpsert {
	u.SetNull(ratelimit.FieldServiceID)
	return u
}

// SetName sets the "name" field.
func (u *RateLimitUpsert) SetName(v string) *RateLimitUpsert {
	u.Set(ratelimit.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RateLimitUpsert) UpdateName() *RateLimitUpsert {
	u.SetExcluded(ratelimit.FieldName)
	return u
}

// SetLimit sets the "limit" field.
func (u *RateLimitUpsert) SetLimit(v int) *RateLimitUpsert {
	u.Set(ratelimit.FieldLimit, v)
	return u
}

// UpdateLimit sets the "limit" field to the value that was provided on create.
func (u *RateLimitUpsert) UpdateLimit() *RateLimitUpsert {
	u.SetExcluded(ratelimit.FieldLimit)
	return u
}

// AddLimit adds v to the "limit" field.
func (u *RateLimitUpsert) AddLimit(v int) *RateLimitUpsert {
	u.Add(ratelimit.FieldLimit, v)
	return u
}

// SetWindowSeconds sets the "window_seconds" field.
func (u *RateLimitUpsert) SetWindowSeconds(v int) *RateLimitUpsert {
	u.Set(ratelimit.FieldWindowSeconds, v)
	return u
}

// UpdateWindowSeconds sets the "window_seconds" field to the value that was provided on create.
func (u *RateLimitUpsert) UpdateWindowSeconds() *RateLimitUpsert {
	u.SetExcluded(ratelimit.FieldWindowSeconds)
	return u
}

// AddWindowSeconds adds v to the "window_seconds" field.
func (u *RateLimitUpsert) AddWindowSeconds(v int) *RateLimitUpsert {
	u.Add(ratelimit.FieldWindowSeconds, v)
	return u
}

// SetBurst sets the "burst" field.
func (u *RateLimitUpsert) SetBurst(v int) *RateLimitUpsert {
	u.Set(ratelimit.FieldBurst, v)
	return u
}

// UpdateBurst sets the "burst" field to the value that was provided on create.
func (u *RateLimitUpsert) UpdateBurst() *RateLimitUpsert {
	u.SetExcluded(ratelimit.FieldBurst)
	return u
}

// AddBurst adds v to the "burst" field.
func (u *RateLimitUpsert) AddBurst(v int) *RateLimitUpsert {
	u.Add(ratelimit.FieldBurst, v)
	return u
}

// ClearBurst clears the value of the "burst" field.
func (u *RateLimitUpsert) ClearBurst() *RateLimitUpsert {
	u.SetNull(ratelimit.FieldBurst)
	return u
}

// SetResponseCode sets the "response_code" field.
func (u *RateLimitUpsert) SetResponseCode(v int) *RateLimitUpsert {
	u.Set(ratelimit.FieldResponseCode, v)
	return u
}

// UpdateResponseCode sets the "response_code" field to the value that was provided on create.
func (u *RateLimitUpsert) UpdateResponseCode() *RateLimitUpsert {
	u.SetExcluded(ratelimit.FieldResponseCode)
	return u
}

// AddResponseCode adds v to the "response_code" field.
func (u *RateLimitUpsert) AddResponseCode(v int) *RateLimitUpsert {
	u.Add(ratelimit.FieldResponseCode, v)
	return u
}

// SetStatus sets the "status" field.
func (u *RateLimitUpsert) SetStatus(v string) *RateLimitUpsert {
	u.Set(ratelimit.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RateLimitUpsert) UpdateStatus() *RateLimitUpsert {
	u.SetExcluded(ratelimit.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RateLimitUpsert) SetUpdatedAt(v time.Time) *RateLimitUpsert {
	u.Set(ratelimit.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RateLimitUpsert) UpdateUpdatedAt() *RateLimitUpsert {
	u.SetExcluded(ratelimit.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RateLimit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ratelimit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RateLimitUpsertOne) UpdateNewValues() *RateLimitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ratelimit.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ratelimit.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RateLimit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RateLimitUpsertOne) Ignore() *RateLimitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RateLimitUpsertOne) DoNothing() *RateLimitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RateLimitCreate.OnConflict
// documentation for more info.
func (u *RateLimitUpsertOne) Update(set func(*RateLimitUpsert)) *RateLimitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RateLimitUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *RateLimitUpsertOne) SetScope(v string) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *RateLimitUpsertOne) UpdateScope() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateScope()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *RateLimitUpsertOne) SetTenantID(v uuid.UUID) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *RateLimitUpsertOne) UpdateTenantID() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *RateLimitUpsertOne) ClearTenantID() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.ClearTenantID()
	})
}

// SetDomainID sets the "domain_id" field.
func (u *RateLimitUpsertOne) SetDomainID(v uuid.UUID) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetDomainID(v)
	})
}

// UpdateDomainID sets the "domain_id" field to the value that was provided on create.
func (u *RateLimitUpsertOne) UpdateDomainID() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateDomainID()
	})
}

// ClearDomainID clears the value of the "domain_id" field.
func (u *RateLimitUpsertOne) ClearDomainID() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.ClearDomainID()
	})
}

// SetServiceID sets the "service_id" field.
func (u *RateLimitUpsertOne) SetServiceID(v uuid.UUID) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetServiceID(v)
	})
}

// UpdateServiceID sets the "service_id" field to the value that was provided on create.
func (u *RateLimitUpsertOne) UpdateServiceID() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateServiceID()
	})
}

// ClearServiceID clears the value of the "service_id" field.
func (u *RateLimitUpsertOne) ClearServiceID() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.ClearServiceID()
	})
}

// SetName sets the "name" field.
func (u *RateLimitUpsertOne) SetName(v string) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RateLimitUpsertOne) UpdateName() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateName()
	})
}

// SetLimit sets the "limit" field.
func (u *RateLimitUpsertOne) SetLimit(v int) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetLimit(v)
	})
}

// AddLimit adds v to the "limit" field.
func (u *RateLimitUpsertOne) AddLimit(v int) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.AddLimit(v)
	})
}

// UpdateLimit sets the "limit" field to the value that was provided on create.
func (u *RateLimitUpsertOne) UpdateLimit() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateLimit()
	})
}

// SetWindowSeconds sets the "window_seconds" field.
func (u *RateLimitUpsertOne) SetWindowSeconds(v int) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetWindowSeconds(v)
	})
}

// AddWindowSeconds adds v to the "window_seconds" field.
func (u *RateLimitUpsertOne) AddWindowSeconds(v int) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.AddWindowSeconds(v)
	})
}

// UpdateWindowSeconds sets the "window_seconds" field to the value that was provided on create.
func (u *RateLimitUpsertOne) UpdateWindowSeconds() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateWindowSeconds()
	})
}

// SetBurst sets the "burst" field.
func (u *RateLimitUpsertOne) SetBurst(v int) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetBurst(v)
	})
}

// AddBurst adds v to the "burst" field.
func (u *RateLimitUpsertOne) AddBurst(v int) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.AddBurst(v)
	})
}

// UpdateBurst sets the "burst" field to the value that was provided on create.
func (u *RateLimitUpsertOne) UpdateBurst() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateBurst()
	})
}

// ClearBurst clears the value of the "burst" field.
func (u *RateLimitUpsertOne) ClearBurst() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.ClearBurst()
	})
}

// SetResponseCode sets the "response_code" field.
func (u *RateLimitUpsertOne) SetResponseCode(v int) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetResponseCode(v)
	})
}

// AddResponseCode adds v to the "response_code" field.
func (u *RateLimitUpsertOne) AddResponseCode(v int) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.AddResponseCode(v)
	})
}

// UpdateResponseCode sets the "response_code" field to the value that was provided on create.
func (u *RateLimitUpsertOne) UpdateResponseCode() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateResponseCode()
	})
}

// SetStatus sets the "status" field.
func (u *RateLimitUpsertOne) SetStatus(v string) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RateLimitUpsertOne) UpdateStatus() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RateLimitUpsertOne) SetUpdatedAt(v time.Time) *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RateLimitUpsertOne) UpdateUpdatedAt() *RateLimitUpsertOne {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RateLimitUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RateLimitCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RateLimitUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RateLimitUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RateLimitUpsertOne.ID is not supported by MySQL driver. Use RateLimitUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RateLimitUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RateLimitCreateBulk is the builder for creating many RateLimit entities in bulk.
type RateLimitCreateBulk struct {
	config
	err      error
	builders []*RateLimitCreate
	conflict []sql.ConflictOption
}

// Save creates the RateLimit entities in the database.
func (rlcb *RateLimitCreateBulk) Save(ctx context.Context) ([]*RateLimit, error) {
	if rlcb.err != nil {
		return nil, rlcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rlcb.builders))
	nodes := make([]*RateLimit, len(rlcb.builders))
	mutators := make([]Mutator, len(rlcb.builders))
	for i := range rlcb.builders {
		func(i int, root context.Context) {
			builder := rlcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RateLimitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rlcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rlcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rlcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rlcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rlcb *RateLimitCreateBulk) SaveX(ctx context.Context) []*RateLimit {
	v, err := rlcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rlcb *RateLimitCreateBulk) Exec(ctx context.Context) error {
	_, err := rlcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rlcb *RateLimitCreateBulk) ExecX(ctx context.Context) {
	if err := rlcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RateLimit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RateLimitUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (rlcb *RateLimitCreateBulk) OnConflict(opts ...sql.ConflictOption) *RateLimitUpsertBulk {
	rlcb.conflict = opts
	return &RateLimitUpsertBulk{
		create: rlcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RateLimit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rlcb *RateLimitCreateBulk) OnConflictColumns(columns ...string) *RateLimitUpsertBulk {
	rlcb.conflict = append(rlcb.conflict, sql.ConflictColumns(columns...))
	return &RateLimitUpsertBulk{
		create: rlcb,
	}
}

// RateLimitUpsertBulk is the builder for "upsert"-ing
// a bulk of RateLimit nodes.
type RateLimitUpsertBulk struct {
	create *RateLimitCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RateLimit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ratelimit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RateLimitUpsertBulk) UpdateNewValues() *RateLimitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ratelimit.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ratelimit.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RateLimit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RateLimitUpsertBulk) Ignore() *RateLimitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RateLimitUpsertBulk) DoNothing() *RateLimitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RateLimitCreateBulk.OnConflict
// documentation for more info.
func (u *RateLimitUpsertBulk) Update(set func(*RateLimitUpsert)) *RateLimitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RateLimitUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *RateLimitUpsertBulk) SetScope(v string) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *RateLimitUpsertBulk) UpdateScope() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateScope()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *RateLimitUpsertBulk) SetTenantID(v uuid.UUID) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *RateLimitUpsertBulk) UpdateTenantID() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *RateLimitUpsertBulk) ClearTenantID() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.ClearTenantID()
	})
}

// SetDomainID sets the "domain_id" field.
func (u *RateLimitUpsertBulk) SetDomainID(v uuid.UUID) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetDomainID(v)
	})
}

// UpdateDomainID sets the "domain_id" field to the value that was provided on create.
func (u *RateLimitUpsertBulk) UpdateDomainID() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateDomainID()
	})
}

// ClearDomainID clears the value of the "domain_id" field.
func (u *RateLimitUpsertBulk) ClearDomainID() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.ClearDomainID()
	})
}

// SetServiceID sets the "service_id" field.
func (u *RateLimitUpsertBulk) SetServiceID(v uuid.UUID) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetServiceID(v)
	})
}

// UpdateServiceID sets the "service_id" field to the value that was provided on create.
func (u *RateLimitUpsertBulk) UpdateServiceID() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateServiceID()
	})
}

// ClearServiceID clears the value of the "service_id" field.
func (u *RateLimitUpsertBulk) ClearServiceID() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.ClearServiceID()
	})
}

// SetName sets the "name" field.
func (u *RateLimitUpsertBulk) SetName(v string) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RateLimitUpsertBulk) UpdateName() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateName()
	})
}

// SetLimit sets the "limit" field.
func (u *RateLimitUpsertBulk) SetLimit(v int) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetLimit(v)
	})
}

// AddLimit adds v to the "limit" field.
func (u *RateLimitUpsertBulk) AddLimit(v int) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.AddLimit(v)
	})
}

// UpdateLimit sets the "limit" field to the value that was provided on create.
func (u *RateLimitUpsertBulk) UpdateLimit() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateLimit()
	})
}

// SetWindowSeconds sets the "window_seconds" field.
func (u *RateLimitUpsertBulk) SetWindowSeconds(v int) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetWindowSeconds(v)
	})
}

// AddWindowSeconds adds v to the "window_seconds" field.
func (u *RateLimitUpsertBulk) AddWindowSeconds(v int) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.AddWindowSeconds(v)
	})
}

// UpdateWindowSeconds sets the "window_seconds" field to the value that was provided on create.
func (u *RateLimitUpsertBulk) UpdateWindowSeconds() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateWindowSeconds()
	})
}

// SetBurst sets the "burst" field.
func (u *RateLimitUpsertBulk) SetBurst(v int) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetBurst(v)
	})
}

// AddBurst adds v to the "burst" field.
func (u *RateLimitUpsertBulk) AddBurst(v int) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.AddBurst(v)
	})
}

// UpdateBurst sets the "burst" field to the value that was provided on create.
func (u *RateLimitUpsertBulk) UpdateBurst() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateBurst()
	})
}

// ClearBurst clears the value of the "burst" field.
func (u *RateLimitUpsertBulk) ClearBurst() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.ClearBurst()
	})
}

// SetResponseCode sets the "response_code" field.
func (u *RateLimitUpsertBulk) SetResponseCode(v int) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetResponseCode(v)
	})
}

// AddResponseCode adds v to the "response_code" field.
func (u *RateLimitUpsertBulk) AddResponseCode(v int) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.AddResponseCode(v)
	})
}

// UpdateResponseCode sets the "response_code" field to the value that was provided on create.
func (u *RateLimitUpsertBulk) UpdateResponseCode() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateResponseCode()
	})
}

// SetStatus sets the "status" field.
func (u *RateLimitUpsertBulk) SetStatus(v string) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RateLimitUpsertBulk) UpdateStatus() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RateLimitUpsertBulk) SetUpdatedAt(v time.Time) *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RateLimitUpsertBulk) UpdateUpdatedAt() *RateLimitUpsertBulk {
	return u.Update(func(s *RateLimitUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RateLimitUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RateLimitCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RateLimitCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RateLimitUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
