// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NeoPlayful/maple-gateway/server/ent/predicate"
	"github.com/NeoPlayful/maple-gateway/server/ent/releaseevent"
	"github.com/google/uuid"
)

// ReleaseEventQuery is the builder for querying ReleaseEvent entities.
type ReleaseEventQuery struct {
	config
	ctx        *QueryContext
	order      []releaseevent.OrderOption
	inters     []Interceptor
	predicates []predicate.ReleaseEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReleaseEventQuery builder.
func (req *ReleaseEventQuery) Where(ps ...predicate.ReleaseEvent) *ReleaseEventQuery {
	req.predicates = append(req.predicates, ps...)
	return req
}

// Limit the number of records to be returned by this query.
func (req *ReleaseEventQuery) Limit(limit int) *ReleaseEventQuery {
	req.ctx.Limit = &limit
	return req
}

// Offset to start from.
func (req *ReleaseEventQuery) Offset(offset int) *ReleaseEventQuery {
	req.ctx.Offset = &offset
	return req
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (req *ReleaseEventQuery) Unique(unique bool) *ReleaseEventQuery {
	req.ctx.Unique = &unique
	return req
}

// Order specifies how the records should be ordered.
func (req *ReleaseEventQuery) Order(o ...releaseevent.OrderOption) *ReleaseEventQuery {
	req.order = append(req.order, o...)
	return req
}

// First returns the first ReleaseEvent entity from the query.
// Returns a *NotFoundError when no ReleaseEvent was found.
func (req *ReleaseEventQuery) First(ctx context.Context) (*ReleaseEvent, error) {
	nodes, err := req.Limit(1).All(setContextOp(ctx, req.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{releaseevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (req *ReleaseEventQuery) FirstX(ctx context.Context) *ReleaseEvent {
	node, err := req.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReleaseEvent ID from the query.
// Returns a *NotFoundError when no ReleaseEvent ID was found.
func (req *ReleaseEventQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = req.Limit(1).IDs(setContextOp(ctx, req.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{releaseevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (req *ReleaseEventQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := req.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReleaseEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReleaseEvent entity is found.
// Returns a *NotFoundError when no ReleaseEvent entities are found.
func (req *ReleaseEventQuery) Only(ctx context.Context) (*ReleaseEvent, error) {
	nodes, err := req.Limit(2).All(setContextOp(ctx, req.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{releaseevent.Label}
	default:
		return nil, &NotSingularError{releaseevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (req *ReleaseEventQuery) OnlyX(ctx context.Context) *ReleaseEvent {
	node, err := req.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReleaseEvent ID in the query.
// Returns a *NotSingularError when more than one ReleaseEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (req *ReleaseEventQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = req.Limit(2).IDs(setContextOp(ctx, req.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{releaseevent.Label}
	default:
		err = &NotSingularError{releaseevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (req *ReleaseEventQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := req.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReleaseEvents.
func (req *ReleaseEventQuery) All(ctx context.Context) ([]*ReleaseEvent, error) {
	ctx = setContextOp(ctx, req.ctx, ent.OpQueryAll)
	if err := req.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReleaseEvent, *ReleaseEventQuery]()
	return withInterceptors[[]*ReleaseEvent](ctx, req, qr, req.inters)
}

// AllX is like All, but panics if an error occurs.
func (req *ReleaseEventQuery) AllX(ctx context.Context) []*ReleaseEvent {
	nodes, err := req.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReleaseEvent IDs.
func (req *ReleaseEventQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if req.ctx.Unique == nil && req.path != nil {
		req.Unique(true)
	}
	ctx = setContextOp(ctx, req.ctx, ent.OpQueryIDs)
	if err = req.Select(releaseevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (req *ReleaseEventQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := req.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (req *ReleaseEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, req.ctx, ent.OpQueryCount)
	if err := req.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, req, querierCount[*ReleaseEventQuery](), req.inters)
}

// CountX is like Count, but panics if an error occurs.
func (req *ReleaseEventQuery) CountX(ctx context.Context) int {
	count, err := req.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (req *ReleaseEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, req.ctx, ent.OpQueryExist)
	switch _, err := req.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (req *ReleaseEventQuery) ExistX(ctx context.Context) bool {
	exist, err := req.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReleaseEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (req *ReleaseEventQuery) Clone() *ReleaseEventQuery {
	if req == nil {
		return nil
	}
	return &ReleaseEventQuery{
		config:     req.config,
		ctx:        req.ctx.Clone(),
		order:      append([]releaseevent.OrderOption{}, req.order...),
		inters:     append([]Interceptor{}, req.inters...),
		predicates: append([]predicate.ReleaseEvent{}, req.predicates...),
		// clone intermediate query.
		sql:  req.sql.Clone(),
		path: req.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ReleaseID uuid.UUID `json:"release_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReleaseEvent.Query().
//		GroupBy(releaseevent.FieldReleaseID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (req *ReleaseEventQuery) GroupBy(field string, fields ...string) *ReleaseEventGroupBy {
	req.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReleaseEventGroupBy{build: req}
	grbuild.flds = &req.ctx.Fields
	grbuild.label = releaseevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ReleaseID uuid.UUID `json:"release_id,omitempty"`
//	}
//
//	client.ReleaseEvent.Query().
//		Select(releaseevent.FieldReleaseID).
//		Scan(ctx, &v)
func (req *ReleaseEventQuery) Select(fields ...string) *ReleaseEventSelect {
	req.ctx.Fields = append(req.ctx.Fields, fields...)
	sbuild := &ReleaseEventSelect{ReleaseEventQuery: req}
	sbuild.label = releaseevent.Label
	sbuild.flds, sbuild.scan = &req.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReleaseEventSelect configured with the given aggregations.
func (req *ReleaseEventQuery) Aggregate(fns ...AggregateFunc) *ReleaseEventSelect {
	return req.Select().Aggregate(fns...)
}

func (req *ReleaseEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range req.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, req); err != nil {
				return err
			}
		}
	}
	for _, f := range req.ctx.Fields {
		if !releaseevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if req.path != nil {
		prev, err := req.path(ctx)
		if err != nil {
			return err
		}
		req.sql = prev
	}
	return nil
}

func (req *ReleaseEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReleaseEvent, error) {
	var (
		nodes = []*ReleaseEvent{}
		_spec = req.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReleaseEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReleaseEvent{config: req.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, req.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (req *ReleaseEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := req.querySpec()
	_spec.Node.Columns = req.ctx.Fields
	if len(req.ctx.Fields) > 0 {
		_spec.Unique = req.ctx.Unique != nil && *req.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, req.driver, _spec)
}

func (req *ReleaseEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(releaseevent.Table, releaseevent.Columns, sqlgraph.NewFieldSpec(releaseevent.FieldID, field.TypeUUID))
	_spec.From = req.sql
	if unique := req.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if req.path != nil {
		_spec.Unique = true
	}
	if fields := req.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, releaseevent.FieldID)
		for i := range fields {
			if fields[i] != releaseevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := req.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := req.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := req.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := req.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (req *ReleaseEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(req.driver.Dialect())
	t1 := builder.Table(releaseevent.Table)
	columns := req.ctx.Fields
	if len(columns) == 0 {
		columns = releaseevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if req.sql != nil {
		selector = req.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if req.ctx.Unique != nil && *req.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range req.predicates {
		p(selector)
	}
	for _, p := range req.order {
		p(selector)
	}
	if offset := req.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := req.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReleaseEventGroupBy is the group-by builder for ReleaseEvent entities.
type ReleaseEventGroupBy struct {
	selector
	build *ReleaseEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (regb *ReleaseEventGroupBy) Aggregate(fns ...AggregateFunc) *ReleaseEventGroupBy {
	regb.fns = append(regb.fns, fns...)
	return regb
}

// Scan applies the selector query and scans the result into the given value.
func (regb *ReleaseEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, regb.build.ctx, ent.OpQueryGroupBy)
	if err := regb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReleaseEventQuery, *ReleaseEventGroupBy](ctx, regb.build, regb, regb.build.inters, v)
}

func (regb *ReleaseEventGroupBy) sqlScan(ctx context.Context, root *ReleaseEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(regb.fns))
	for _, fn := range regb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*regb.flds)+len(regb.fns))
		for _, f := range *regb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*regb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := regb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReleaseEventSelect is the builder for selecting fields of ReleaseEvent entities.
type ReleaseEventSelect struct {
	*ReleaseEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (res *ReleaseEventSelect) Aggregate(fns ...AggregateFunc) *ReleaseEventSelect {
	res.fns = append(res.fns, fns...)
	return res
}

// Scan applies the selector query and scans the result into the given value.
func (res *ReleaseEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, res.ctx, ent.OpQuerySelect)
	if err := res.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReleaseEventQuery, *ReleaseEventSelect](ctx, res.ReleaseEventQuery, res, res.inters, v)
}

func (res *ReleaseEventSelect) sqlScan(ctx context.Context, root *ReleaseEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(res.fns))
	for _, fn := range res.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*res.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := res.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
