// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"

	"github.com/NeoPlayful/maple-gateway/server/ent/acmeaccount"
	"github.com/NeoPlayful/maple-gateway/server/ent/auditlog"
	"github.com/NeoPlayful/maple-gateway/server/ent/bluegreendeployment"
	"github.com/NeoPlayful/maple-gateway/server/ent/bluegreenevent"
	"github.com/NeoPlayful/maple-gateway/server/ent/canaryevent"
	"github.com/NeoPlayful/maple-gateway/server/ent/canaryrelease"
	"github.com/NeoPlayful/maple-gateway/server/ent/certificate"
	"github.com/NeoPlayful/maple-gateway/server/ent/certificateoperation"
	"github.com/NeoPlayful/maple-gateway/server/ent/deployment"
	"github.com/NeoPlayful/maple-gateway/server/ent/deploymentversion"
	"github.com/NeoPlayful/maple-gateway/server/ent/domain"
	"github.com/NeoPlayful/maple-gateway/server/ent/gatewayinstance"
	"github.com/NeoPlayful/maple-gateway/server/ent/instance"
	"github.com/NeoPlayful/maple-gateway/server/ent/node"
	"github.com/NeoPlayful/maple-gateway/server/ent/ratelimit"
	"github.com/NeoPlayful/maple-gateway/server/ent/schema"
	"github.com/NeoPlayful/maple-gateway/server/ent/service"
	"github.com/NeoPlayful/maple-gateway/server/ent/setting"
	"github.com/NeoPlayful/maple-gateway/server/ent/settinghistory"
	"github.com/NeoPlayful/maple-gateway/server/ent/tenant"
	"github.com/NeoPlayful/maple-gateway/server/ent/trafficpolicy"
	"github.com/NeoPlayful/maple-gateway/server/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	acmeaccountFields := schema.ACMEAccount{}.Fields()
	_ = acmeaccountFields
	// acmeaccountDescDirectoryURL is the schema descriptor for directory_url field.
	acmeaccountDescDirectoryURL := acmeaccountFields[1].Descriptor()
	// acmeaccount.DirectoryURLValidator is a validator for the "directory_url" field. It is called by the builders before save.
	acmeaccount.DirectoryURLValidator = acmeaccountDescDirectoryURL.Validators[0].(func(string) error)
	// acmeaccountDescAccountURL is the schema descriptor for account_url field.
	acmeaccountDescAccountURL := acmeaccountFields[2].Descriptor()
	// acmeaccount.DefaultAccountURL holds the default value on creation for the account_url field.
	acmeaccount.DefaultAccountURL = acmeaccountDescAccountURL.Default.(string)
	// acmeaccountDescEmail is the schema descriptor for email field.
	acmeaccountDescEmail := acmeaccountFields[3].Descriptor()
	// acmeaccount.DefaultEmail holds the default value on creation for the email field.
	acmeaccount.DefaultEmail = acmeaccountDescEmail.Default.(string)
	// acmeaccountDescKeyEncrypted is the schema descriptor for key_encrypted field.
	acmeaccountDescKeyEncrypted := acmeaccountFields[4].Descriptor()
	// acmeaccount.KeyEncryptedValidator is a validator for the "key_encrypted" field. It is called by the builders before save.
	acmeaccount.KeyEncryptedValidator = acmeaccountDescKeyEncrypted.Validators[0].(func(string) error)
	// acmeaccountDescStatus is the schema descriptor for status field.
	acmeaccountDescStatus := acmeaccountFields[5].Descriptor()
	// acmeaccount.DefaultStatus holds the default value on creation for the status field.
	acmeaccount.DefaultStatus = acmeaccountDescStatus.Default.(string)
	// acmeaccountDescLastError is the schema descriptor for last_error field.
	acmeaccountDescLastError := acmeaccountFields[6].Descriptor()
	// acmeaccount.DefaultLastError holds the default value on creation for the last_error field.
	acmeaccount.DefaultLastError = acmeaccountDescLastError.Default.(string)
	// acmeaccountDescID is the schema descriptor for id field.
	acmeaccountDescID := acmeaccountFields[0].Descriptor()
	// acmeaccount.DefaultID holds the default value on creation for the id field.
	acmeaccount.DefaultID = acmeaccountDescID.Default.(func() uuid.UUID)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[2].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescTargetType is the schema descriptor for target_type field.
	auditlogDescTargetType := auditlogFields[3].Descriptor()
	// auditlog.TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	auditlog.TargetTypeValidator = auditlogDescTargetType.Validators[0].(func(string) error)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() uuid.UUID)
	bluegreendeploymentFields := schema.BluegreenDeployment{}.Fields()
	_ = bluegreendeploymentFields
	// bluegreendeploymentDescID is the schema descriptor for id field.
	bluegreendeploymentDescID := bluegreendeploymentFields[0].Descriptor()
	// bluegreendeployment.DefaultID holds the default value on creation for the id field.
	bluegreendeployment.DefaultID = bluegreendeploymentDescID.Default.(func() uuid.UUID)
	bluegreeneventFields := schema.BluegreenEvent{}.Fields()
	_ = bluegreeneventFields
	// bluegreeneventDescAction is the schema descriptor for action field.
	bluegreeneventDescAction := bluegreeneventFields[2].Descriptor()
	// bluegreenevent.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	bluegreenevent.ActionValidator = bluegreeneventDescAction.Validators[0].(func(string) error)
	// bluegreeneventDescDetail is the schema descriptor for detail field.
	bluegreeneventDescDetail := bluegreeneventFields[5].Descriptor()
	// bluegreenevent.DefaultDetail holds the default value on creation for the detail field.
	bluegreenevent.DefaultDetail = bluegreeneventDescDetail.Default.(string)
	// bluegreeneventDescID is the schema descriptor for id field.
	bluegreeneventDescID := bluegreeneventFields[0].Descriptor()
	// bluegreenevent.DefaultID holds the default value on creation for the id field.
	bluegreenevent.DefaultID = bluegreeneventDescID.Default.(func() uuid.UUID)
	canaryeventFields := schema.CanaryEvent{}.Fields()
	_ = canaryeventFields
	// canaryeventDescPhase is the schema descriptor for phase field.
	canaryeventDescPhase := canaryeventFields[2].Descriptor()
	// canaryevent.PhaseValidator is a validator for the "phase" field. It is called by the builders before save.
	canaryevent.PhaseValidator = canaryeventDescPhase.Validators[0].(func(string) error)
	// canaryeventDescDetail is the schema descriptor for detail field.
	canaryeventDescDetail := canaryeventFields[5].Descriptor()
	// canaryevent.DefaultDetail holds the default value on creation for the detail field.
	canaryevent.DefaultDetail = canaryeventDescDetail.Default.(string)
	// canaryeventDescID is the schema descriptor for id field.
	canaryeventDescID := canaryeventFields[0].Descriptor()
	// canaryevent.DefaultID holds the default value on creation for the id field.
	canaryevent.DefaultID = canaryeventDescID.Default.(func() uuid.UUID)
	canaryreleaseFields := schema.CanaryRelease{}.Fields()
	_ = canaryreleaseFields
	// canaryreleaseDescName is the schema descriptor for name field.
	canaryreleaseDescName := canaryreleaseFields[2].Descriptor()
	// canaryrelease.NameValidator is a validator for the "name" field. It is called by the builders before save.
	canaryrelease.NameValidator = canaryreleaseDescName.Validators[0].(func(string) error)
	// canaryreleaseDescPhase is the schema descriptor for phase field.
	canaryreleaseDescPhase := canaryreleaseFields[5].Descriptor()
	// canaryrelease.DefaultPhase holds the default value on creation for the phase field.
	canaryrelease.DefaultPhase = canaryreleaseDescPhase.Default.(string)
	// canaryreleaseDescCanaryWeight is the schema descriptor for canary_weight field.
	canaryreleaseDescCanaryWeight := canaryreleaseFields[6].Descriptor()
	// canaryrelease.DefaultCanaryWeight holds the default value on creation for the canary_weight field.
	canaryrelease.DefaultCanaryWeight = canaryreleaseDescCanaryWeight.Default.(int)
	// canaryreleaseDescTargetWeight is the schema descriptor for target_weight field.
	canaryreleaseDescTargetWeight := canaryreleaseFields[7].Descriptor()
	// canaryrelease.DefaultTargetWeight holds the default value on creation for the target_weight field.
	canaryrelease.DefaultTargetWeight = canaryreleaseDescTargetWeight.Default.(int)
	// canaryreleaseDescStepWeight is the schema descriptor for step_weight field.
	canaryreleaseDescStepWeight := canaryreleaseFields[8].Descriptor()
	// canaryrelease.DefaultStepWeight holds the default value on creation for the step_weight field.
	canaryrelease.DefaultStepWeight = canaryreleaseDescStepWeight.Default.(int)
	// canaryreleaseDescID is the schema descriptor for id field.
	canaryreleaseDescID := canaryreleaseFields[0].Descriptor()
	// canaryrelease.DefaultID holds the default value on creation for the id field.
	canaryrelease.DefaultID = canaryreleaseDescID.Default.(func() uuid.UUID)
	certificateFields := schema.Certificate{}.Fields()
	_ = certificateFields
	// certificateDescHostname is the schema descriptor for hostname field.
	certificateDescHostname := certificateFields[2].Descriptor()
	// certificate.HostnameValidator is a validator for the "hostname" field. It is called by the builders before save.
	certificate.HostnameValidator = certificateDescHostname.Validators[0].(func(string) error)
	// certificateDescSource is the schema descriptor for source field.
	certificateDescSource := certificateFields[3].Descriptor()
	// certificate.DefaultSource holds the default value on creation for the source field.
	certificate.DefaultSource = certificateDescSource.Default.(string)
	// certificateDescStatus is the schema descriptor for status field.
	certificateDescStatus := certificateFields[4].Descriptor()
	// certificate.DefaultStatus holds the default value on creation for the status field.
	certificate.DefaultStatus = certificateDescStatus.Default.(string)
	// certificateDescCertificatePem is the schema descriptor for certificate_pem field.
	certificateDescCertificatePem := certificateFields[5].Descriptor()
	// certificate.CertificatePemValidator is a validator for the "certificate_pem" field. It is called by the builders before save.
	certificate.CertificatePemValidator = certificateDescCertificatePem.Validators[0].(func(string) error)
	// certificateDescPrivateKeyEncrypted is the schema descriptor for private_key_encrypted field.
	certificateDescPrivateKeyEncrypted := certificateFields[6].Descriptor()
	// certificate.PrivateKeyEncryptedValidator is a validator for the "private_key_encrypted" field. It is called by the builders before save.
	certificate.PrivateKeyEncryptedValidator = certificateDescPrivateKeyEncrypted.Validators[0].(func(string) error)
	// certificateDescIssuer is the schema descriptor for issuer field.
	certificateDescIssuer := certificateFields[7].Descriptor()
	// certificate.DefaultIssuer holds the default value on creation for the issuer field.
	certificate.DefaultIssuer = certificateDescIssuer.Default.(string)
	// certificateDescSerialNumber is the schema descriptor for serial_number field.
	certificateDescSerialNumber := certificateFields[8].Descriptor()
	// certificate.DefaultSerialNumber holds the default value on creation for the serial_number field.
	certificate.DefaultSerialNumber = certificateDescSerialNumber.Default.(string)
	// certificateDescLastError is the schema descriptor for last_error field.
	certificateDescLastError := certificateFields[12].Descriptor()
	// certificate.DefaultLastError holds the default value on creation for the last_error field.
	certificate.DefaultLastError = certificateDescLastError.Default.(string)
	// certificateDescRenewAttempts is the schema descriptor for renew_attempts field.
	certificateDescRenewAttempts := certificateFields[14].Descriptor()
	// certificate.DefaultRenewAttempts holds the default value on creation for the renew_attempts field.
	certificate.DefaultRenewAttempts = certificateDescRenewAttempts.Default.(int)
	// certificateDescLastRenewError is the schema descriptor for last_renew_error field.
	certificateDescLastRenewError := certificateFields[16].Descriptor()
	// certificate.DefaultLastRenewError holds the default value on creation for the last_renew_error field.
	certificate.DefaultLastRenewError = certificateDescLastRenewError.Default.(string)
	// certificateDescID is the schema descriptor for id field.
	certificateDescID := certificateFields[0].Descriptor()
	// certificate.DefaultID holds the default value on creation for the id field.
	certificate.DefaultID = certificateDescID.Default.(func() uuid.UUID)
	certificateoperationFields := schema.CertificateOperation{}.Fields()
	_ = certificateoperationFields
	// certificateoperationDescHostname is the schema descriptor for hostname field.
	certificateoperationDescHostname := certificateoperationFields[1].Descriptor()
	// certificateoperation.HostnameValidator is a validator for the "hostname" field. It is called by the builders before save.
	certificateoperation.HostnameValidator = certificateoperationDescHostname.Validators[0].(func(string) error)
	// certificateoperationDescAction is the schema descriptor for action field.
	certificateoperationDescAction := certificateoperationFields[3].Descriptor()
	// certificateoperation.DefaultAction holds the default value on creation for the action field.
	certificateoperation.DefaultAction = certificateoperationDescAction.Default.(string)
	// certificateoperationDescStatus is the schema descriptor for status field.
	certificateoperationDescStatus := certificateoperationFields[4].Descriptor()
	// certificateoperation.DefaultStatus holds the default value on creation for the status field.
	certificateoperation.DefaultStatus = certificateoperationDescStatus.Default.(string)
	// certificateoperationDescMessage is the schema descriptor for message field.
	certificateoperationDescMessage := certificateoperationFields[5].Descriptor()
	// certificateoperation.DefaultMessage holds the default value on creation for the message field.
	certificateoperation.DefaultMessage = certificateoperationDescMessage.Default.(string)
	// certificateoperationDescError is the schema descriptor for error field.
	certificateoperationDescError := certificateoperationFields[6].Descriptor()
	// certificateoperation.DefaultError holds the default value on creation for the error field.
	certificateoperation.DefaultError = certificateoperationDescError.Default.(string)
	// certificateoperationDescID is the schema descriptor for id field.
	certificateoperationDescID := certificateoperationFields[0].Descriptor()
	// certificateoperation.DefaultID holds the default value on creation for the id field.
	certificateoperation.DefaultID = certificateoperationDescID.Default.(func() uuid.UUID)
	deploymentFields := schema.Deployment{}.Fields()
	_ = deploymentFields
	// deploymentDescName is the schema descriptor for name field.
	deploymentDescName := deploymentFields[2].Descriptor()
	// deployment.NameValidator is a validator for the "name" field. It is called by the builders before save.
	deployment.NameValidator = deploymentDescName.Validators[0].(func(string) error)
	// deploymentDescStatus is the schema descriptor for status field.
	deploymentDescStatus := deploymentFields[3].Descriptor()
	// deployment.DefaultStatus holds the default value on creation for the status field.
	deployment.DefaultStatus = deploymentDescStatus.Default.(string)
	// deploymentDescStrategy is the schema descriptor for strategy field.
	deploymentDescStrategy := deploymentFields[4].Descriptor()
	// deployment.DefaultStrategy holds the default value on creation for the strategy field.
	deployment.DefaultStrategy = deploymentDescStrategy.Default.(string)
	// deploymentDescID is the schema descriptor for id field.
	deploymentDescID := deploymentFields[0].Descriptor()
	// deployment.DefaultID holds the default value on creation for the id field.
	deployment.DefaultID = deploymentDescID.Default.(func() uuid.UUID)
	deploymentversionFields := schema.DeploymentVersion{}.Fields()
	_ = deploymentversionFields
	// deploymentversionDescVersion is the schema descriptor for version field.
	deploymentversionDescVersion := deploymentversionFields[2].Descriptor()
	// deploymentversion.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	deploymentversion.VersionValidator = deploymentversionDescVersion.Validators[0].(func(string) error)
	// deploymentversionDescImage is the schema descriptor for image field.
	deploymentversionDescImage := deploymentversionFields[3].Descriptor()
	// deploymentversion.DefaultImage holds the default value on creation for the image field.
	deploymentversion.DefaultImage = deploymentversionDescImage.Default.(string)
	// deploymentversionDescWeight is the schema descriptor for weight field.
	deploymentversionDescWeight := deploymentversionFields[4].Descriptor()
	// deploymentversion.DefaultWeight holds the default value on creation for the weight field.
	deploymentversion.DefaultWeight = deploymentversionDescWeight.Default.(int)
	// deploymentversionDescStatus is the schema descriptor for status field.
	deploymentversionDescStatus := deploymentversionFields[5].Descriptor()
	// deploymentversion.DefaultStatus holds the default value on creation for the status field.
	deploymentversion.DefaultStatus = deploymentversionDescStatus.Default.(string)
	// deploymentversionDescID is the schema descriptor for id field.
	deploymentversionDescID := deploymentversionFields[0].Descriptor()
	// deploymentversion.DefaultID holds the default value on creation for the id field.
	deploymentversion.DefaultID = deploymentversionDescID.Default.(func() uuid.UUID)
	domainFields := schema.Domain{}.Fields()
	_ = domainFields
	// domainDescHostname is the schema descriptor for hostname field.
	domainDescHostname := domainFields[2].Descriptor()
	// domain.HostnameValidator is a validator for the "hostname" field. It is called by the builders before save.
	domain.HostnameValidator = domainDescHostname.Validators[0].(func(string) error)
	// domainDescStatus is the schema descriptor for status field.
	domainDescStatus := domainFields[4].Descriptor()
	// domain.DefaultStatus holds the default value on creation for the status field.
	domain.DefaultStatus = domainDescStatus.Default.(string)
	// domainDescTLSMode is the schema descriptor for tls_mode field.
	domainDescTLSMode := domainFields[6].Descriptor()
	// domain.DefaultTLSMode holds the default value on creation for the tls_mode field.
	domain.DefaultTLSMode = domainDescTLSMode.Default.(string)
	// domainDescID is the schema descriptor for id field.
	domainDescID := domainFields[0].Descriptor()
	// domain.DefaultID holds the default value on creation for the id field.
	domain.DefaultID = domainDescID.Default.(func() uuid.UUID)
	gatewayinstanceFields := schema.GatewayInstance{}.Fields()
	_ = gatewayinstanceFields
	// gatewayinstanceDescInstanceID is the schema descriptor for instance_id field.
	gatewayinstanceDescInstanceID := gatewayinstanceFields[1].Descriptor()
	// gatewayinstance.InstanceIDValidator is a validator for the "instance_id" field. It is called by the builders before save.
	gatewayinstance.InstanceIDValidator = gatewayinstanceDescInstanceID.Validators[0].(func(string) error)
	// gatewayinstanceDescAddr is the schema descriptor for addr field.
	gatewayinstanceDescAddr := gatewayinstanceFields[2].Descriptor()
	// gatewayinstance.AddrValidator is a validator for the "addr" field. It is called by the builders before save.
	gatewayinstance.AddrValidator = gatewayinstanceDescAddr.Validators[0].(func(string) error)
	// gatewayinstanceDescHostname is the schema descriptor for hostname field.
	gatewayinstanceDescHostname := gatewayinstanceFields[3].Descriptor()
	// gatewayinstance.DefaultHostname holds the default value on creation for the hostname field.
	gatewayinstance.DefaultHostname = gatewayinstanceDescHostname.Default.(string)
	// gatewayinstanceDescStatus is the schema descriptor for status field.
	gatewayinstanceDescStatus := gatewayinstanceFields[4].Descriptor()
	// gatewayinstance.DefaultStatus holds the default value on creation for the status field.
	gatewayinstance.DefaultStatus = gatewayinstanceDescStatus.Default.(string)
	// gatewayinstanceDescRole is the schema descriptor for role field.
	gatewayinstanceDescRole := gatewayinstanceFields[5].Descriptor()
	// gatewayinstance.DefaultRole holds the default value on creation for the role field.
	gatewayinstance.DefaultRole = gatewayinstanceDescRole.Default.(string)
	// gatewayinstanceDescVersion is the schema descriptor for version field.
	gatewayinstanceDescVersion := gatewayinstanceFields[7].Descriptor()
	// gatewayinstance.DefaultVersion holds the default value on creation for the version field.
	gatewayinstance.DefaultVersion = gatewayinstanceDescVersion.Default.(string)
	// gatewayinstanceDescID is the schema descriptor for id field.
	gatewayinstanceDescID := gatewayinstanceFields[0].Descriptor()
	// gatewayinstance.DefaultID holds the default value on creation for the id field.
	gatewayinstance.DefaultID = gatewayinstanceDescID.Default.(func() uuid.UUID)
	instanceFields := schema.Instance{}.Fields()
	_ = instanceFields
	// instanceDescVersion is the schema descriptor for version field.
	instanceDescVersion := instanceFields[5].Descriptor()
	// instance.DefaultVersion holds the default value on creation for the version field.
	instance.DefaultVersion = instanceDescVersion.Default.(string)
	// instanceDescAddress is the schema descriptor for address field.
	instanceDescAddress := instanceFields[6].Descriptor()
	// instance.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	instance.AddressValidator = instanceDescAddress.Validators[0].(func(string) error)
	// instanceDescProtocol is the schema descriptor for protocol field.
	instanceDescProtocol := instanceFields[8].Descriptor()
	// instance.DefaultProtocol holds the default value on creation for the protocol field.
	instance.DefaultProtocol = instanceDescProtocol.Default.(string)
	// instanceDescWeight is the schema descriptor for weight field.
	instanceDescWeight := instanceFields[9].Descriptor()
	// instance.DefaultWeight holds the default value on creation for the weight field.
	instance.DefaultWeight = instanceDescWeight.Default.(int)
	// instanceDescStatus is the schema descriptor for status field.
	instanceDescStatus := instanceFields[10].Descriptor()
	// instance.DefaultStatus holds the default value on creation for the status field.
	instance.DefaultStatus = instanceDescStatus.Default.(string)
	// instanceDescHealth is the schema descriptor for health field.
	instanceDescHealth := instanceFields[11].Descriptor()
	// instance.DefaultHealth holds the default value on creation for the health field.
	instance.DefaultHealth = instanceDescHealth.Default.(string)
	// instanceDescID is the schema descriptor for id field.
	instanceDescID := instanceFields[0].Descriptor()
	// instance.DefaultID holds the default value on creation for the id field.
	instance.DefaultID = instanceDescID.Default.(func() uuid.UUID)
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescName is the schema descriptor for name field.
	nodeDescName := nodeFields[1].Descriptor()
	// node.NameValidator is a validator for the "name" field. It is called by the builders before save.
	node.NameValidator = nodeDescName.Validators[0].(func(string) error)
	// nodeDescHost is the schema descriptor for host field.
	nodeDescHost := nodeFields[2].Descriptor()
	// node.HostValidator is a validator for the "host" field. It is called by the builders before save.
	node.HostValidator = nodeDescHost.Validators[0].(func(string) error)
	// nodeDescRegion is the schema descriptor for region field.
	nodeDescRegion := nodeFields[3].Descriptor()
	// node.DefaultRegion holds the default value on creation for the region field.
	node.DefaultRegion = nodeDescRegion.Default.(string)
	// nodeDescStatus is the schema descriptor for status field.
	nodeDescStatus := nodeFields[5].Descriptor()
	// node.DefaultStatus holds the default value on creation for the status field.
	node.DefaultStatus = nodeDescStatus.Default.(string)
	// nodeDescWeight is the schema descriptor for weight field.
	nodeDescWeight := nodeFields[6].Descriptor()
	// node.DefaultWeight holds the default value on creation for the weight field.
	node.DefaultWeight = nodeDescWeight.Default.(int)
	// nodeDescID is the schema descriptor for id field.
	nodeDescID := nodeFields[0].Descriptor()
	// node.DefaultID holds the default value on creation for the id field.
	node.DefaultID = nodeDescID.Default.(func() uuid.UUID)
	ratelimitFields := schema.RateLimit{}.Fields()
	_ = ratelimitFields
	// ratelimitDescScope is the schema descriptor for scope field.
	ratelimitDescScope := ratelimitFields[1].Descriptor()
	// ratelimit.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	ratelimit.ScopeValidator = ratelimitDescScope.Validators[0].(func(string) error)
	// ratelimitDescName is the schema descriptor for name field.
	ratelimitDescName := ratelimitFields[5].Descriptor()
	// ratelimit.NameValidator is a validator for the "name" field. It is called by the builders before save.
	ratelimit.NameValidator = ratelimitDescName.Validators[0].(func(string) error)
	// ratelimitDescWindowSeconds is the schema descriptor for window_seconds field.
	ratelimitDescWindowSeconds := ratelimitFields[7].Descriptor()
	// ratelimit.DefaultWindowSeconds holds the default value on creation for the window_seconds field.
	ratelimit.DefaultWindowSeconds = ratelimitDescWindowSeconds.Default.(int)
	// ratelimitDescBurst is the schema descriptor for burst field.
	ratelimitDescBurst := ratelimitFields[8].Descriptor()
	// ratelimit.DefaultBurst holds the default value on creation for the burst field.
	ratelimit.DefaultBurst = ratelimitDescBurst.Default.(int)
	// ratelimitDescResponseCode is the schema descriptor for response_code field.
	ratelimitDescResponseCode := ratelimitFields[9].Descriptor()
	// ratelimit.DefaultResponseCode holds the default value on creation for the response_code field.
	ratelimit.DefaultResponseCode = ratelimitDescResponseCode.Default.(int)
	// ratelimitDescStatus is the schema descriptor for status field.
	ratelimitDescStatus := ratelimitFields[10].Descriptor()
	// ratelimit.DefaultStatus holds the default value on creation for the status field.
	ratelimit.DefaultStatus = ratelimitDescStatus.Default.(string)
	// ratelimitDescID is the schema descriptor for id field.
	ratelimitDescID := ratelimitFields[0].Descriptor()
	// ratelimit.DefaultID holds the default value on creation for the id field.
	ratelimit.DefaultID = ratelimitDescID.Default.(func() uuid.UUID)
	serviceFields := schema.Service{}.Fields()
	_ = serviceFields
	// serviceDescName is the schema descriptor for name field.
	serviceDescName := serviceFields[2].Descriptor()
	// service.NameValidator is a validator for the "name" field. It is called by the builders before save.
	service.NameValidator = serviceDescName.Validators[0].(func(string) error)
	// serviceDescProtocol is the schema descriptor for protocol field.
	serviceDescProtocol := serviceFields[3].Descriptor()
	// service.DefaultProtocol holds the default value on creation for the protocol field.
	service.DefaultProtocol = serviceDescProtocol.Default.(string)
	// serviceDescStatus is the schema descriptor for status field.
	serviceDescStatus := serviceFields[4].Descriptor()
	// service.DefaultStatus holds the default value on creation for the status field.
	service.DefaultStatus = serviceDescStatus.Default.(string)
	// serviceDescID is the schema descriptor for id field.
	serviceDescID := serviceFields[0].Descriptor()
	// service.DefaultID holds the default value on creation for the id field.
	service.DefaultID = serviceDescID.Default.(func() uuid.UUID)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescSection is the schema descriptor for section field.
	settingDescSection := settingFields[1].Descriptor()
	// setting.SectionValidator is a validator for the "section" field. It is called by the builders before save.
	setting.SectionValidator = settingDescSection.Validators[0].(func(string) error)
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[2].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = settingDescKey.Validators[0].(func(string) error)
	// settingDescValue is the schema descriptor for value field.
	settingDescValue := settingFields[3].Descriptor()
	// setting.DefaultValue holds the default value on creation for the value field.
	setting.DefaultValue = settingDescValue.Default.(json.RawMessage)
	// settingDescVersion is the schema descriptor for version field.
	settingDescVersion := settingFields[4].Descriptor()
	// setting.DefaultVersion holds the default value on creation for the version field.
	setting.DefaultVersion = settingDescVersion.Default.(int)
	// settingDescID is the schema descriptor for id field.
	settingDescID := settingFields[0].Descriptor()
	// setting.DefaultID holds the default value on creation for the id field.
	setting.DefaultID = settingDescID.Default.(func() uuid.UUID)
	settinghistoryFields := schema.SettingHistory{}.Fields()
	_ = settinghistoryFields
	// settinghistoryDescSection is the schema descriptor for section field.
	settinghistoryDescSection := settinghistoryFields[1].Descriptor()
	// settinghistory.SectionValidator is a validator for the "section" field. It is called by the builders before save.
	settinghistory.SectionValidator = settinghistoryDescSection.Validators[0].(func(string) error)
	// settinghistoryDescKey is the schema descriptor for key field.
	settinghistoryDescKey := settinghistoryFields[2].Descriptor()
	// settinghistory.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	settinghistory.KeyValidator = settinghistoryDescKey.Validators[0].(func(string) error)
	// settinghistoryDescID is the schema descriptor for id field.
	settinghistoryDescID := settinghistoryFields[0].Descriptor()
	// settinghistory.DefaultID holds the default value on creation for the id field.
	settinghistory.DefaultID = settinghistoryDescID.Default.(func() uuid.UUID)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescSlug is the schema descriptor for slug field.
	tenantDescSlug := tenantFields[2].Descriptor()
	// tenant.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tenant.SlugValidator = tenantDescSlug.Validators[0].(func(string) error)
	// tenantDescStatus is the schema descriptor for status field.
	tenantDescStatus := tenantFields[3].Descriptor()
	// tenant.DefaultStatus holds the default value on creation for the status field.
	tenant.DefaultStatus = tenantDescStatus.Default.(string)
	// tenantDescDescription is the schema descriptor for description field.
	tenantDescDescription := tenantFields[4].Descriptor()
	// tenant.DefaultDescription holds the default value on creation for the description field.
	tenant.DefaultDescription = tenantDescDescription.Default.(string)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
	trafficpolicyFields := schema.TrafficPolicy{}.Fields()
	_ = trafficpolicyFields
	// trafficpolicyDescName is the schema descriptor for name field.
	trafficpolicyDescName := trafficpolicyFields[2].Descriptor()
	// trafficpolicy.NameValidator is a validator for the "name" field. It is called by the builders before save.
	trafficpolicy.NameValidator = trafficpolicyDescName.Validators[0].(func(string) error)
	// trafficpolicyDescPriority is the schema descriptor for priority field.
	trafficpolicyDescPriority := trafficpolicyFields[3].Descriptor()
	// trafficpolicy.DefaultPriority holds the default value on creation for the priority field.
	trafficpolicy.DefaultPriority = trafficpolicyDescPriority.Default.(int)
	// trafficpolicyDescMatch is the schema descriptor for match field.
	trafficpolicyDescMatch := trafficpolicyFields[4].Descriptor()
	// trafficpolicy.DefaultMatch holds the default value on creation for the match field.
	trafficpolicy.DefaultMatch = trafficpolicyDescMatch.Default.(json.RawMessage)
	// trafficpolicyDescWeight is the schema descriptor for weight field.
	trafficpolicyDescWeight := trafficpolicyFields[6].Descriptor()
	// trafficpolicy.DefaultWeight holds the default value on creation for the weight field.
	trafficpolicy.DefaultWeight = trafficpolicyDescWeight.Default.(int)
	// trafficpolicyDescBalance is the schema descriptor for balance field.
	trafficpolicyDescBalance := trafficpolicyFields[8].Descriptor()
	// trafficpolicy.DefaultBalance holds the default value on creation for the balance field.
	trafficpolicy.DefaultBalance = trafficpolicyDescBalance.Default.(string)
	// trafficpolicyDescStatus is the schema descriptor for status field.
	trafficpolicyDescStatus := trafficpolicyFields[9].Descriptor()
	// trafficpolicy.DefaultStatus holds the default value on creation for the status field.
	trafficpolicy.DefaultStatus = trafficpolicyDescStatus.Default.(string)
	// trafficpolicyDescID is the schema descriptor for id field.
	trafficpolicyDescID := trafficpolicyFields[0].Descriptor()
	// trafficpolicy.DefaultID holds the default value on creation for the id field.
	trafficpolicy.DefaultID = trafficpolicyDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[4].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[5].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
