// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NeoPlayful/maple-gateway/server/ent/predicate"
	"github.com/NeoPlayful/maple-gateway/server/ent/settinghistory"
	"github.com/google/uuid"
)

// SettingHistoryQuery is the builder for querying SettingHistory entities.
type SettingHistoryQuery struct {
	config
	ctx        *QueryContext
	order      []settinghistory.OrderOption
	inters     []Interceptor
	predicates []predicate.SettingHistory
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SettingHistoryQuery builder.
func (shq *SettingHistoryQuery) Where(ps ...predicate.SettingHistory) *SettingHistoryQuery {
	shq.predicates = append(shq.predicates, ps...)
	return shq
}

// Limit the number of records to be returned by this query.
func (shq *SettingHistoryQuery) Limit(limit int) *SettingHistoryQuery {
	shq.ctx.Limit = &limit
	return shq
}

// Offset to start from.
func (shq *SettingHistoryQuery) Offset(offset int) *SettingHistoryQuery {
	shq.ctx.Offset = &offset
	return shq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (shq *SettingHistoryQuery) Unique(unique bool) *SettingHistoryQuery {
	shq.ctx.Unique = &unique
	return shq
}

// Order specifies how the records should be ordered.
func (shq *SettingHistoryQuery) Order(o ...settinghistory.OrderOption) *SettingHistoryQuery {
	shq.order = append(shq.order, o...)
	return shq
}

// First returns the first SettingHistory entity from the query.
// Returns a *NotFoundError when no SettingHistory was found.
func (shq *SettingHistoryQuery) First(ctx context.Context) (*SettingHistory, error) {
	nodes, err := shq.Limit(1).All(setContextOp(ctx, shq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{settinghistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (shq *SettingHistoryQuery) FirstX(ctx context.Context) *SettingHistory {
	node, err := shq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SettingHistory ID from the query.
// Returns a *NotFoundError when no SettingHistory ID was found.
func (shq *SettingHistoryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = shq.Limit(1).IDs(setContextOp(ctx, shq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{settinghistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (shq *SettingHistoryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := shq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SettingHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SettingHistory entity is found.
// Returns a *NotFoundError when no SettingHistory entities are found.
func (shq *SettingHistoryQuery) Only(ctx context.Context) (*SettingHistory, error) {
	nodes, err := shq.Limit(2).All(setContextOp(ctx, shq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{settinghistory.Label}
	default:
		return nil, &NotSingularError{settinghistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (shq *SettingHistoryQuery) OnlyX(ctx context.Context) *SettingHistory {
	node, err := shq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SettingHistory ID in the query.
// Returns a *NotSingularError when more than one SettingHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (shq *SettingHistoryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = shq.Limit(2).IDs(setContextOp(ctx, shq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{settinghistory.Label}
	default:
		err = &NotSingularError{settinghistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (shq *SettingHistoryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := shq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SettingHistories.
func (shq *SettingHistoryQuery) All(ctx context.Context) ([]*SettingHistory, error) {
	ctx = setContextOp(ctx, shq.ctx, ent.OpQueryAll)
	if err := shq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SettingHistory, *SettingHistoryQuery]()
	return withInterceptors[[]*SettingHistory](ctx, shq, qr, shq.inters)
}

// AllX is like All, but panics if an error occurs.
func (shq *SettingHistoryQuery) AllX(ctx context.Context) []*SettingHistory {
	nodes, err := shq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SettingHistory IDs.
func (shq *SettingHistoryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if shq.ctx.Unique == nil && shq.path != nil {
		shq.Unique(true)
	}
	ctx = setContextOp(ctx, shq.ctx, ent.OpQueryIDs)
	if err = shq.Select(settinghistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (shq *SettingHistoryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := shq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (shq *SettingHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, shq.ctx, ent.OpQueryCount)
	if err := shq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, shq, querierCount[*SettingHistoryQuery](), shq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (shq *SettingHistoryQuery) CountX(ctx context.Context) int {
	count, err := shq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (shq *SettingHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, shq.ctx, ent.OpQueryExist)
	switch _, err := shq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (shq *SettingHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := shq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SettingHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (shq *SettingHistoryQuery) Clone() *SettingHistoryQuery {
	if shq == nil {
		return nil
	}
	return &SettingHistoryQuery{
		config:     shq.config,
		ctx:        shq.ctx.Clone(),
		order:      append([]settinghistory.OrderOption{}, shq.order...),
		inters:     append([]Interceptor{}, shq.inters...),
		predicates: append([]predicate.SettingHistory{}, shq.predicates...),
		// clone intermediate query.
		sql:  shq.sql.Clone(),
		path: shq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Section string `json:"section,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SettingHistory.Query().
//		GroupBy(settinghistory.FieldSection).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (shq *SettingHistoryQuery) GroupBy(field string, fields ...string) *SettingHistoryGroupBy {
	shq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SettingHistoryGroupBy{build: shq}
	grbuild.flds = &shq.ctx.Fields
	grbuild.label = settinghistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Section string `json:"section,omitempty"`
//	}
//
//	client.SettingHistory.Query().
//		Select(settinghistory.FieldSection).
//		Scan(ctx, &v)
func (shq *SettingHistoryQuery) Select(fields ...string) *SettingHistorySelect {
	shq.ctx.Fields = append(shq.ctx.Fields, fields...)
	sbuild := &SettingHistorySelect{SettingHistoryQuery: shq}
	sbuild.label = settinghistory.Label
	sbuild.flds, sbuild.scan = &shq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SettingHistorySelect configured with the given aggregations.
func (shq *SettingHistoryQuery) Aggregate(fns ...AggregateFunc) *SettingHistorySelect {
	return shq.Select().Aggregate(fns...)
}

func (shq *SettingHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range shq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, shq); err != nil {
				return err
			}
		}
	}
	for _, f := range shq.ctx.Fields {
		if !settinghistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if shq.path != nil {
		prev, err := shq.path(ctx)
		if err != nil {
			return err
		}
		shq.sql = prev
	}
	return nil
}

func (shq *SettingHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SettingHistory, error) {
	var (
		nodes = []*SettingHistory{}
		_spec = shq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SettingHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SettingHistory{config: shq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, shq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (shq *SettingHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := shq.querySpec()
	_spec.Node.Columns = shq.ctx.Fields
	if len(shq.ctx.Fields) > 0 {
		_spec.Unique = shq.ctx.Unique != nil && *shq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, shq.driver, _spec)
}

func (shq *SettingHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(settinghistory.Table, settinghistory.Columns, sqlgraph.NewFieldSpec(settinghistory.FieldID, field.TypeUUID))
	_spec.From = shq.sql
	if unique := shq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if shq.path != nil {
		_spec.Unique = true
	}
	if fields := shq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settinghistory.FieldID)
		for i := range fields {
			if fields[i] != settinghistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := shq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := shq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := shq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := shq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (shq *SettingHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(shq.driver.Dialect())
	t1 := builder.Table(settinghistory.Table)
	columns := shq.ctx.Fields
	if len(columns) == 0 {
		columns = settinghistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if shq.sql != nil {
		selector = shq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if shq.ctx.Unique != nil && *shq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range shq.predicates {
		p(selector)
	}
	for _, p := range shq.order {
		p(selector)
	}
	if offset := shq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := shq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SettingHistoryGroupBy is the group-by builder for SettingHistory entities.
type SettingHistoryGroupBy struct {
	selector
	build *SettingHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (shgb *SettingHistoryGroupBy) Aggregate(fns ...AggregateFunc) *SettingHistoryGroupBy {
	shgb.fns = append(shgb.fns, fns...)
	return shgb
}

// Scan applies the selector query and scans the result into the given value.
func (shgb *SettingHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, shgb.build.ctx, ent.OpQueryGroupBy)
	if err := shgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SettingHistoryQuery, *SettingHistoryGroupBy](ctx, shgb.build, shgb, shgb.build.inters, v)
}

func (shgb *SettingHistoryGroupBy) sqlScan(ctx context.Context, root *SettingHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(shgb.fns))
	for _, fn := range shgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*shgb.flds)+len(shgb.fns))
		for _, f := range *shgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*shgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := shgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SettingHistorySelect is the builder for selecting fields of SettingHistory entities.
type SettingHistorySelect struct {
	*SettingHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (shs *SettingHistorySelect) Aggregate(fns ...AggregateFunc) *SettingHistorySelect {
	shs.fns = append(shs.fns, fns...)
	return shs
}

// Scan applies the selector query and scans the result into the given value.
func (shs *SettingHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, shs.ctx, ent.OpQuerySelect)
	if err := shs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SettingHistoryQuery, *SettingHistorySelect](ctx, shs.SettingHistoryQuery, shs, shs.inters, v)
}

func (shs *SettingHistorySelect) sqlScan(ctx context.Context, root *SettingHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(shs.fns))
	for _, fn := range shs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*shs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := shs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
