// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NeoPlayful/maple-gateway/server/ent/settinghistory"
	"github.com/google/uuid"
)

// SettingHistoryCreate is the builder for creating a SettingHistory entity.
type SettingHistoryCreate struct {
	config
	mutation *SettingHistoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSection sets the "section" field.
func (shc *SettingHistoryCreate) SetSection(s string) *SettingHistoryCreate {
	shc.mutation.SetSection(s)
	return shc
}

// SetKey sets the "key" field.
func (shc *SettingHistoryCreate) SetKey(s string) *SettingHistoryCreate {
	shc.mutation.SetKey(s)
	return shc
}

// SetVersion sets the "version" field.
func (shc *SettingHistoryCreate) SetVersion(i int) *SettingHistoryCreate {
	shc.mutation.SetVersion(i)
	return shc
}

// SetValue sets the "value" field.
func (shc *SettingHistoryCreate) SetValue(jm json.RawMessage) *SettingHistoryCreate {
	shc.mutation.SetValue(jm)
	return shc
}

// SetCreatedAt sets the "created_at" field.
func (shc *SettingHistoryCreate) SetCreatedAt(t time.Time) *SettingHistoryCreate {
	shc.mutation.SetCreatedAt(t)
	return shc
}

// SetID sets the "id" field.
func (shc *SettingHistoryCreate) SetID(u uuid.UUID) *SettingHistoryCreate {
	shc.mutation.SetID(u)
	return shc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (shc *SettingHistoryCreate) SetNillableID(u *uuid.UUID) *SettingHistoryCreate {
	if u != nil {
		shc.SetID(*u)
	}
	return shc
}

// Mutation returns the SettingHistoryMutation object of the builder.
func (shc *SettingHistoryCreate) Mutation() *SettingHistoryMutation {
	return shc.mutation
}

// Save creates the SettingHistory in the database.
func (shc *SettingHistoryCreate) Save(ctx context.Context) (*SettingHistory, error) {
	shc.defaults()
	return withHooks(ctx, shc.sqlSave, shc.mutation, shc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (shc *SettingHistoryCreate) SaveX(ctx context.Context) *SettingHistory {
	v, err := shc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (shc *SettingHistoryCreate) Exec(ctx context.Context) error {
	_, err := shc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (shc *SettingHistoryCreate) ExecX(ctx context.Context) {
	if err := shc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (shc *SettingHistoryCreate) defaults() {
	if _, ok := shc.mutation.ID(); !ok {
		v := settinghistory.DefaultID()
		shc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (shc *SettingHistoryCreate) check() error {
	if _, ok := shc.mutation.Section(); !ok {
		return &ValidationError{Name: "section", err: errors.New(`ent: missing required field "SettingHistory.section"`)}
	}
	if v, ok := shc.mutation.Section(); ok {
		if err := settinghistory.SectionValidator(v); err != nil {
			return &ValidationError{Name: "section", err: fmt.Errorf(`ent: validator failed for field "SettingHistory.section": %w`, err)}
		}
	}
	if _, ok := shc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "SettingHistory.key"`)}
	}
	if v, ok := shc.mutation.Key(); ok {
		if err := settinghistory.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "SettingHistory.key": %w`, err)}
		}
	}
	if _, ok := shc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "SettingHistory.version"`)}
	}
	if _, ok := shc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "SettingHistory.value"`)}
	}
	if _, ok := shc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SettingHistory.created_at"`)}
	}
	return nil
}

func (shc *SettingHistoryCreate) sqlSave(ctx context.Context) (*SettingHistory, error) {
	if err := shc.check(); err != nil {
		return nil, err
	}
	_node, _spec := shc.createSpec()
	if err := sqlgraph.CreateNode(ctx, shc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	shc.mutation.id = &_node.ID
	shc.mutation.done = true
	return _node, nil
}

func (shc *SettingHistoryCreate) createSpec() (*SettingHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &SettingHistory{config: shc.config}
		_spec = sqlgraph.NewCreateSpec(settinghistory.Table, sqlgraph.NewFieldSpec(settinghistory.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = shc.conflict
	if id, ok := shc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := shc.mutation.Section(); ok {
		_spec.SetField(settinghistory.FieldSection, field.TypeString, value)
		_node.Section = value
	}
	if value, ok := shc.mutation.Key(); ok {
		_spec.SetField(settinghistory.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := shc.mutation.Version(); ok {
		_spec.SetField(settinghistory.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := shc.mutation.Value(); ok {
		_spec.SetField(settinghistory.FieldValue, field.TypeJSON, value)
		_node.Value = value
	}
	if value, ok := shc.mutation.CreatedAt(); ok {
		_spec.SetField(settinghistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SettingHistory.Create().
//		SetSection(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SettingHistoryUpsert) {
//			SetSection(v+v).
//		}).
//		Exec(ctx)
func (shc *SettingHistoryCreate) OnConflict(opts ...sql.ConflictOption) *SettingHistoryUpsertOne {
	shc.conflict = opts
	return &SettingHistoryUpsertOne{
		create: shc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SettingHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (shc *SettingHistoryCreate) OnConflictColumns(columns ...string) *SettingHistoryUpsertOne {
	shc.conflict = append(shc.conflict, sql.ConflictColumns(columns...))
	return &SettingHistoryUpsertOne{
		create: shc,
	}
}

type (
	// SettingHistoryUpsertOne is the builder for "upsert"-ing
	//  one SettingHistory node.
	SettingHistoryUpsertOne struct {
		create *SettingHistoryCreate
	}

	// SettingHistoryUpsert is the "OnConflict" setter.
	SettingHistoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetSection sets the "section" field.
func (u *SettingHistoryUpsert) SetSection(v string) *SettingHistoryUpsert {
	u.Set(settinghistory.FieldSection, v)
	return u
}

// UpdateSection sets the "section" field to the value that was provided on create.
func (u *SettingHistoryUpsert) UpdateSection() *SettingHistoryUpsert {
	u.SetExcluded(settinghistory.FieldSection)
	return u
}

// SetKey sets the "key" field.
func (u *SettingHistoryUpsert) SetKey(v string) *SettingHistoryUpsert {
	u.Set(settinghistory.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *SettingHistoryUpsert) UpdateKey() *SettingHistoryUpsert {
	u.SetExcluded(settinghistory.FieldKey)
	return u
}

// SetVersion sets the "version" field.
func (u *SettingHistoryUpsert) SetVersion(v int) *SettingHistoryUpsert {
	u.Set(settinghistory.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SettingHistoryUpsert) UpdateVersion() *SettingHistoryUpsert {
	u.SetExcluded(settinghistory.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *SettingHistoryUpsert) AddVersion(v int) *SettingHistoryUpsert {
	u.Add(settinghistory.FieldVersion, v)
	return u
}

// SetValue sets the "value" field.
func (u *SettingHistoryUpsert) SetValue(v json.RawMessage) *SettingHistoryUpsert {
	u.Set(settinghistory.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SettingHistoryUpsert) UpdateValue() *SettingHistoryUpsert {
	u.SetExcluded(settinghistory.FieldValue)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SettingHistoryUpsert) SetCreatedAt(v time.Time) *SettingHistoryUpsert {
	u.Set(settinghistory.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SettingHistoryUpsert) UpdateCreatedAt() *SettingHistoryUpsert {
	u.SetExcluded(settinghistory.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SettingHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(settinghistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SettingHistoryUpsertOne) UpdateNewValues() *SettingHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(settinghistory.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SettingHistory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SettingHistoryUpsertOne) Ignore() *SettingHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SettingHistoryUpsertOne) DoNothing() *SettingHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SettingHistoryCreate.OnConflict
// documentation for more info.
func (u *SettingHistoryUpsertOne) Update(set func(*SettingHistoryUpsert)) *SettingHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SettingHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetSection sets the "section" field.
func (u *SettingHistoryUpsertOne) SetSection(v string) *SettingHistoryUpsertOne {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.SetSection(v)
	})
}

// UpdateSection sets the "section" field to the value that was provided on create.
func (u *SettingHistoryUpsertOne) UpdateSection() *SettingHistoryUpsertOne {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.UpdateSection()
	})
}

// SetKey sets the "key" field.
func (u *SettingHistoryUpsertOne) SetKey(v string) *SettingHistoryUpsertOne {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *SettingHistoryUpsertOne) UpdateKey() *SettingHistoryUpsertOne {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.UpdateKey()
	})
}

// SetVersion sets the "version" field.
func (u *SettingHistoryUpsertOne) SetVersion(v int) *SettingHistoryUpsertOne {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SettingHistoryUpsertOne) AddVersion(v int) *SettingHistoryUpsertOne {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SettingHistoryUpsertOne) UpdateVersion() *SettingHistoryUpsertOne {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.UpdateVersion()
	})
}

// SetValue sets the "value" field.
func (u *SettingHistoryUpsertOne) SetValue(v json.RawMessage) *SettingHistoryUpsertOne {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SettingHistoryUpsertOne) UpdateValue() *SettingHistoryUpsertOne {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.UpdateValue()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SettingHistoryUpsertOne) SetCreatedAt(v time.Time) *SettingHistoryUpsertOne {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SettingHistoryUpsertOne) UpdateCreatedAt() *SettingHistoryUpsertOne {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *SettingHistoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SettingHistoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SettingHistoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SettingHistoryUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SettingHistoryUpsertOne.ID is not supported by MySQL driver. Use SettingHistoryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SettingHistoryUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SettingHistoryCreateBulk is the builder for creating many SettingHistory entities in bulk.
type SettingHistoryCreateBulk struct {
	config
	err      error
	builders []*SettingHistoryCreate
	conflict []sql.ConflictOption
}

// Save creates the SettingHistory entities in the database.
func (shcb *SettingHistoryCreateBulk) Save(ctx context.Context) ([]*SettingHistory, error) {
	if shcb.err != nil {
		return nil, shcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(shcb.builders))
	nodes := make([]*SettingHistory, len(shcb.builders))
	mutators := make([]Mutator, len(shcb.builders))
	for i := range shcb.builders {
		func(i int, root context.Context) {
			builder := shcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SettingHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, shcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = shcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, shcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, shcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (shcb *SettingHistoryCreateBulk) SaveX(ctx context.Context) []*SettingHistory {
	v, err := shcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (shcb *SettingHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := shcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (shcb *SettingHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := shcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SettingHistory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SettingHistoryUpsert) {
//			SetSection(v+v).
//		}).
//		Exec(ctx)
func (shcb *SettingHistoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *SettingHistoryUpsertBulk {
	shcb.conflict = opts
	return &SettingHistoryUpsertBulk{
		create: shcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SettingHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (shcb *SettingHistoryCreateBulk) OnConflictColumns(columns ...string) *SettingHistoryUpsertBulk {
	shcb.conflict = append(shcb.conflict, sql.ConflictColumns(columns...))
	return &SettingHistoryUpsertBulk{
		create: shcb,
	}
}

// SettingHistoryUpsertBulk is the builder for "upsert"-ing
// a bulk of SettingHistory nodes.
type SettingHistoryUpsertBulk struct {
	create *SettingHistoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SettingHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(settinghistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SettingHistoryUpsertBulk) UpdateNewValues() *SettingHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(settinghistory.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SettingHistory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SettingHistoryUpsertBulk) Ignore() *SettingHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SettingHistoryUpsertBulk) DoNothing() *SettingHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SettingHistoryCreateBulk.OnConflict
// documentation for more info.
func (u *SettingHistoryUpsertBulk) Update(set func(*SettingHistoryUpsert)) *SettingHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SettingHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetSection sets the "section" field.
func (u *SettingHistoryUpsertBulk) SetSection(v string) *SettingHistoryUpsertBulk {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.SetSection(v)
	})
}

// UpdateSection sets the "section" field to the value that was provided on create.
func (u *SettingHistoryUpsertBulk) UpdateSection() *SettingHistoryUpsertBulk {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.UpdateSection()
	})
}

// SetKey sets the "key" field.
func (u *SettingHistoryUpsertBulk) SetKey(v string) *SettingHistoryUpsertBulk {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *SettingHistoryUpsertBulk) UpdateKey() *SettingHistoryUpsertBulk {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.UpdateKey()
	})
}

// SetVersion sets the "version" field.
func (u *SettingHistoryUpsertBulk) SetVersion(v int) *SettingHistoryUpsertBulk {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SettingHistoryUpsertBulk) AddVersion(v int) *SettingHistoryUpsertBulk {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SettingHistoryUpsertBulk) UpdateVersion() *SettingHistoryUpsertBulk {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.UpdateVersion()
	})
}

// SetValue sets the "value" field.
func (u *SettingHistoryUpsertBulk) SetValue(v json.RawMessage) *SettingHistoryUpsertBulk {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SettingHistoryUpsertBulk) UpdateValue() *SettingHistoryUpsertBulk {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.UpdateValue()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SettingHistoryUpsertBulk) SetCreatedAt(v time.Time) *SettingHistoryUpsertBulk {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SettingHistoryUpsertBulk) UpdateCreatedAt() *SettingHistoryUpsertBulk {
	return u.Update(func(s *SettingHistoryUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *SettingHistoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SettingHistoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SettingHistoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SettingHistoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
