// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/NeoPlayful/maple-gateway/server/ent/service"
	"github.com/NeoPlayful/maple-gateway/server/ent/trafficpolicy"
	"github.com/google/uuid"
)

// TrafficPolicy is the model entity for the TrafficPolicy schema.
type TrafficPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ServiceID holds the value of the "service_id" field.
	ServiceID uuid.UUID `json:"service_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Match holds the value of the "match" field.
	Match json.RawMessage `json:"match,omitempty"`
	// TargetVersionID holds the value of the "target_version_id" field.
	TargetVersionID *uuid.UUID `json:"target_version_id,omitempty"`
	// Weight holds the value of the "weight" field.
	Weight int `json:"weight,omitempty"`
	// Sticky holds the value of the "sticky" field.
	Sticky json.RawMessage `json:"sticky,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance string `json:"balance,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TrafficPolicyQuery when eager-loading is set.
	Edges        TrafficPolicyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TrafficPolicyEdges holds the relations/edges for other nodes in the graph.
type TrafficPolicyEdges struct {
	// Service holds the value of the service edge.
	Service *Service `json:"service,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ServiceOrErr returns the Service value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TrafficPolicyEdges) ServiceOrErr() (*Service, error) {
	if e.Service != nil {
		return e.Service, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: service.Label}
	}
	return nil, &NotLoadedError{edge: "service"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TrafficPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case trafficpolicy.FieldTargetVersionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case trafficpolicy.FieldMatch, trafficpolicy.FieldSticky:
			values[i] = new([]byte)
		case trafficpolicy.FieldPriority, trafficpolicy.FieldWeight:
			values[i] = new(sql.NullInt64)
		case trafficpolicy.FieldName, trafficpolicy.FieldBalance, trafficpolicy.FieldStatus:
			values[i] = new(sql.NullString)
		case trafficpolicy.FieldCreatedAt, trafficpolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case trafficpolicy.FieldID, trafficpolicy.FieldServiceID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TrafficPolicy fields.
func (tp *TrafficPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case trafficpolicy.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				tp.ID = *value
			}
		case trafficpolicy.FieldServiceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field service_id", values[i])
			} else if value != nil {
				tp.ServiceID = *value
			}
		case trafficpolicy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				tp.Name = value.String
			}
		case trafficpolicy.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				tp.Priority = int(value.Int64)
			}
		case trafficpolicy.FieldMatch:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field match", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tp.Match); err != nil {
					return fmt.Errorf("unmarshal field match: %w", err)
				}
			}
		case trafficpolicy.FieldTargetVersionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field target_version_id", values[i])
			} else if value.Valid {
				tp.TargetVersionID = new(uuid.UUID)
				*tp.TargetVersionID = *value.S.(*uuid.UUID)
			}
		case trafficpolicy.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				tp.Weight = int(value.Int64)
			}
		case trafficpolicy.FieldSticky:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field sticky", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tp.Sticky); err != nil {
					return fmt.Errorf("unmarshal field sticky: %w", err)
				}
			}
		case trafficpolicy.FieldBalance:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				tp.Balance = value.String
			}
		case trafficpolicy.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				tp.Status = value.String
			}
		case trafficpolicy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				tp.CreatedAt = value.Time
			}
		case trafficpolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				tp.UpdatedAt = value.Time
			}
		default:
			tp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TrafficPolicy.
// This includes values selected through modifiers, order, etc.
func (tp *TrafficPolicy) Value(name string) (ent.Value, error) {
	return tp.selectValues.Get(name)
}

// QueryService queries the "service" edge of the TrafficPolicy entity.
func (tp *TrafficPolicy) QueryService() *ServiceQuery {
	return NewTrafficPolicyClient(tp.config).QueryService(tp)
}

// Update returns a builder for updating this TrafficPolicy.
// Note that you need to call TrafficPolicy.Unwrap() before calling this method if this TrafficPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (tp *TrafficPolicy) Update() *TrafficPolicyUpdateOne {
	return NewTrafficPolicyClient(tp.config).UpdateOne(tp)
}

// Unwrap unwraps the TrafficPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tp *TrafficPolicy) Unwrap() *TrafficPolicy {
	_tx, ok := tp.config.driver.(*txDriver)
	if !ok {
		panic("ent: TrafficPolicy is not a transactional entity")
	}
	tp.config.driver = _tx.drv
	return tp
}

// String implements the fmt.Stringer.
func (tp *TrafficPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("TrafficPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tp.ID))
	builder.WriteString("service_id=")
	builder.WriteString(fmt.Sprintf("%v", tp.ServiceID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(tp.Name)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", tp.Priority))
	builder.WriteString(", ")
	builder.WriteString("match=")
	builder.WriteString(fmt.Sprintf("%v", tp.Match))
	builder.WriteString(", ")
	if v := tp.TargetVersionID; v != nil {
		builder.WriteString("target_version_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", tp.Weight))
	builder.WriteString(", ")
	builder.WriteString("sticky=")
	builder.WriteString(fmt.Sprintf("%v", tp.Sticky))
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(tp.Balance)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(tp.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(tp.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(tp.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TrafficPolicies is a parsable slice of TrafficPolicy.
type TrafficPolicies []*TrafficPolicy
