// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NeoPlayful/maple-gateway/server/ent/predicate"
	"github.com/NeoPlayful/maple-gateway/server/ent/service"
	"github.com/NeoPlayful/maple-gateway/server/ent/trafficpolicy"
	"github.com/google/uuid"
)

// TrafficPolicyQuery is the builder for querying TrafficPolicy entities.
type TrafficPolicyQuery struct {
	config
	ctx         *QueryContext
	order       []trafficpolicy.OrderOption
	inters      []Interceptor
	predicates  []predicate.TrafficPolicy
	withService *ServiceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TrafficPolicyQuery builder.
func (tpq *TrafficPolicyQuery) Where(ps ...predicate.TrafficPolicy) *TrafficPolicyQuery {
	tpq.predicates = append(tpq.predicates, ps...)
	return tpq
}

// Limit the number of records to be returned by this query.
func (tpq *TrafficPolicyQuery) Limit(limit int) *TrafficPolicyQuery {
	tpq.ctx.Limit = &limit
	return tpq
}

// Offset to start from.
func (tpq *TrafficPolicyQuery) Offset(offset int) *TrafficPolicyQuery {
	tpq.ctx.Offset = &offset
	return tpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tpq *TrafficPolicyQuery) Unique(unique bool) *TrafficPolicyQuery {
	tpq.ctx.Unique = &unique
	return tpq
}

// Order specifies how the records should be ordered.
func (tpq *TrafficPolicyQuery) Order(o ...trafficpolicy.OrderOption) *TrafficPolicyQuery {
	tpq.order = append(tpq.order, o...)
	return tpq
}

// QueryService chains the current query on the "service" edge.
func (tpq *TrafficPolicyQuery) QueryService() *ServiceQuery {
	query := (&ServiceClient{config: tpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(trafficpolicy.Table, trafficpolicy.FieldID, selector),
			sqlgraph.To(service.Table, service.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, trafficpolicy.ServiceTable, trafficpolicy.ServiceColumn),
		)
		fromU = sqlgraph.SetNeighbors(tpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TrafficPolicy entity from the query.
// Returns a *NotFoundError when no TrafficPolicy was found.
func (tpq *TrafficPolicyQuery) First(ctx context.Context) (*TrafficPolicy, error) {
	nodes, err := tpq.Limit(1).All(setContextOp(ctx, tpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{trafficpolicy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tpq *TrafficPolicyQuery) FirstX(ctx context.Context) *TrafficPolicy {
	node, err := tpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TrafficPolicy ID from the query.
// Returns a *NotFoundError when no TrafficPolicy ID was found.
func (tpq *TrafficPolicyQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tpq.Limit(1).IDs(setContextOp(ctx, tpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{trafficpolicy.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tpq *TrafficPolicyQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TrafficPolicy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TrafficPolicy entity is found.
// Returns a *NotFoundError when no TrafficPolicy entities are found.
func (tpq *TrafficPolicyQuery) Only(ctx context.Context) (*TrafficPolicy, error) {
	nodes, err := tpq.Limit(2).All(setContextOp(ctx, tpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{trafficpolicy.Label}
	default:
		return nil, &NotSingularError{trafficpolicy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tpq *TrafficPolicyQuery) OnlyX(ctx context.Context) *TrafficPolicy {
	node, err := tpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TrafficPolicy ID in the query.
// Returns a *NotSingularError when more than one TrafficPolicy ID is found.
// Returns a *NotFoundError when no entities are found.
func (tpq *TrafficPolicyQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tpq.Limit(2).IDs(setContextOp(ctx, tpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{trafficpolicy.Label}
	default:
		err = &NotSingularError{trafficpolicy.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tpq *TrafficPolicyQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TrafficPolicies.
func (tpq *TrafficPolicyQuery) All(ctx context.Context) ([]*TrafficPolicy, error) {
	ctx = setContextOp(ctx, tpq.ctx, ent.OpQueryAll)
	if err := tpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TrafficPolicy, *TrafficPolicyQuery]()
	return withInterceptors[[]*TrafficPolicy](ctx, tpq, qr, tpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tpq *TrafficPolicyQuery) AllX(ctx context.Context) []*TrafficPolicy {
	nodes, err := tpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TrafficPolicy IDs.
func (tpq *TrafficPolicyQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tpq.ctx.Unique == nil && tpq.path != nil {
		tpq.Unique(true)
	}
	ctx = setContextOp(ctx, tpq.ctx, ent.OpQueryIDs)
	if err = tpq.Select(trafficpolicy.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tpq *TrafficPolicyQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tpq *TrafficPolicyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tpq.ctx, ent.OpQueryCount)
	if err := tpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tpq, querierCount[*TrafficPolicyQuery](), tpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tpq *TrafficPolicyQuery) CountX(ctx context.Context) int {
	count, err := tpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tpq *TrafficPolicyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tpq.ctx, ent.OpQueryExist)
	switch _, err := tpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tpq *TrafficPolicyQuery) ExistX(ctx context.Context) bool {
	exist, err := tpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TrafficPolicyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tpq *TrafficPolicyQuery) Clone() *TrafficPolicyQuery {
	if tpq == nil {
		return nil
	}
	return &TrafficPolicyQuery{
		config:      tpq.config,
		ctx:         tpq.ctx.Clone(),
		order:       append([]trafficpolicy.OrderOption{}, tpq.order...),
		inters:      append([]Interceptor{}, tpq.inters...),
		predicates:  append([]predicate.TrafficPolicy{}, tpq.predicates...),
		withService: tpq.withService.Clone(),
		// clone intermediate query.
		sql:  tpq.sql.Clone(),
		path: tpq.path,
	}
}

// WithService tells the query-builder to eager-load the nodes that are connected to
// the "service" edge. The optional arguments are used to configure the query builder of the edge.
func (tpq *TrafficPolicyQuery) WithService(opts ...func(*ServiceQuery)) *TrafficPolicyQuery {
	query := (&ServiceClient{config: tpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tpq.withService = query
	return tpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ServiceID uuid.UUID `json:"service_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TrafficPolicy.Query().
//		GroupBy(trafficpolicy.FieldServiceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tpq *TrafficPolicyQuery) GroupBy(field string, fields ...string) *TrafficPolicyGroupBy {
	tpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TrafficPolicyGroupBy{build: tpq}
	grbuild.flds = &tpq.ctx.Fields
	grbuild.label = trafficpolicy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ServiceID uuid.UUID `json:"service_id,omitempty"`
//	}
//
//	client.TrafficPolicy.Query().
//		Select(trafficpolicy.FieldServiceID).
//		Scan(ctx, &v)
func (tpq *TrafficPolicyQuery) Select(fields ...string) *TrafficPolicySelect {
	tpq.ctx.Fields = append(tpq.ctx.Fields, fields...)
	sbuild := &TrafficPolicySelect{TrafficPolicyQuery: tpq}
	sbuild.label = trafficpolicy.Label
	sbuild.flds, sbuild.scan = &tpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TrafficPolicySelect configured with the given aggregations.
func (tpq *TrafficPolicyQuery) Aggregate(fns ...AggregateFunc) *TrafficPolicySelect {
	return tpq.Select().Aggregate(fns...)
}

func (tpq *TrafficPolicyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tpq); err != nil {
				return err
			}
		}
	}
	for _, f := range tpq.ctx.Fields {
		if !trafficpolicy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tpq.path != nil {
		prev, err := tpq.path(ctx)
		if err != nil {
			return err
		}
		tpq.sql = prev
	}
	return nil
}

func (tpq *TrafficPolicyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TrafficPolicy, error) {
	var (
		nodes       = []*TrafficPolicy{}
		_spec       = tpq.querySpec()
		loadedTypes = [1]bool{
			tpq.withService != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TrafficPolicy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TrafficPolicy{config: tpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tpq.withService; query != nil {
		if err := tpq.loadService(ctx, query, nodes, nil,
			func(n *TrafficPolicy, e *Service) { n.Edges.Service = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tpq *TrafficPolicyQuery) loadService(ctx context.Context, query *ServiceQuery, nodes []*TrafficPolicy, init func(*TrafficPolicy), assign func(*TrafficPolicy, *Service)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TrafficPolicy)
	for i := range nodes {
		fk := nodes[i].ServiceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(service.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "service_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tpq *TrafficPolicyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tpq.querySpec()
	_spec.Node.Columns = tpq.ctx.Fields
	if len(tpq.ctx.Fields) > 0 {
		_spec.Unique = tpq.ctx.Unique != nil && *tpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tpq.driver, _spec)
}

func (tpq *TrafficPolicyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(trafficpolicy.Table, trafficpolicy.Columns, sqlgraph.NewFieldSpec(trafficpolicy.FieldID, field.TypeUUID))
	_spec.From = tpq.sql
	if unique := tpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tpq.path != nil {
		_spec.Unique = true
	}
	if fields := tpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trafficpolicy.FieldID)
		for i := range fields {
			if fields[i] != trafficpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tpq.withService != nil {
			_spec.Node.AddColumnOnce(trafficpolicy.FieldServiceID)
		}
	}
	if ps := tpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tpq *TrafficPolicyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tpq.driver.Dialect())
	t1 := builder.Table(trafficpolicy.Table)
	columns := tpq.ctx.Fields
	if len(columns) == 0 {
		columns = trafficpolicy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tpq.sql != nil {
		selector = tpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tpq.ctx.Unique != nil && *tpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tpq.predicates {
		p(selector)
	}
	for _, p := range tpq.order {
		p(selector)
	}
	if offset := tpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TrafficPolicyGroupBy is the group-by builder for TrafficPolicy entities.
type TrafficPolicyGroupBy struct {
	selector
	build *TrafficPolicyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tpgb *TrafficPolicyGroupBy) Aggregate(fns ...AggregateFunc) *TrafficPolicyGroupBy {
	tpgb.fns = append(tpgb.fns, fns...)
	return tpgb
}

// Scan applies the selector query and scans the result into the given value.
func (tpgb *TrafficPolicyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tpgb.build.ctx, ent.OpQueryGroupBy)
	if err := tpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrafficPolicyQuery, *TrafficPolicyGroupBy](ctx, tpgb.build, tpgb, tpgb.build.inters, v)
}

func (tpgb *TrafficPolicyGroupBy) sqlScan(ctx context.Context, root *TrafficPolicyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tpgb.fns))
	for _, fn := range tpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tpgb.flds)+len(tpgb.fns))
		for _, f := range *tpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TrafficPolicySelect is the builder for selecting fields of TrafficPolicy entities.
type TrafficPolicySelect struct {
	*TrafficPolicyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tps *TrafficPolicySelect) Aggregate(fns ...AggregateFunc) *TrafficPolicySelect {
	tps.fns = append(tps.fns, fns...)
	return tps
}

// Scan applies the selector query and scans the result into the given value.
func (tps *TrafficPolicySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tps.ctx, ent.OpQuerySelect)
	if err := tps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrafficPolicyQuery, *TrafficPolicySelect](ctx, tps.TrafficPolicyQuery, tps, tps.inters, v)
}

func (tps *TrafficPolicySelect) sqlScan(ctx context.Context, root *TrafficPolicyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tps.fns))
	for _, fn := range tps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
