// Code generated by ent, DO NOT EDIT.

package deploymentversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/NeoPlayful/maple-gateway/server/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLTE(FieldID, id))
}

// DeploymentID applies equality check predicate on the "deployment_id" field. It's identical to DeploymentIDEQ.
func DeploymentID(v uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldDeploymentID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldVersion, v))
}

// Image applies equality check predicate on the "image" field. It's identical to ImageEQ.
func Image(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldImage, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldWeight, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldStatus, v))
}

// Replicas applies equality check predicate on the "replicas" field. It's identical to ReplicasEQ.
func Replicas(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldReplicas, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldPort, v))
}

// HealthPath applies equality check predicate on the "health_path" field. It's identical to HealthPathEQ.
func HealthPath(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldHealthPath, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeploymentIDEQ applies the EQ predicate on the "deployment_id" field.
func DeploymentIDEQ(v uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldDeploymentID, v))
}

// DeploymentIDNEQ applies the NEQ predicate on the "deployment_id" field.
func DeploymentIDNEQ(v uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNEQ(FieldDeploymentID, v))
}

// DeploymentIDIn applies the In predicate on the "deployment_id" field.
func DeploymentIDIn(vs ...uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIn(FieldDeploymentID, vs...))
}

// DeploymentIDNotIn applies the NotIn predicate on the "deployment_id" field.
func DeploymentIDNotIn(vs ...uuid.UUID) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotIn(FieldDeploymentID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldContainsFold(FieldVersion, v))
}

// ImageEQ applies the EQ predicate on the "image" field.
func ImageEQ(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldImage, v))
}

// ImageNEQ applies the NEQ predicate on the "image" field.
func ImageNEQ(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNEQ(FieldImage, v))
}

// ImageIn applies the In predicate on the "image" field.
func ImageIn(vs ...string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIn(FieldImage, vs...))
}

// ImageNotIn applies the NotIn predicate on the "image" field.
func ImageNotIn(vs ...string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotIn(FieldImage, vs...))
}

// ImageGT applies the GT predicate on the "image" field.
func ImageGT(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGT(FieldImage, v))
}

// ImageGTE applies the GTE predicate on the "image" field.
func ImageGTE(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGTE(FieldImage, v))
}

// ImageLT applies the LT predicate on the "image" field.
func ImageLT(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLT(FieldImage, v))
}

// ImageLTE applies the LTE predicate on the "image" field.
func ImageLTE(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLTE(FieldImage, v))
}

// ImageContains applies the Contains predicate on the "image" field.
func ImageContains(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldContains(FieldImage, v))
}

// ImageHasPrefix applies the HasPrefix predicate on the "image" field.
func ImageHasPrefix(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldHasPrefix(FieldImage, v))
}

// ImageHasSuffix applies the HasSuffix predicate on the "image" field.
func ImageHasSuffix(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldHasSuffix(FieldImage, v))
}

// ImageIsNil applies the IsNil predicate on the "image" field.
func ImageIsNil() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIsNull(FieldImage))
}

// ImageNotNil applies the NotNil predicate on the "image" field.
func ImageNotNil() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotNull(FieldImage))
}

// ImageEqualFold applies the EqualFold predicate on the "image" field.
func ImageEqualFold(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEqualFold(FieldImage, v))
}

// ImageContainsFold applies the ContainsFold predicate on the "image" field.
func ImageContainsFold(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldContainsFold(FieldImage, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLTE(FieldWeight, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldContainsFold(FieldStatus, v))
}

// ReplicasEQ applies the EQ predicate on the "replicas" field.
func ReplicasEQ(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldReplicas, v))
}

// ReplicasNEQ applies the NEQ predicate on the "replicas" field.
func ReplicasNEQ(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNEQ(FieldReplicas, v))
}

// ReplicasIn applies the In predicate on the "replicas" field.
func ReplicasIn(vs ...int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIn(FieldReplicas, vs...))
}

// ReplicasNotIn applies the NotIn predicate on the "replicas" field.
func ReplicasNotIn(vs ...int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotIn(FieldReplicas, vs...))
}

// ReplicasGT applies the GT predicate on the "replicas" field.
func ReplicasGT(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGT(FieldReplicas, v))
}

// ReplicasGTE applies the GTE predicate on the "replicas" field.
func ReplicasGTE(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGTE(FieldReplicas, v))
}

// ReplicasLT applies the LT predicate on the "replicas" field.
func ReplicasLT(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLT(FieldReplicas, v))
}

// ReplicasLTE applies the LTE predicate on the "replicas" field.
func ReplicasLTE(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLTE(FieldReplicas, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v int) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLTE(FieldPort, v))
}

// PortIsNil applies the IsNil predicate on the "port" field.
func PortIsNil() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIsNull(FieldPort))
}

// PortNotNil applies the NotNil predicate on the "port" field.
func PortNotNil() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotNull(FieldPort))
}

// EnvIsNil applies the IsNil predicate on the "env" field.
func EnvIsNil() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIsNull(FieldEnv))
}

// EnvNotNil applies the NotNil predicate on the "env" field.
func EnvNotNil() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotNull(FieldEnv))
}

// ResourcesIsNil applies the IsNil predicate on the "resources" field.
func ResourcesIsNil() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIsNull(FieldResources))
}

// ResourcesNotNil applies the NotNil predicate on the "resources" field.
func ResourcesNotNil() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotNull(FieldResources))
}

// HealthPathEQ applies the EQ predicate on the "health_path" field.
func HealthPathEQ(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldHealthPath, v))
}

// HealthPathNEQ applies the NEQ predicate on the "health_path" field.
func HealthPathNEQ(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNEQ(FieldHealthPath, v))
}

// HealthPathIn applies the In predicate on the "health_path" field.
func HealthPathIn(vs ...string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIn(FieldHealthPath, vs...))
}

// HealthPathNotIn applies the NotIn predicate on the "health_path" field.
func HealthPathNotIn(vs ...string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotIn(FieldHealthPath, vs...))
}

// HealthPathGT applies the GT predicate on the "health_path" field.
func HealthPathGT(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGT(FieldHealthPath, v))
}

// HealthPathGTE applies the GTE predicate on the "health_path" field.
func HealthPathGTE(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGTE(FieldHealthPath, v))
}

// HealthPathLT applies the LT predicate on the "health_path" field.
func HealthPathLT(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLT(FieldHealthPath, v))
}

// HealthPathLTE applies the LTE predicate on the "health_path" field.
func HealthPathLTE(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLTE(FieldHealthPath, v))
}

// HealthPathContains applies the Contains predicate on the "health_path" field.
func HealthPathContains(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldContains(FieldHealthPath, v))
}

// HealthPathHasPrefix applies the HasPrefix predicate on the "health_path" field.
func HealthPathHasPrefix(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldHasPrefix(FieldHealthPath, v))
}

// HealthPathHasSuffix applies the HasSuffix predicate on the "health_path" field.
func HealthPathHasSuffix(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldHasSuffix(FieldHealthPath, v))
}

// HealthPathIsNil applies the IsNil predicate on the "health_path" field.
func HealthPathIsNil() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIsNull(FieldHealthPath))
}

// HealthPathNotNil applies the NotNil predicate on the "health_path" field.
func HealthPathNotNil() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotNull(FieldHealthPath))
}

// HealthPathEqualFold applies the EqualFold predicate on the "health_path" field.
func HealthPathEqualFold(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEqualFold(FieldHealthPath, v))
}

// HealthPathContainsFold applies the ContainsFold predicate on the "health_path" field.
func HealthPathContainsFold(v string) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldContainsFold(FieldHealthPath, v))
}

// NodeSelectorIsNil applies the IsNil predicate on the "node_selector" field.
func NodeSelectorIsNil() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIsNull(FieldNodeSelector))
}

// NodeSelectorNotNil applies the NotNil predicate on the "node_selector" field.
func NodeSelectorNotNil() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotNull(FieldNodeSelector))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasDeployment applies the HasEdge predicate on the "deployment" edge.
func HasDeployment() predicate.DeploymentVersion {
	return predicate.DeploymentVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeploymentTable, DeploymentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeploymentWith applies the HasEdge predicate on the "deployment" edge with a given conditions (other predicates).
func HasDeploymentWith(preds ...predicate.Deployment) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(func(s *sql.Selector) {
		step := newDeploymentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeploymentVersion) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeploymentVersion) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeploymentVersion) predicate.DeploymentVersion {
	return predicate.DeploymentVersion(sql.NotPredicates(p))
}
