// Code generated by ent, DO NOT EDIT.

package bluegreenevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/NeoPlayful/maple-gateway/server/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLTE(FieldID, id))
}

// BgID applies equality check predicate on the "bg_id" field. It's identical to BgIDEQ.
func BgID(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldBgID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldAction, v))
}

// FromActive applies equality check predicate on the "from_active" field. It's identical to FromActiveEQ.
func FromActive(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldFromActive, v))
}

// ToActive applies equality check predicate on the "to_active" field. It's identical to ToActiveEQ.
func ToActive(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldToActive, v))
}

// Detail applies equality check predicate on the "detail" field. It's identical to DetailEQ.
func Detail(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldDetail, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// BgIDEQ applies the EQ predicate on the "bg_id" field.
func BgIDEQ(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldBgID, v))
}

// BgIDNEQ applies the NEQ predicate on the "bg_id" field.
func BgIDNEQ(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNEQ(FieldBgID, v))
}

// BgIDIn applies the In predicate on the "bg_id" field.
func BgIDIn(vs ...uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldIn(FieldBgID, vs...))
}

// BgIDNotIn applies the NotIn predicate on the "bg_id" field.
func BgIDNotIn(vs ...uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNotIn(FieldBgID, vs...))
}

// BgIDGT applies the GT predicate on the "bg_id" field.
func BgIDGT(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGT(FieldBgID, v))
}

// BgIDGTE applies the GTE predicate on the "bg_id" field.
func BgIDGTE(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGTE(FieldBgID, v))
}

// BgIDLT applies the LT predicate on the "bg_id" field.
func BgIDLT(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLT(FieldBgID, v))
}

// BgIDLTE applies the LTE predicate on the "bg_id" field.
func BgIDLTE(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLTE(FieldBgID, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldContainsFold(FieldAction, v))
}

// FromActiveEQ applies the EQ predicate on the "from_active" field.
func FromActiveEQ(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldFromActive, v))
}

// FromActiveNEQ applies the NEQ predicate on the "from_active" field.
func FromActiveNEQ(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNEQ(FieldFromActive, v))
}

// FromActiveIn applies the In predicate on the "from_active" field.
func FromActiveIn(vs ...uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldIn(FieldFromActive, vs...))
}

// FromActiveNotIn applies the NotIn predicate on the "from_active" field.
func FromActiveNotIn(vs ...uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNotIn(FieldFromActive, vs...))
}

// FromActiveGT applies the GT predicate on the "from_active" field.
func FromActiveGT(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGT(FieldFromActive, v))
}

// FromActiveGTE applies the GTE predicate on the "from_active" field.
func FromActiveGTE(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGTE(FieldFromActive, v))
}

// FromActiveLT applies the LT predicate on the "from_active" field.
func FromActiveLT(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLT(FieldFromActive, v))
}

// FromActiveLTE applies the LTE predicate on the "from_active" field.
func FromActiveLTE(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLTE(FieldFromActive, v))
}

// FromActiveIsNil applies the IsNil predicate on the "from_active" field.
func FromActiveIsNil() predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldIsNull(FieldFromActive))
}

// FromActiveNotNil applies the NotNil predicate on the "from_active" field.
func FromActiveNotNil() predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNotNull(FieldFromActive))
}

// ToActiveEQ applies the EQ predicate on the "to_active" field.
func ToActiveEQ(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldToActive, v))
}

// ToActiveNEQ applies the NEQ predicate on the "to_active" field.
func ToActiveNEQ(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNEQ(FieldToActive, v))
}

// ToActiveIn applies the In predicate on the "to_active" field.
func ToActiveIn(vs ...uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldIn(FieldToActive, vs...))
}

// ToActiveNotIn applies the NotIn predicate on the "to_active" field.
func ToActiveNotIn(vs ...uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNotIn(FieldToActive, vs...))
}

// ToActiveGT applies the GT predicate on the "to_active" field.
func ToActiveGT(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGT(FieldToActive, v))
}

// ToActiveGTE applies the GTE predicate on the "to_active" field.
func ToActiveGTE(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGTE(FieldToActive, v))
}

// ToActiveLT applies the LT predicate on the "to_active" field.
func ToActiveLT(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLT(FieldToActive, v))
}

// ToActiveLTE applies the LTE predicate on the "to_active" field.
func ToActiveLTE(v uuid.UUID) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLTE(FieldToActive, v))
}

// ToActiveIsNil applies the IsNil predicate on the "to_active" field.
func ToActiveIsNil() predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldIsNull(FieldToActive))
}

// ToActiveNotNil applies the NotNil predicate on the "to_active" field.
func ToActiveNotNil() predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNotNull(FieldToActive))
}

// DetailEQ applies the EQ predicate on the "detail" field.
func DetailEQ(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldDetail, v))
}

// DetailNEQ applies the NEQ predicate on the "detail" field.
func DetailNEQ(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNEQ(FieldDetail, v))
}

// DetailIn applies the In predicate on the "detail" field.
func DetailIn(vs ...string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldIn(FieldDetail, vs...))
}

// DetailNotIn applies the NotIn predicate on the "detail" field.
func DetailNotIn(vs ...string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNotIn(FieldDetail, vs...))
}

// DetailGT applies the GT predicate on the "detail" field.
func DetailGT(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGT(FieldDetail, v))
}

// DetailGTE applies the GTE predicate on the "detail" field.
func DetailGTE(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGTE(FieldDetail, v))
}

// DetailLT applies the LT predicate on the "detail" field.
func DetailLT(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLT(FieldDetail, v))
}

// DetailLTE applies the LTE predicate on the "detail" field.
func DetailLTE(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLTE(FieldDetail, v))
}

// DetailContains applies the Contains predicate on the "detail" field.
func DetailContains(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldContains(FieldDetail, v))
}

// DetailHasPrefix applies the HasPrefix predicate on the "detail" field.
func DetailHasPrefix(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldHasPrefix(FieldDetail, v))
}

// DetailHasSuffix applies the HasSuffix predicate on the "detail" field.
func DetailHasSuffix(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldHasSuffix(FieldDetail, v))
}

// DetailIsNil applies the IsNil predicate on the "detail" field.
func DetailIsNil() predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldIsNull(FieldDetail))
}

// DetailNotNil applies the NotNil predicate on the "detail" field.
func DetailNotNil() predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNotNull(FieldDetail))
}

// DetailEqualFold applies the EqualFold predicate on the "detail" field.
func DetailEqualFold(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEqualFold(FieldDetail, v))
}

// DetailContainsFold applies the ContainsFold predicate on the "detail" field.
func DetailContainsFold(v string) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldContainsFold(FieldDetail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BluegreenEvent) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BluegreenEvent) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BluegreenEvent) predicate.BluegreenEvent {
	return predicate.BluegreenEvent(sql.NotPredicates(p))
}
