// Code generated by ent, DO NOT EDIT.

package canaryrelease

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the canaryrelease type in the database.
	Label = "canary_release"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServiceID holds the string denoting the service_id field in the database.
	FieldServiceID = "service_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStableVersionID holds the string denoting the stable_version_id field in the database.
	FieldStableVersionID = "stable_version_id"
	// FieldCanaryVersionID holds the string denoting the canary_version_id field in the database.
	FieldCanaryVersionID = "canary_version_id"
	// FieldPhase holds the string denoting the phase field in the database.
	FieldPhase = "phase"
	// FieldCanaryWeight holds the string denoting the canary_weight field in the database.
	FieldCanaryWeight = "canary_weight"
	// FieldTargetWeight holds the string denoting the target_weight field in the database.
	FieldTargetWeight = "target_weight"
	// FieldStepWeight holds the string denoting the step_weight field in the database.
	FieldStepWeight = "step_weight"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the canaryrelease in the database.
	Table = "canary_releases"
)

// Columns holds all SQL columns for canaryrelease fields.
var Columns = []string{
	FieldID,
	FieldServiceID,
	FieldName,
	FieldStableVersionID,
	FieldCanaryVersionID,
	FieldPhase,
	FieldCanaryWeight,
	FieldTargetWeight,
	FieldStepWeight,
	FieldStartedAt,
	FieldFinishedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultPhase holds the default value on creation for the "phase" field.
	DefaultPhase string
	// DefaultCanaryWeight holds the default value on creation for the "canary_weight" field.
	DefaultCanaryWeight int
	// DefaultTargetWeight holds the default value on creation for the "target_weight" field.
	DefaultTargetWeight int
	// DefaultStepWeight holds the default value on creation for the "step_weight" field.
	DefaultStepWeight int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the CanaryRelease queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByServiceID orders the results by the service_id field.
func ByServiceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStableVersionID orders the results by the stable_version_id field.
func ByStableVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStableVersionID, opts...).ToFunc()
}

// ByCanaryVersionID orders the results by the canary_version_id field.
func ByCanaryVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanaryVersionID, opts...).ToFunc()
}

// ByPhase orders the results by the phase field.
func ByPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhase, opts...).ToFunc()
}

// ByCanaryWeight orders the results by the canary_weight field.
func ByCanaryWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanaryWeight, opts...).ToFunc()
}

// ByTargetWeight orders the results by the target_weight field.
func ByTargetWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetWeight, opts...).ToFunc()
}

// ByStepWeight orders the results by the step_weight field.
func ByStepWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStepWeight, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
